//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace DCSControlPanel
{
    
    
    public class ConPump : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.Button button1;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button2;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button3;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button4;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button5;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button6;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button7;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox ConcretPumpGroup1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_CP1_8;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_CP1_forward;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_A061_CP1_forward;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor num_A061_CP1_SetFlowrate;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_CP1_SetRun;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox InlineMixerG1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_CP1_4;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph bar_CP1_tempPump;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph bar_CP1_Pressure;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_CP1_IsReady;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_CP1_IsRun;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph bar_CP1_torque;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_CP1_3;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph bar_CP1_temp;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_CP1_2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_CP1_1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_A061_MI1_speed;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_CP1_backward;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_A061_CP1_backward;
        
        private ABB.Robotics.Tps.Windows.Forms.TabControl tab_CP1_1;
        
        private ABB.Robotics.Tps.Windows.Forms.TabPage tabPage2;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor numEditor3;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_CP1_7;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_CP1_FlushOn;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_CP1_FlushOn;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor num_A061_CP1_DosingFactor;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_CP1_6;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor num_A061_CP1_SetCheckFlowrate;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_CP1_5;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_CP1_CheckOn;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_CP1_CheckOn;
        
        private ABB.Robotics.Tps.Windows.Forms.TabPage tabPage1;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_CP1_DiverError;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_CP1_PowerOn;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_CP1_SaftyGridOn;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button8;
        
        public ConPump()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject1 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject2 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject3 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject4 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject5 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject6 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject7 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject8 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject9 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject10 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject11 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject12 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject13 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject14 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject15 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            this.button1 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button2 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button3 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button4 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button5 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button6 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button7 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button8 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.ConcretPumpGroup1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.InlineMixerG1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.led_CP1_DiverError = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led_CP1_PowerOn = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led_CP1_SaftyGridOn = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.bar_CP1_temp = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.bar_CP1_tempPump = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.bar_CP1_Pressure = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.bar_CP1_torque = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.lab_info_CP1_4 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.led_CP1_IsReady = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led_CP1_IsRun = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.lab_info_CP1_3 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.lab_info_CP1_2 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.lab_info_CP1_1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tab_CP1_1 = new ABB.Robotics.Tps.Windows.Forms.TabControl();
            this.tabPage1 = new ABB.Robotics.Tps.Windows.Forms.TabPage();
            this.btn_A061_CP1_SetRun = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.led_A061_CP1_backward = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.btn_A061_CP1_backward = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.num_A061_CP1_SetFlowrate = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.led_A061_CP1_forward = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.lab_info_CP1_8 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.btn_A061_CP1_forward = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.tabPage2 = new ABB.Robotics.Tps.Windows.Forms.TabPage();
            this.numEditor3 = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.lab_info_CP1_7 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.led_CP1_FlushOn = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.btn_A061_CP1_FlushOn = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.num_A061_CP1_DosingFactor = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.lab_info_CP1_6 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.num_A061_CP1_SetCheckFlowrate = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.lab_info_CP1_5 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.led_CP1_CheckOn = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.btn_A061_CP1_CheckOn = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.lab_A061_MI1_speed = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.ConcretPumpGroup1.SuspendLayout();
            this.InlineMixerG1.SuspendLayout();
            this.tab_CP1_1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.SuspendLayout();
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.Color.White;
            this.button1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button1.Location = new System.Drawing.Point(-1, 360);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(80, 30);
            this.button1.Text = "Main";
            this.button1.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // button2
            // 
            this.button2.BackColor = System.Drawing.Color.White;
            this.button2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button2.Location = new System.Drawing.Point(79, 360);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(80, 30);
            this.button2.Text = "Mixer";
            this.button2.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // button3
            // 
            this.button3.BackColor = System.Drawing.Color.Silver;
            this.button3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button3.Location = new System.Drawing.Point(159, 360);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(80, 30);
            this.button3.Text = "ConPump";
            this.button3.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button3.Click += new System.EventHandler(this.button3_Click);
            // 
            // button4
            // 
            this.button4.BackColor = System.Drawing.Color.White;
            this.button4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button4.Location = new System.Drawing.Point(239, 360);
            this.button4.Name = "button4";
            this.button4.Size = new System.Drawing.Size(80, 30);
            this.button4.Text = "DosPumpH";
            this.button4.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button4.Click += new System.EventHandler(this.button4_Click);
            // 
            // button5
            // 
            this.button5.BackColor = System.Drawing.Color.White;
            this.button5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button5.Location = new System.Drawing.Point(319, 360);
            this.button5.Name = "button5";
            this.button5.Size = new System.Drawing.Size(80, 30);
            this.button5.Text = "DosPumpL";
            this.button5.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button5.Click += new System.EventHandler(this.button5_Click);
            // 
            // button6
            // 
            this.button6.BackColor = System.Drawing.Color.White;
            this.button6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button6.Location = new System.Drawing.Point(399, 360);
            this.button6.Name = "button6";
            this.button6.Size = new System.Drawing.Size(80, 30);
            this.button6.Text = "Sys";
            this.button6.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button6.Click += new System.EventHandler(this.button6_Click);
            // 
            // button7
            // 
            this.button7.BackColor = System.Drawing.Color.White;
            this.button7.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button7.Location = new System.Drawing.Point(479, 360);
            this.button7.Name = "button7";
            this.button7.Size = new System.Drawing.Size(80, 30);
            this.button7.Text = "Robot";
            this.button7.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button7.Click += new System.EventHandler(this.button7_Click);
            // 
            // button8
            // 
            this.button8.BackColor = System.Drawing.Color.White;
            this.button8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button8.Location = new System.Drawing.Point(559, 360);
            this.button8.Name = "button8";
            this.button8.Size = new System.Drawing.Size(80, 30);
            this.button8.Text = "Info";
            this.button8.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button8.Click += new System.EventHandler(this.button8_Click);
            // 
            // ConcretPumpGroup1
            // 
            this.ConcretPumpGroup1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.ConcretPumpGroup1.AutoScroll = false;
            this.ConcretPumpGroup1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.ConcretPumpGroup1.Controls.Add(this.InlineMixerG1);
            this.ConcretPumpGroup1.Controls.Add(this.tab_CP1_1);
            this.ConcretPumpGroup1.Controls.Add(this.lab_A061_MI1_speed);
            this.ConcretPumpGroup1.Dock = System.Windows.Forms.DockStyle.None;
            this.ConcretPumpGroup1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.ConcretPumpGroup1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.ConcretPumpGroup1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.OnlyTopLine;
            this.ConcretPumpGroup1.Location = new System.Drawing.Point(3, 31);
            this.ConcretPumpGroup1.Name = "ConcretPumpGroup1";
            this.ConcretPumpGroup1.Size = new System.Drawing.Size(633, 323);
            this.ConcretPumpGroup1.Tag = null;
            this.ConcretPumpGroup1.Title = "Concrete Pump";
            this.ConcretPumpGroup1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // InlineMixerG1
            // 
            this.InlineMixerG1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.InlineMixerG1.AutoScroll = false;
            this.InlineMixerG1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.InlineMixerG1.Controls.Add(this.led_CP1_DiverError);
            this.InlineMixerG1.Controls.Add(this.led_CP1_PowerOn);
            this.InlineMixerG1.Controls.Add(this.led_CP1_SaftyGridOn);
            this.InlineMixerG1.Controls.Add(this.bar_CP1_temp);
            this.InlineMixerG1.Controls.Add(this.bar_CP1_tempPump);
            this.InlineMixerG1.Controls.Add(this.bar_CP1_Pressure);
            this.InlineMixerG1.Controls.Add(this.bar_CP1_torque);
            this.InlineMixerG1.Controls.Add(this.lab_info_CP1_4);
            this.InlineMixerG1.Controls.Add(this.led_CP1_IsReady);
            this.InlineMixerG1.Controls.Add(this.led_CP1_IsRun);
            this.InlineMixerG1.Controls.Add(this.lab_info_CP1_3);
            this.InlineMixerG1.Controls.Add(this.lab_info_CP1_2);
            this.InlineMixerG1.Controls.Add(this.lab_info_CP1_1);
            this.InlineMixerG1.Dock = System.Windows.Forms.DockStyle.None;
            this.InlineMixerG1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.InlineMixerG1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.InlineMixerG1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.InlineMixerG1.Location = new System.Drawing.Point(3, 23);
            this.InlineMixerG1.Name = "InlineMixerG1";
            this.InlineMixerG1.Size = new System.Drawing.Size(313, 297);
            this.InlineMixerG1.Tag = null;
            this.InlineMixerG1.Title = "Current Staus";
            this.InlineMixerG1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Top;
            // 
            // led_CP1_DiverError
            // 
            this.led_CP1_DiverError.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_CP1DriveError")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_CP1_DiverError.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led_CP1_DiverError.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_CP1_DiverError.Location = new System.Drawing.Point(13, 104);
            this.led_CP1_DiverError.Name = "led_CP1_DiverError";
            this.led_CP1_DiverError.OnValue = "E";
            this.led_CP1_DiverError.Size = new System.Drawing.Size(140, 34);
            this.led_CP1_DiverError.Text = "Driver Error";
            // 
            // led_CP1_PowerOn
            // 
            this.led_CP1_PowerOn.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_CP1PowerOn")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_CP1_PowerOn.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led_CP1_PowerOn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_CP1_PowerOn.Location = new System.Drawing.Point(13, 64);
            this.led_CP1_PowerOn.Name = "led_CP1_PowerOn";
            this.led_CP1_PowerOn.Size = new System.Drawing.Size(140, 34);
            this.led_CP1_PowerOn.Text = "Power On";
            // 
            // led_CP1_SaftyGridOn
            // 
            this.led_CP1_SaftyGridOn.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_CP1SafetyGrid")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_CP1_SaftyGridOn.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led_CP1_SaftyGridOn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_CP1_SaftyGridOn.Location = new System.Drawing.Point(153, 64);
            this.led_CP1_SaftyGridOn.Name = "led_CP1_SaftyGridOn";
            this.led_CP1_SaftyGridOn.Size = new System.Drawing.Size(152, 34);
            this.led_CP1_SaftyGridOn.Text = "Safty Grid";
            // 
            // bar_CP1_temp
            // 
            this.bar_CP1_temp.BarColor = System.Drawing.Color.Maroon;
            this.bar_CP1_temp.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("giA061_CP1StatusTempConFresh")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.bar_CP1_temp.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.bar_CP1_temp.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bar_CP1_temp.Location = new System.Drawing.Point(196, 225);
            this.bar_CP1_temp.Maximum = new decimal(new int[] {
                        80,
                        0,
                        0,
                        0});
            this.bar_CP1_temp.Name = "bar_CP1_temp";
            this.bar_CP1_temp.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.bar_CP1_temp.Precision = 2;
            this.bar_CP1_temp.Size = new System.Drawing.Size(109, 21);
            this.bar_CP1_temp.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.bar_CP1_temp.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // bar_CP1_tempPump
            // 
            this.bar_CP1_tempPump.BarColor = System.Drawing.Color.Maroon;
            this.bar_CP1_tempPump.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("giA061_CP1StatusTempPump")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.bar_CP1_tempPump.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.bar_CP1_tempPump.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bar_CP1_tempPump.Location = new System.Drawing.Point(196, 256);
            this.bar_CP1_tempPump.Maximum = new decimal(new int[] {
                        80,
                        0,
                        0,
                        0});
            this.bar_CP1_tempPump.Name = "bar_CP1_tempPump";
            this.bar_CP1_tempPump.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.bar_CP1_tempPump.Precision = 2;
            this.bar_CP1_tempPump.Size = new System.Drawing.Size(109, 21);
            this.bar_CP1_tempPump.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.bar_CP1_tempPump.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // bar_CP1_Pressure
            // 
            this.bar_CP1_Pressure.BarColor = System.Drawing.Color.Gray;
            this.bar_CP1_Pressure.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("giA061_CP1StatusPressurePump")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.bar_CP1_Pressure.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.bar_CP1_Pressure.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bar_CP1_Pressure.Location = new System.Drawing.Point(196, 188);
            this.bar_CP1_Pressure.Maximum = new decimal(new int[] {
                        40,
                        0,
                        0,
                        0});
            this.bar_CP1_Pressure.Name = "bar_CP1_Pressure";
            this.bar_CP1_Pressure.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.bar_CP1_Pressure.Precision = 2;
            this.bar_CP1_Pressure.Size = new System.Drawing.Size(109, 21);
            this.bar_CP1_Pressure.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.bar_CP1_Pressure.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // bar_CP1_torque
            // 
            this.bar_CP1_torque.BarColor = System.Drawing.Color.Gray;
            this.bar_CP1_torque.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.bar_CP1_torque.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bar_CP1_torque.Location = new System.Drawing.Point(196, 155);
            this.bar_CP1_torque.Maximum = new decimal(new int[] {
                        18,
                        0,
                        0,
                        0});
            this.bar_CP1_torque.Name = "bar_CP1_torque";
            this.bar_CP1_torque.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.bar_CP1_torque.Precision = 2;
            this.bar_CP1_torque.Size = new System.Drawing.Size(109, 21);
            this.bar_CP1_torque.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.bar_CP1_torque.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // lab_info_CP1_4
            // 
            this.lab_info_CP1_4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_CP1_4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_CP1_4.Location = new System.Drawing.Point(13, 256);
            this.lab_info_CP1_4.Multiline = true;
            this.lab_info_CP1_4.Name = "lab_info_CP1_4";
            this.lab_info_CP1_4.Size = new System.Drawing.Size(186, 21);
            this.lab_info_CP1_4.Title = "Pump Temperature[C]";
            // 
            // led_CP1_IsReady
            // 
            this.led_CP1_IsReady.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_CP1IsReady")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_CP1_IsReady.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led_CP1_IsReady.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_CP1_IsReady.Location = new System.Drawing.Point(13, 23);
            this.led_CP1_IsReady.Name = "led_CP1_IsReady";
            this.led_CP1_IsReady.Size = new System.Drawing.Size(140, 34);
            this.led_CP1_IsReady.Text = "Ready";
            // 
            // led_CP1_IsRun
            // 
            this.led_CP1_IsRun.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_CP1IsRun")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_CP1_IsRun.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led_CP1_IsRun.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_CP1_IsRun.Location = new System.Drawing.Point(153, 23);
            this.led_CP1_IsRun.Name = "led_CP1_IsRun";
            this.led_CP1_IsRun.Size = new System.Drawing.Size(152, 34);
            this.led_CP1_IsRun.Text = "Run";
            // 
            // lab_info_CP1_3
            // 
            this.lab_info_CP1_3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_CP1_3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_CP1_3.Location = new System.Drawing.Point(13, 225);
            this.lab_info_CP1_3.Multiline = true;
            this.lab_info_CP1_3.Name = "lab_info_CP1_3";
            this.lab_info_CP1_3.Size = new System.Drawing.Size(186, 21);
            this.lab_info_CP1_3.Title = "Concrete Temperature[C]";
            // 
            // lab_info_CP1_2
            // 
            this.lab_info_CP1_2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_CP1_2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_CP1_2.Location = new System.Drawing.Point(13, 188);
            this.lab_info_CP1_2.Multiline = true;
            this.lab_info_CP1_2.Name = "lab_info_CP1_2";
            this.lab_info_CP1_2.Size = new System.Drawing.Size(177, 24);
            this.lab_info_CP1_2.Title = "Pressure[Bar]";
            // 
            // lab_info_CP1_1
            // 
            this.lab_info_CP1_1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_CP1_1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_CP1_1.Location = new System.Drawing.Point(13, 156);
            this.lab_info_CP1_1.Multiline = true;
            this.lab_info_CP1_1.Name = "lab_info_CP1_1";
            this.lab_info_CP1_1.Size = new System.Drawing.Size(177, 21);
            this.lab_info_CP1_1.Title = "Motor Torque[Nm]";
            // 
            // tab_CP1_1
            // 
            this.tab_CP1_1.AutoScroll = false;
            this.tab_CP1_1.BackColor = System.Drawing.Color.White;
            this.tab_CP1_1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tab_CP1_1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tab_CP1_1.Location = new System.Drawing.Point(322, 23);
            this.tab_CP1_1.Name = "tab_CP1_1";
            this.tab_CP1_1.SelectedIndex = 0;
            this.tab_CP1_1.Size = new System.Drawing.Size(308, 297);
            this.tab_CP1_1.TabPages.Add(this.tabPage1);
            this.tab_CP1_1.TabPages.Add(this.tabPage2);
            // 
            // tabPage1
            // 
            this.tabPage1.Controls.Add(this.btn_A061_CP1_SetRun);
            this.tabPage1.Controls.Add(this.led_A061_CP1_backward);
            this.tabPage1.Controls.Add(this.btn_A061_CP1_backward);
            this.tabPage1.Controls.Add(this.num_A061_CP1_SetFlowrate);
            this.tabPage1.Controls.Add(this.led_A061_CP1_forward);
            this.tabPage1.Controls.Add(this.lab_info_CP1_8);
            this.tabPage1.Controls.Add(this.btn_A061_CP1_forward);
            this.tabPage1.Dock = System.Windows.Forms.DockStyle.None;
            this.tabPage1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tabPage1.Location = new System.Drawing.Point(0, 40);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Size = new System.Drawing.Size(308, 257);
            this.tabPage1.Text = "Operation";
            // 
            // btn_A061_CP1_SetRun
            // 
            this.btn_A061_CP1_SetRun.AllowMultipleStates = true;
            this.btn_A061_CP1_SetRun.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_CP1_SetRun.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_CP1ForwardOn")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_CP1_SetRun.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_CP1_SetRun.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_CP1_SetRun.Location = new System.Drawing.Point(183, 176);
            this.btn_A061_CP1_SetRun.Name = "btn_A061_CP1_SetRun";
            this.btn_A061_CP1_SetRun.Size = new System.Drawing.Size(107, 61);
            stateObject1.Add("Text", "Start");
            stateObject1.Add("BackColor", System.Drawing.Color.White);
            stateObject2.Add("Text", "Stop");
            stateObject2.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CP1_SetRun.States.Add(stateObject1);
            this.btn_A061_CP1_SetRun.States.Add(stateObject2);
            this.btn_A061_CP1_SetRun.Text = "Start/Stop";
            this.btn_A061_CP1_SetRun.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject3.Add("Text", "None");
            stateObject3.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CP1_SetRun.UndefinedState = stateObject3;
            this.btn_A061_CP1_SetRun.Click += new System.EventHandler(this.btn_A061_MI1_SetRun_Click);
            // 
            // led_A061_CP1_backward
            // 
            this.led_A061_CP1_backward.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_CP1BackwardOn")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_A061_CP1_backward.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.led_A061_CP1_backward.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_A061_CP1_backward.Location = new System.Drawing.Point(14, 131);
            this.led_A061_CP1_backward.Name = "led_A061_CP1_backward";
            this.led_A061_CP1_backward.Size = new System.Drawing.Size(163, 32);
            this.led_A061_CP1_backward.Text = "Backward On";
            // 
            // btn_A061_CP1_backward
            // 
            this.btn_A061_CP1_backward.AllowMultipleStates = true;
            this.btn_A061_CP1_backward.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_CP1_backward.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_CP1BackwardOn")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_CP1_backward.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_CP1_backward.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_CP1_backward.Location = new System.Drawing.Point(183, 131);
            this.btn_A061_CP1_backward.Name = "btn_A061_CP1_backward";
            this.btn_A061_CP1_backward.Size = new System.Drawing.Size(107, 32);
            stateObject4.Add("Text", "On");
            stateObject4.Add("BackColor", System.Drawing.Color.White);
            stateObject5.Add("Text", "Off");
            stateObject5.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CP1_backward.States.Add(stateObject4);
            this.btn_A061_CP1_backward.States.Add(stateObject5);
            this.btn_A061_CP1_backward.Text = "On/Off";
            this.btn_A061_CP1_backward.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject6.Add("Text", "None");
            stateObject6.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CP1_backward.UndefinedState = stateObject6;
            this.btn_A061_CP1_backward.Click += new System.EventHandler(this.btn_A061_CP1_backward_Click);
            // 
            // num_A061_CP1_SetFlowrate
            // 
            this.num_A061_CP1_SetFlowrate.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("goA061_CP1SetFlowrate")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.num_A061_CP1_SetFlowrate.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.num_A061_CP1_SetFlowrate.ForeColor = System.Drawing.SystemColors.ControlText;
            this.num_A061_CP1_SetFlowrate.Location = new System.Drawing.Point(185, 24);
            this.num_A061_CP1_SetFlowrate.Maximum = new decimal(new int[] {
                        24,
                        0,
                        0,
                        0});
            this.num_A061_CP1_SetFlowrate.Minimum = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.num_A061_CP1_SetFlowrate.Name = "num_A061_CP1_SetFlowrate";
            this.num_A061_CP1_SetFlowrate.Size = new System.Drawing.Size(105, 33);
            // 
            // led_A061_CP1_forward
            // 
            this.led_A061_CP1_forward.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_CP1ForwardOn")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_A061_CP1_forward.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.led_A061_CP1_forward.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_A061_CP1_forward.Location = new System.Drawing.Point(14, 93);
            this.led_A061_CP1_forward.Name = "led_A061_CP1_forward";
            this.led_A061_CP1_forward.Size = new System.Drawing.Size(163, 32);
            this.led_A061_CP1_forward.Text = "Forward On";
            // 
            // lab_info_CP1_8
            // 
            this.lab_info_CP1_8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_CP1_8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_CP1_8.Location = new System.Drawing.Point(14, 23);
            this.lab_info_CP1_8.Multiline = true;
            this.lab_info_CP1_8.Name = "lab_info_CP1_8";
            this.lab_info_CP1_8.Size = new System.Drawing.Size(163, 33);
            this.lab_info_CP1_8.Title = "Flowrate [L/min]";
            // 
            // btn_A061_CP1_forward
            // 
            this.btn_A061_CP1_forward.AllowMultipleStates = true;
            this.btn_A061_CP1_forward.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_CP1_forward.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_CP1ForwardOn")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_CP1_forward.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_CP1_forward.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_CP1_forward.Location = new System.Drawing.Point(183, 93);
            this.btn_A061_CP1_forward.Name = "btn_A061_CP1_forward";
            this.btn_A061_CP1_forward.Size = new System.Drawing.Size(107, 32);
            stateObject7.Add("Text", "On");
            stateObject7.Add("BackColor", System.Drawing.Color.White);
            stateObject8.Add("Text", "Off");
            stateObject8.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CP1_forward.States.Add(stateObject7);
            this.btn_A061_CP1_forward.States.Add(stateObject8);
            this.btn_A061_CP1_forward.Text = "On/Off";
            this.btn_A061_CP1_forward.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject9.Add("Text", "None");
            stateObject9.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CP1_forward.UndefinedState = stateObject9;
            this.btn_A061_CP1_forward.Click += new System.EventHandler(this.btn_A061_CP1_forward_Click);
            // 
            // tabPage2
            // 
            this.tabPage2.Controls.Add(this.numEditor3);
            this.tabPage2.Controls.Add(this.lab_info_CP1_7);
            this.tabPage2.Controls.Add(this.led_CP1_FlushOn);
            this.tabPage2.Controls.Add(this.btn_A061_CP1_FlushOn);
            this.tabPage2.Controls.Add(this.num_A061_CP1_DosingFactor);
            this.tabPage2.Controls.Add(this.lab_info_CP1_6);
            this.tabPage2.Controls.Add(this.num_A061_CP1_SetCheckFlowrate);
            this.tabPage2.Controls.Add(this.lab_info_CP1_5);
            this.tabPage2.Controls.Add(this.led_CP1_CheckOn);
            this.tabPage2.Controls.Add(this.btn_A061_CP1_CheckOn);
            this.tabPage2.Dock = System.Windows.Forms.DockStyle.None;
            this.tabPage2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tabPage2.Location = new System.Drawing.Point(0, 40);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Size = new System.Drawing.Size(308, 257);
            this.tabPage2.Text = "Calibration";
            // 
            // numEditor3
            // 
            this.numEditor3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.numEditor3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.numEditor3.Location = new System.Drawing.Point(185, 103);
            this.numEditor3.Maximum = new decimal(new int[] {
                        120,
                        0,
                        0,
                        0});
            this.numEditor3.Minimum = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.numEditor3.Name = "numEditor3";
            this.numEditor3.Size = new System.Drawing.Size(105, 33);
            this.numEditor3.Value = new decimal(new int[] {
                        20,
                        0,
                        0,
                        0});
            // 
            // lab_info_CP1_7
            // 
            this.lab_info_CP1_7.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_CP1_7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_CP1_7.Location = new System.Drawing.Point(14, 102);
            this.lab_info_CP1_7.Multiline = true;
            this.lab_info_CP1_7.Name = "lab_info_CP1_7";
            this.lab_info_CP1_7.Size = new System.Drawing.Size(163, 33);
            this.lab_info_CP1_7.Title = "Calib. Time[s]";
            // 
            // led_CP1_FlushOn
            // 
            this.led_CP1_FlushOn.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_CP1FlushOn")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_CP1_FlushOn.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.led_CP1_FlushOn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_CP1_FlushOn.Location = new System.Drawing.Point(14, 195);
            this.led_CP1_FlushOn.Name = "led_CP1_FlushOn";
            this.led_CP1_FlushOn.Size = new System.Drawing.Size(163, 32);
            this.led_CP1_FlushOn.Text = "Flush On";
            // 
            // btn_A061_CP1_FlushOn
            // 
            this.btn_A061_CP1_FlushOn.AllowMultipleStates = true;
            this.btn_A061_CP1_FlushOn.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_CP1_FlushOn.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_CP1FlushOn")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_CP1_FlushOn.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_CP1_FlushOn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_CP1_FlushOn.Location = new System.Drawing.Point(183, 195);
            this.btn_A061_CP1_FlushOn.Name = "btn_A061_CP1_FlushOn";
            this.btn_A061_CP1_FlushOn.Size = new System.Drawing.Size(107, 32);
            stateObject10.Add("Text", "On");
            stateObject10.Add("BackColor", System.Drawing.Color.White);
            stateObject11.Add("Text", "Off");
            stateObject11.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CP1_FlushOn.States.Add(stateObject10);
            this.btn_A061_CP1_FlushOn.States.Add(stateObject11);
            this.btn_A061_CP1_FlushOn.Text = "On/Off";
            this.btn_A061_CP1_FlushOn.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject12.Add("Text", "None");
            stateObject12.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CP1_FlushOn.UndefinedState = stateObject12;
            this.btn_A061_CP1_FlushOn.Click += new System.EventHandler(this.btn_A061_CP1_FlushOn_Click);
            // 
            // num_A061_CP1_DosingFactor
            // 
            this.num_A061_CP1_DosingFactor.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("goA061_CP1SetDosingFactor")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.num_A061_CP1_DosingFactor.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.num_A061_CP1_DosingFactor.ForeColor = System.Drawing.SystemColors.ControlText;
            this.num_A061_CP1_DosingFactor.Location = new System.Drawing.Point(185, 63);
            this.num_A061_CP1_DosingFactor.Maximum = new decimal(new int[] {
                        15,
                        0,
                        0,
                        0});
            this.num_A061_CP1_DosingFactor.Minimum = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.num_A061_CP1_DosingFactor.Name = "num_A061_CP1_DosingFactor";
            this.num_A061_CP1_DosingFactor.Size = new System.Drawing.Size(105, 33);
            // 
            // lab_info_CP1_6
            // 
            this.lab_info_CP1_6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_CP1_6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_CP1_6.Location = new System.Drawing.Point(14, 62);
            this.lab_info_CP1_6.Multiline = true;
            this.lab_info_CP1_6.Name = "lab_info_CP1_6";
            this.lab_info_CP1_6.Size = new System.Drawing.Size(163, 33);
            this.lab_info_CP1_6.Title = "Dosing Factor";
            // 
            // num_A061_CP1_SetCheckFlowrate
            // 
            this.num_A061_CP1_SetCheckFlowrate.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("goA061_CP1SetCheckFlow")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.num_A061_CP1_SetCheckFlowrate.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.num_A061_CP1_SetCheckFlowrate.ForeColor = System.Drawing.SystemColors.ControlText;
            this.num_A061_CP1_SetCheckFlowrate.Location = new System.Drawing.Point(185, 24);
            this.num_A061_CP1_SetCheckFlowrate.Maximum = new decimal(new int[] {
                        24,
                        0,
                        0,
                        0});
            this.num_A061_CP1_SetCheckFlowrate.Minimum = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.num_A061_CP1_SetCheckFlowrate.Name = "num_A061_CP1_SetCheckFlowrate";
            this.num_A061_CP1_SetCheckFlowrate.Size = new System.Drawing.Size(105, 33);
            // 
            // lab_info_CP1_5
            // 
            this.lab_info_CP1_5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_CP1_5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_CP1_5.Location = new System.Drawing.Point(14, 23);
            this.lab_info_CP1_5.Multiline = true;
            this.lab_info_CP1_5.Name = "lab_info_CP1_5";
            this.lab_info_CP1_5.Size = new System.Drawing.Size(163, 33);
            this.lab_info_CP1_5.Title = "Flowrate [L/min]";
            // 
            // led_CP1_CheckOn
            // 
            this.led_CP1_CheckOn.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_CP1CheckOn")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_CP1_CheckOn.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.led_CP1_CheckOn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_CP1_CheckOn.Location = new System.Drawing.Point(14, 157);
            this.led_CP1_CheckOn.Name = "led_CP1_CheckOn";
            this.led_CP1_CheckOn.Size = new System.Drawing.Size(163, 32);
            this.led_CP1_CheckOn.Text = "Check On";
            // 
            // btn_A061_CP1_CheckOn
            // 
            this.btn_A061_CP1_CheckOn.AllowMultipleStates = true;
            this.btn_A061_CP1_CheckOn.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_CP1_CheckOn.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_CP1CheckOn")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_CP1_CheckOn.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_CP1_CheckOn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_CP1_CheckOn.Location = new System.Drawing.Point(183, 157);
            this.btn_A061_CP1_CheckOn.Name = "btn_A061_CP1_CheckOn";
            this.btn_A061_CP1_CheckOn.Size = new System.Drawing.Size(107, 32);
            stateObject13.Add("Text", "On");
            stateObject13.Add("BackColor", System.Drawing.Color.White);
            stateObject14.Add("Text", "Off");
            stateObject14.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CP1_CheckOn.States.Add(stateObject13);
            this.btn_A061_CP1_CheckOn.States.Add(stateObject14);
            this.btn_A061_CP1_CheckOn.Text = "On/Off";
            this.btn_A061_CP1_CheckOn.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject15.Add("Text", "None");
            stateObject15.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CP1_CheckOn.UndefinedState = stateObject15;
            this.btn_A061_CP1_CheckOn.Click += new System.EventHandler(this.btn_A061_CP1_CheckOn_Click);
            // 
            // lab_A061_MI1_speed
            // 
            this.lab_A061_MI1_speed.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_A061_MI1_speed.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_A061_MI1_speed.Location = new System.Drawing.Point(128, 221);
            this.lab_A061_MI1_speed.Multiline = true;
            this.lab_A061_MI1_speed.Name = "lab_A061_MI1_speed";
            this.lab_A061_MI1_speed.Size = new System.Drawing.Size(108, 22);
            this.lab_A061_MI1_speed.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.lab_A061_MI1_speed.Title = "[rpm]";
            // 
            // ConPump
            // 
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.ConcretPumpGroup1);
            this.Controls.Add(this.button8);
            this.Controls.Add(this.button7);
            this.Controls.Add(this.button6);
            this.Controls.Add(this.button5);
            this.Controls.Add(this.button4);
            this.Controls.Add(this.button3);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.button1);
            this.Text = "Digital Casting System";
            this.Controls.SetChildIndex(this.button1, 0);
            this.Controls.SetChildIndex(this.button2, 0);
            this.Controls.SetChildIndex(this.button3, 0);
            this.Controls.SetChildIndex(this.button4, 0);
            this.Controls.SetChildIndex(this.button5, 0);
            this.Controls.SetChildIndex(this.button6, 0);
            this.Controls.SetChildIndex(this.button7, 0);
            this.Controls.SetChildIndex(this.button8, 0);
            this.Controls.SetChildIndex(this.ConcretPumpGroup1, 0);
            this.ConcretPumpGroup1.ResumeLayout(false);
            this.InlineMixerG1.ResumeLayout(false);
            this.tab_CP1_1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage2.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void button2_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Mixer));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button2_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button3_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(ConPump));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button3_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button4_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(DosPumpH));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button4_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button5_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(DosPumpL));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button5_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button6_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Sys));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button6_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button7_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Spare));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button7_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button8_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Spare2));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button8_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button1_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(MainScreen));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button1_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_MI1_SetRun_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalInvert
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_CP1ForwardOn"))).Invert();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_MI1_SetRun_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_CP1_forward_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalInvert
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_CP1ForwardOn"))).Invert();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_CP1_forward_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_CP1_backward_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalInvert
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_CP1BackwardOn"))).Invert();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_CP1_backward_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_CP1_CheckOn_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalInvert
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_CP1CheckOn"))).Invert();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_CP1_CheckOn_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_CP1_FlushOn_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalInvert
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_CP1FlushOn"))).Invert();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_CP1_FlushOn_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
    }
}
