//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace DCSControlPanel
{
    
    
    public class MainInfo : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox InfomationG1;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox3;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph barGraph_D1_2;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph barGraph_D1_1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_D1_2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_D1_1;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox2;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph barGraph_CP1_Pressure;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph barGraph_CP1_ConTemp;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph bar_CP1_torque;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_CP1_2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_CP1_3;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_CP1_1;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph bar_MI1_torqueM2;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph bar_MI1_torqueM1;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph bar_MI1_FunnelTemp;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_M1_4;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph bar_MI1_pressure;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_M1_3;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_M1_2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_M1_1;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph barGraph_CP1_Temperature;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_CP1_4;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox4;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph barGraph_D2_2;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph barGraph_D2_1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel5;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_D2_1;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_info_goMain;
        
        public MainInfo()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.btn_info_goMain = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.InfomationG1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.groupBox4 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.barGraph_D2_2 = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.barGraph_D2_1 = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.tpsLabel5 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.lab_info_D2_1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.groupBox3 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.barGraph_D1_2 = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.barGraph_D1_1 = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.lab_info_D1_2 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.lab_info_D1_1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.groupBox2 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.barGraph_CP1_Temperature = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.lab_info_CP1_4 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.barGraph_CP1_Pressure = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.barGraph_CP1_ConTemp = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.bar_CP1_torque = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.lab_info_CP1_2 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.lab_info_CP1_3 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.lab_info_CP1_1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.groupBox1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.bar_MI1_torqueM2 = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.bar_MI1_torqueM1 = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.bar_MI1_FunnelTemp = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.lab_info_M1_4 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.bar_MI1_pressure = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.lab_info_M1_3 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.lab_info_M1_2 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.lab_info_M1_1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.InfomationG1.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // btn_info_goMain
            // 
            this.btn_info_goMain.BackColor = System.Drawing.Color.White;
            this.btn_info_goMain.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_info_goMain.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_info_goMain.Location = new System.Drawing.Point(480, 340);
            this.btn_info_goMain.Name = "btn_info_goMain";
            this.btn_info_goMain.Size = new System.Drawing.Size(137, 35);
            this.btn_info_goMain.Text = "<--Main";
            this.btn_info_goMain.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.btn_info_goMain.Click += new System.EventHandler(this.btn_goMain);
            // 
            // InfomationG1
            // 
            this.InfomationG1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.InfomationG1.AutoScroll = false;
            this.InfomationG1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.InfomationG1.Controls.Add(this.groupBox4);
            this.InfomationG1.Controls.Add(this.groupBox3);
            this.InfomationG1.Controls.Add(this.groupBox2);
            this.InfomationG1.Controls.Add(this.groupBox1);
            this.InfomationG1.Dock = System.Windows.Forms.DockStyle.None;
            this.InfomationG1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.InfomationG1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.InfomationG1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.InfomationG1.Location = new System.Drawing.Point(0, 31);
            this.InfomationG1.Name = "InfomationG1";
            this.InfomationG1.Size = new System.Drawing.Size(636, 356);
            this.InfomationG1.Tag = null;
            this.InfomationG1.Title = "Machine infomation";
            this.InfomationG1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // groupBox4
            // 
            this.groupBox4.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox4.AutoScroll = false;
            this.groupBox4.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox4.Controls.Add(this.barGraph_D2_2);
            this.groupBox4.Controls.Add(this.barGraph_D2_1);
            this.groupBox4.Controls.Add(this.tpsLabel5);
            this.groupBox4.Controls.Add(this.lab_info_D2_1);
            this.groupBox4.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox4.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox4.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.OnlyTopLine;
            this.groupBox4.Location = new System.Drawing.Point(3, 250);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(627, 53);
            this.groupBox4.Tag = null;
            this.groupBox4.Title = "Dosing Pump 2";
            this.groupBox4.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // barGraph_D2_2
            // 
            this.barGraph_D2_2.BarColor = System.Drawing.Color.SteelBlue;
            this.barGraph_D2_2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.barGraph_D2_2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.barGraph_D2_2.Location = new System.Drawing.Point(502, 27);
            this.barGraph_D2_2.Maximum = new decimal(new int[] {
                        40,
                        0,
                        0,
                        0});
            this.barGraph_D2_2.Name = "barGraph_D2_2";
            this.barGraph_D2_2.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.barGraph_D2_2.Precision = 2;
            this.barGraph_D2_2.Size = new System.Drawing.Size(109, 21);
            this.barGraph_D2_2.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.barGraph_D2_2.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // barGraph_D2_1
            // 
            this.barGraph_D2_1.BarColor = System.Drawing.Color.Gray;
            this.barGraph_D2_1.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("goA061_SP1SetFlowrate")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.barGraph_D2_1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.barGraph_D2_1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.barGraph_D2_1.Location = new System.Drawing.Point(186, 24);
            this.barGraph_D2_1.Maximum = new decimal(new int[] {
                        138,
                        0,
                        0,
                        0});
            this.barGraph_D2_1.Name = "barGraph_D2_1";
            this.barGraph_D2_1.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.barGraph_D2_1.Precision = 1;
            this.barGraph_D2_1.Size = new System.Drawing.Size(109, 21);
            this.barGraph_D2_1.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.barGraph_D2_1.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // tpsLabel5
            // 
            this.tpsLabel5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel5.Location = new System.Drawing.Point(322, 24);
            this.tpsLabel5.Multiline = true;
            this.tpsLabel5.Name = "tpsLabel5";
            this.tpsLabel5.Size = new System.Drawing.Size(177, 24);
            this.tpsLabel5.Title = "spare1";
            // 
            // lab_info_D2_1
            // 
            this.lab_info_D2_1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_D2_1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_D2_1.Location = new System.Drawing.Point(6, 21);
            this.lab_info_D2_1.Multiline = true;
            this.lab_info_D2_1.Name = "lab_info_D2_1";
            this.lab_info_D2_1.Size = new System.Drawing.Size(153, 24);
            this.lab_info_D2_1.Title = "SetFlowrate[ml/min]";
            // 
            // groupBox3
            // 
            this.groupBox3.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox3.AutoScroll = false;
            this.groupBox3.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox3.Controls.Add(this.barGraph_D1_2);
            this.groupBox3.Controls.Add(this.barGraph_D1_1);
            this.groupBox3.Controls.Add(this.lab_info_D1_2);
            this.groupBox3.Controls.Add(this.lab_info_D1_1);
            this.groupBox3.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox3.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox3.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.OnlyTopLine;
            this.groupBox3.Location = new System.Drawing.Point(6, 194);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(627, 53);
            this.groupBox3.Tag = null;
            this.groupBox3.Title = "Dosing Pump 1";
            this.groupBox3.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // barGraph_D1_2
            // 
            this.barGraph_D1_2.BarColor = System.Drawing.Color.SteelBlue;
            this.barGraph_D1_2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.barGraph_D1_2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.barGraph_D1_2.Location = new System.Drawing.Point(499, 27);
            this.barGraph_D1_2.Maximum = new decimal(new int[] {
                        40,
                        0,
                        0,
                        0});
            this.barGraph_D1_2.Name = "barGraph_D1_2";
            this.barGraph_D1_2.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.barGraph_D1_2.Precision = 2;
            this.barGraph_D1_2.Size = new System.Drawing.Size(109, 21);
            this.barGraph_D1_2.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.barGraph_D1_2.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // barGraph_D1_1
            // 
            this.barGraph_D1_1.BarColor = System.Drawing.Color.Gray;
            this.barGraph_D1_1.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("goA061_AP1SetFlowrate")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.barGraph_D1_1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.barGraph_D1_1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.barGraph_D1_1.Location = new System.Drawing.Point(183, 24);
            this.barGraph_D1_1.Maximum = new decimal(new int[] {
                        637,
                        0,
                        0,
                        0});
            this.barGraph_D1_1.Name = "barGraph_D1_1";
            this.barGraph_D1_1.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.barGraph_D1_1.Precision = 1;
            this.barGraph_D1_1.Size = new System.Drawing.Size(109, 21);
            this.barGraph_D1_1.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.barGraph_D1_1.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // lab_info_D1_2
            // 
            this.lab_info_D1_2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_D1_2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_D1_2.Location = new System.Drawing.Point(319, 24);
            this.lab_info_D1_2.Multiline = true;
            this.lab_info_D1_2.Name = "lab_info_D1_2";
            this.lab_info_D1_2.Size = new System.Drawing.Size(177, 24);
            this.lab_info_D1_2.Title = "spare1";
            // 
            // lab_info_D1_1
            // 
            this.lab_info_D1_1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_D1_1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_D1_1.Location = new System.Drawing.Point(3, 21);
            this.lab_info_D1_1.Multiline = true;
            this.lab_info_D1_1.Name = "lab_info_D1_1";
            this.lab_info_D1_1.Size = new System.Drawing.Size(153, 24);
            this.lab_info_D1_1.Title = "SetFlowrate[ml/min]";
            // 
            // groupBox2
            // 
            this.groupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox2.AutoScroll = false;
            this.groupBox2.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox2.Controls.Add(this.barGraph_CP1_Temperature);
            this.groupBox2.Controls.Add(this.lab_info_CP1_4);
            this.groupBox2.Controls.Add(this.barGraph_CP1_Pressure);
            this.groupBox2.Controls.Add(this.barGraph_CP1_ConTemp);
            this.groupBox2.Controls.Add(this.bar_CP1_torque);
            this.groupBox2.Controls.Add(this.lab_info_CP1_2);
            this.groupBox2.Controls.Add(this.lab_info_CP1_3);
            this.groupBox2.Controls.Add(this.lab_info_CP1_1);
            this.groupBox2.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox2.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox2.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.OnlyTopLine;
            this.groupBox2.Location = new System.Drawing.Point(3, 108);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(630, 80);
            this.groupBox2.Tag = null;
            this.groupBox2.Title = "Concrete Pump";
            this.groupBox2.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // barGraph_CP1_Temperature
            // 
            this.barGraph_CP1_Temperature.BarColor = System.Drawing.Color.Maroon;
            this.barGraph_CP1_Temperature.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("giA061_CP1StatusTempPump")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.barGraph_CP1_Temperature.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.barGraph_CP1_Temperature.ForeColor = System.Drawing.SystemColors.ControlText;
            this.barGraph_CP1_Temperature.Location = new System.Drawing.Point(502, 51);
            this.barGraph_CP1_Temperature.Maximum = new decimal(new int[] {
                        80,
                        0,
                        0,
                        0});
            this.barGraph_CP1_Temperature.Name = "barGraph_CP1_Temperature";
            this.barGraph_CP1_Temperature.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.barGraph_CP1_Temperature.Precision = 1;
            this.barGraph_CP1_Temperature.Size = new System.Drawing.Size(109, 21);
            this.barGraph_CP1_Temperature.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.barGraph_CP1_Temperature.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            this.barGraph_CP1_Temperature.Click += new System.EventHandler(this.barGraph9_Click);
            // 
            // lab_info_CP1_4
            // 
            this.lab_info_CP1_4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_CP1_4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_CP1_4.Location = new System.Drawing.Point(319, 48);
            this.lab_info_CP1_4.Multiline = true;
            this.lab_info_CP1_4.Name = "lab_info_CP1_4";
            this.lab_info_CP1_4.Size = new System.Drawing.Size(177, 24);
            this.lab_info_CP1_4.Title = "PumpTemperature[C]";
            // 
            // barGraph_CP1_Pressure
            // 
            this.barGraph_CP1_Pressure.BarColor = System.Drawing.Color.SteelBlue;
            this.barGraph_CP1_Pressure.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("giA061_CP1StatusPressurePump")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.barGraph_CP1_Pressure.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.barGraph_CP1_Pressure.ForeColor = System.Drawing.SystemColors.ControlText;
            this.barGraph_CP1_Pressure.Location = new System.Drawing.Point(502, 27);
            this.barGraph_CP1_Pressure.Maximum = new decimal(new int[] {
                        11,
                        0,
                        0,
                        0});
            this.barGraph_CP1_Pressure.Name = "barGraph_CP1_Pressure";
            this.barGraph_CP1_Pressure.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.barGraph_CP1_Pressure.Precision = 2;
            this.barGraph_CP1_Pressure.Size = new System.Drawing.Size(109, 21);
            this.barGraph_CP1_Pressure.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.barGraph_CP1_Pressure.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // barGraph_CP1_ConTemp
            // 
            this.barGraph_CP1_ConTemp.BarColor = System.Drawing.Color.Maroon;
            this.barGraph_CP1_ConTemp.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("giA061_CP1StatusTempConFresh")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.barGraph_CP1_ConTemp.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.barGraph_CP1_ConTemp.ForeColor = System.Drawing.SystemColors.ControlText;
            this.barGraph_CP1_ConTemp.Location = new System.Drawing.Point(186, 51);
            this.barGraph_CP1_ConTemp.Maximum = new decimal(new int[] {
                        80,
                        0,
                        0,
                        0});
            this.barGraph_CP1_ConTemp.Name = "barGraph_CP1_ConTemp";
            this.barGraph_CP1_ConTemp.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.barGraph_CP1_ConTemp.Precision = 1;
            this.barGraph_CP1_ConTemp.Size = new System.Drawing.Size(109, 21);
            this.barGraph_CP1_ConTemp.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.barGraph_CP1_ConTemp.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // bar_CP1_torque
            // 
            this.bar_CP1_torque.BarColor = System.Drawing.Color.Gray;
            this.bar_CP1_torque.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.bar_CP1_torque.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bar_CP1_torque.Location = new System.Drawing.Point(186, 24);
            this.bar_CP1_torque.Maximum = new decimal(new int[] {
                        1888,
                        0,
                        0,
                        131072});
            this.bar_CP1_torque.Name = "bar_CP1_torque";
            this.bar_CP1_torque.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.bar_CP1_torque.Precision = 2;
            this.bar_CP1_torque.Size = new System.Drawing.Size(109, 21);
            this.bar_CP1_torque.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.bar_CP1_torque.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // lab_info_CP1_2
            // 
            this.lab_info_CP1_2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_CP1_2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_CP1_2.Location = new System.Drawing.Point(319, 24);
            this.lab_info_CP1_2.Multiline = true;
            this.lab_info_CP1_2.Name = "lab_info_CP1_2";
            this.lab_info_CP1_2.Size = new System.Drawing.Size(177, 24);
            this.lab_info_CP1_2.Title = "Pressure[Bar]";
            // 
            // lab_info_CP1_3
            // 
            this.lab_info_CP1_3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_CP1_3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_CP1_3.Location = new System.Drawing.Point(3, 48);
            this.lab_info_CP1_3.Multiline = true;
            this.lab_info_CP1_3.Name = "lab_info_CP1_3";
            this.lab_info_CP1_3.Size = new System.Drawing.Size(177, 24);
            this.lab_info_CP1_3.Title = "ConcreteTemperature[C]";
            // 
            // lab_info_CP1_1
            // 
            this.lab_info_CP1_1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_CP1_1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_CP1_1.Location = new System.Drawing.Point(3, 21);
            this.lab_info_CP1_1.Multiline = true;
            this.lab_info_CP1_1.Name = "lab_info_CP1_1";
            this.lab_info_CP1_1.Size = new System.Drawing.Size(153, 24);
            this.lab_info_CP1_1.Title = "Torque[Nm]";
            // 
            // groupBox1
            // 
            this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox1.AutoScroll = false;
            this.groupBox1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox1.Controls.Add(this.bar_MI1_torqueM2);
            this.groupBox1.Controls.Add(this.bar_MI1_torqueM1);
            this.groupBox1.Controls.Add(this.bar_MI1_FunnelTemp);
            this.groupBox1.Controls.Add(this.lab_info_M1_4);
            this.groupBox1.Controls.Add(this.bar_MI1_pressure);
            this.groupBox1.Controls.Add(this.lab_info_M1_3);
            this.groupBox1.Controls.Add(this.lab_info_M1_2);
            this.groupBox1.Controls.Add(this.lab_info_M1_1);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.OnlyTopLine;
            this.groupBox1.Location = new System.Drawing.Point(3, 21);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(630, 92);
            this.groupBox1.Tag = null;
            this.groupBox1.Title = "Inline Mixer";
            this.groupBox1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // bar_MI1_torqueM2
            // 
            this.bar_MI1_torqueM2.BarColor = System.Drawing.Color.Gray;
            this.bar_MI1_torqueM2.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("giA061_MI1StatusTorqueM2")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.bar_MI1_torqueM2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.bar_MI1_torqueM2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bar_MI1_torqueM2.Location = new System.Drawing.Point(502, 27);
            this.bar_MI1_torqueM2.Maximum = new decimal(new int[] {
                        1888,
                        0,
                        0,
                        131072});
            this.bar_MI1_torqueM2.Name = "bar_MI1_torqueM2";
            this.bar_MI1_torqueM2.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.bar_MI1_torqueM2.Precision = 2;
            this.bar_MI1_torqueM2.Size = new System.Drawing.Size(109, 21);
            this.bar_MI1_torqueM2.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.bar_MI1_torqueM2.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // bar_MI1_torqueM1
            // 
            this.bar_MI1_torqueM1.BarColor = System.Drawing.Color.Gray;
            this.bar_MI1_torqueM1.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("giA061_MI1StatusTorqueM1")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.bar_MI1_torqueM1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.bar_MI1_torqueM1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bar_MI1_torqueM1.Location = new System.Drawing.Point(186, 24);
            this.bar_MI1_torqueM1.Maximum = new decimal(new int[] {
                        1888,
                        0,
                        0,
                        131072});
            this.bar_MI1_torqueM1.Name = "bar_MI1_torqueM1";
            this.bar_MI1_torqueM1.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.bar_MI1_torqueM1.Precision = 2;
            this.bar_MI1_torqueM1.Size = new System.Drawing.Size(109, 21);
            this.bar_MI1_torqueM1.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.bar_MI1_torqueM1.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            this.bar_MI1_torqueM1.Click += new System.EventHandler(this.bar_MI1_torqueM1_Click);
            // 
            // bar_MI1_FunnelTemp
            // 
            this.bar_MI1_FunnelTemp.BarColor = System.Drawing.Color.Maroon;
            this.bar_MI1_FunnelTemp.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("giA061_MI1StatusTempFunnelOut")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.bar_MI1_FunnelTemp.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.bar_MI1_FunnelTemp.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bar_MI1_FunnelTemp.Location = new System.Drawing.Point(186, 57);
            this.bar_MI1_FunnelTemp.Maximum = new decimal(new int[] {
                        80,
                        0,
                        0,
                        0});
            this.bar_MI1_FunnelTemp.Name = "bar_MI1_FunnelTemp";
            this.bar_MI1_FunnelTemp.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.bar_MI1_FunnelTemp.Precision = 1;
            this.bar_MI1_FunnelTemp.Size = new System.Drawing.Size(109, 21);
            this.bar_MI1_FunnelTemp.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.bar_MI1_FunnelTemp.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // lab_info_M1_4
            // 
            this.lab_info_M1_4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_M1_4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_M1_4.Location = new System.Drawing.Point(319, 57);
            this.lab_info_M1_4.Multiline = true;
            this.lab_info_M1_4.Name = "lab_info_M1_4";
            this.lab_info_M1_4.Size = new System.Drawing.Size(177, 24);
            this.lab_info_M1_4.Title = "Pressure[Bar]";
            // 
            // bar_MI1_pressure
            // 
            this.bar_MI1_pressure.BarColor = System.Drawing.Color.SteelBlue;
            this.bar_MI1_pressure.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("giA061_MI1StatusPressureFunnel")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.bar_MI1_pressure.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.bar_MI1_pressure.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bar_MI1_pressure.Location = new System.Drawing.Point(502, 57);
            this.bar_MI1_pressure.Maximum = new decimal(new int[] {
                        11,
                        0,
                        0,
                        0});
            this.bar_MI1_pressure.Name = "bar_MI1_pressure";
            this.bar_MI1_pressure.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.bar_MI1_pressure.Precision = 2;
            this.bar_MI1_pressure.Size = new System.Drawing.Size(109, 21);
            this.bar_MI1_pressure.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.bar_MI1_pressure.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // lab_info_M1_3
            // 
            this.lab_info_M1_3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_M1_3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_M1_3.Location = new System.Drawing.Point(3, 54);
            this.lab_info_M1_3.Multiline = true;
            this.lab_info_M1_3.Name = "lab_info_M1_3";
            this.lab_info_M1_3.Size = new System.Drawing.Size(177, 24);
            this.lab_info_M1_3.Title = "Funnel Temperature[C]";
            // 
            // lab_info_M1_2
            // 
            this.lab_info_M1_2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_M1_2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_M1_2.Location = new System.Drawing.Point(319, 24);
            this.lab_info_M1_2.Multiline = true;
            this.lab_info_M1_2.Name = "lab_info_M1_2";
            this.lab_info_M1_2.Size = new System.Drawing.Size(177, 24);
            this.lab_info_M1_2.Title = "TorqueM2[Nm]";
            // 
            // lab_info_M1_1
            // 
            this.lab_info_M1_1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_M1_1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_M1_1.Location = new System.Drawing.Point(3, 24);
            this.lab_info_M1_1.Multiline = true;
            this.lab_info_M1_1.Name = "lab_info_M1_1";
            this.lab_info_M1_1.Size = new System.Drawing.Size(177, 24);
            this.lab_info_M1_1.Title = "TorqueM1[Nm]";
            // 
            // MainInfo
            // 
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.btn_info_goMain);
            this.Controls.Add(this.InfomationG1);
            this.Text = "Digital Casting System";
            this.Controls.SetChildIndex(this.InfomationG1, 0);
            this.Controls.SetChildIndex(this.btn_info_goMain, 0);
            this.InfomationG1.ResumeLayout(false);
            this.groupBox4.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void btn_goMain(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(MainScreen));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_goMain", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void barGraph9_Click(object sender, System.EventArgs e)
        {
            try
            {
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in barGraph9_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void bar_MI1_torqueM1_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalRead
                ABB.Robotics.ScreenMaker.Base.IApplicationVariable read_0 = this.ScreenServices.ApplicationVariables["Mi1TorqueM1"];
                read_0.Value = ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/giA061_MI1StatusTorqueM1").Value;
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in bar_MI1_torqueM1_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
    }
}
