//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace DCSControlPanel
{
    
    
    public class Mixer : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.Button button1;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button2;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button3;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button4;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button5;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button6;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button7;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox InlineMixerGroup1;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_MI1_SetRun;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_A061_MI1_speed;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_MI1_IsRun;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor num_A061_MI1_SetSpeed;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_MI1_IsReady;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox InlineMixerG2;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox InlineMixerG1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_M1_7;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph bar_MI1_SpeedM1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_M1_6;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph bar_MI1_TempM2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_M1_5;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph bar_MI1_TempM1;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph bar_MI1_torqueM2;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph bar_MI1_torqueM1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_M1_3;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph bar_MI1_temp;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph bar_MI1_pressure;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_M1_2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_M1_1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_M1_4;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button10;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led3;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_M1_8;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_MI1_Enable;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_A061_MI1_enable;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_CC1_Reset;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_A061_CC1_reset;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button8;
        
        public Mixer()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject1 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject2 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject3 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject4 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject5 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject6 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject7 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject8 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject9 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject10 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject11 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject12 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            this.button1 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button2 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button3 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button4 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button5 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button6 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button7 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button8 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.InlineMixerGroup1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.InlineMixerG2 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.btn_A061_CC1_Reset = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.led_A061_CC1_reset = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.button10 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.led3 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.lab_info_M1_8 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.btn_A061_MI1_Enable = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.led_A061_MI1_enable = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.num_A061_MI1_SetSpeed = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.btn_A061_MI1_SetRun = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.InlineMixerG1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.lab_info_M1_7 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.bar_MI1_SpeedM1 = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.lab_info_M1_6 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.bar_MI1_TempM2 = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.lab_info_M1_5 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.bar_MI1_TempM1 = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.bar_MI1_torqueM2 = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.led_MI1_IsReady = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led_MI1_IsRun = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.bar_MI1_torqueM1 = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.lab_info_M1_3 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.bar_MI1_temp = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.bar_MI1_pressure = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.lab_info_M1_2 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.lab_info_M1_1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.lab_info_M1_4 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.lab_A061_MI1_speed = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.InlineMixerGroup1.SuspendLayout();
            this.InlineMixerG2.SuspendLayout();
            this.InlineMixerG1.SuspendLayout();
            this.SuspendLayout();
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.Color.White;
            this.button1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button1.Location = new System.Drawing.Point(-1, 360);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(80, 30);
            this.button1.Text = "Main";
            this.button1.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // button2
            // 
            this.button2.BackColor = System.Drawing.Color.Silver;
            this.button2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button2.Location = new System.Drawing.Point(79, 360);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(80, 30);
            this.button2.Text = "Mixer";
            this.button2.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // button3
            // 
            this.button3.BackColor = System.Drawing.Color.White;
            this.button3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button3.Location = new System.Drawing.Point(159, 360);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(80, 30);
            this.button3.Text = "ConPump";
            this.button3.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button3.Click += new System.EventHandler(this.button3_Click);
            // 
            // button4
            // 
            this.button4.BackColor = System.Drawing.Color.White;
            this.button4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button4.Location = new System.Drawing.Point(239, 360);
            this.button4.Name = "button4";
            this.button4.Size = new System.Drawing.Size(80, 30);
            this.button4.Text = "DosPumpH";
            this.button4.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button4.Click += new System.EventHandler(this.button4_Click);
            // 
            // button5
            // 
            this.button5.BackColor = System.Drawing.Color.White;
            this.button5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button5.Location = new System.Drawing.Point(319, 360);
            this.button5.Name = "button5";
            this.button5.Size = new System.Drawing.Size(80, 30);
            this.button5.Text = "DosPumpL";
            this.button5.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button5.Click += new System.EventHandler(this.button5_Click);
            // 
            // button6
            // 
            this.button6.BackColor = System.Drawing.Color.White;
            this.button6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button6.Location = new System.Drawing.Point(399, 360);
            this.button6.Name = "button6";
            this.button6.Size = new System.Drawing.Size(80, 30);
            this.button6.Text = "Sys";
            this.button6.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button6.Click += new System.EventHandler(this.button6_Click);
            // 
            // button7
            // 
            this.button7.BackColor = System.Drawing.Color.White;
            this.button7.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button7.Location = new System.Drawing.Point(479, 360);
            this.button7.Name = "button7";
            this.button7.Size = new System.Drawing.Size(80, 30);
            this.button7.Text = "Robot";
            this.button7.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button7.Click += new System.EventHandler(this.button7_Click);
            // 
            // button8
            // 
            this.button8.BackColor = System.Drawing.Color.White;
            this.button8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button8.Location = new System.Drawing.Point(559, 360);
            this.button8.Name = "button8";
            this.button8.Size = new System.Drawing.Size(80, 30);
            this.button8.Text = "Info";
            this.button8.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button8.Click += new System.EventHandler(this.button8_Click);
            // 
            // InlineMixerGroup1
            // 
            this.InlineMixerGroup1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.InlineMixerGroup1.AutoScroll = false;
            this.InlineMixerGroup1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.InlineMixerGroup1.Controls.Add(this.InlineMixerG2);
            this.InlineMixerGroup1.Controls.Add(this.InlineMixerG1);
            this.InlineMixerGroup1.Controls.Add(this.lab_A061_MI1_speed);
            this.InlineMixerGroup1.Dock = System.Windows.Forms.DockStyle.None;
            this.InlineMixerGroup1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.InlineMixerGroup1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.InlineMixerGroup1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.OnlyTopLine;
            this.InlineMixerGroup1.Location = new System.Drawing.Point(3, 31);
            this.InlineMixerGroup1.Name = "InlineMixerGroup1";
            this.InlineMixerGroup1.Size = new System.Drawing.Size(633, 323);
            this.InlineMixerGroup1.Tag = null;
            this.InlineMixerGroup1.Title = "Inline Mixer";
            this.InlineMixerGroup1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // InlineMixerG2
            // 
            this.InlineMixerG2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.InlineMixerG2.AutoScroll = false;
            this.InlineMixerG2.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.InlineMixerG2.Controls.Add(this.btn_A061_CC1_Reset);
            this.InlineMixerG2.Controls.Add(this.led_A061_CC1_reset);
            this.InlineMixerG2.Controls.Add(this.button10);
            this.InlineMixerG2.Controls.Add(this.led3);
            this.InlineMixerG2.Controls.Add(this.lab_info_M1_8);
            this.InlineMixerG2.Controls.Add(this.btn_A061_MI1_Enable);
            this.InlineMixerG2.Controls.Add(this.led_A061_MI1_enable);
            this.InlineMixerG2.Controls.Add(this.num_A061_MI1_SetSpeed);
            this.InlineMixerG2.Controls.Add(this.btn_A061_MI1_SetRun);
            this.InlineMixerG2.Dock = System.Windows.Forms.DockStyle.None;
            this.InlineMixerG2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.InlineMixerG2.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.InlineMixerG2.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.InlineMixerG2.Location = new System.Drawing.Point(322, 23);
            this.InlineMixerG2.Name = "InlineMixerG2";
            this.InlineMixerG2.Size = new System.Drawing.Size(308, 297);
            this.InlineMixerG2.Tag = null;
            this.InlineMixerG2.Title = "Operation";
            this.InlineMixerG2.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Top;
            // 
            // btn_A061_CC1_Reset
            // 
            this.btn_A061_CC1_Reset.AllowMultipleStates = true;
            this.btn_A061_CC1_Reset.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_CC1_Reset.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_CC1Reset")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_CC1_Reset.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_CC1_Reset.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_CC1_Reset.Location = new System.Drawing.Point(186, 61);
            this.btn_A061_CC1_Reset.Name = "btn_A061_CC1_Reset";
            this.btn_A061_CC1_Reset.Size = new System.Drawing.Size(107, 32);
            stateObject1.Add("Text", "On");
            stateObject1.Add("BackColor", System.Drawing.Color.White);
            stateObject2.Add("Text", "Off");
            stateObject2.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CC1_Reset.States.Add(stateObject1);
            this.btn_A061_CC1_Reset.States.Add(stateObject2);
            this.btn_A061_CC1_Reset.Text = "On/Off";
            this.btn_A061_CC1_Reset.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject3.Add("Text", "None");
            stateObject3.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CC1_Reset.UndefinedState = stateObject3;
            this.btn_A061_CC1_Reset.Click += new System.EventHandler(this.btn_A061_CC1_Reset_Click);
            // 
            // led_A061_CC1_reset
            // 
            this.led_A061_CC1_reset.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_CC1Reset")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_A061_CC1_reset.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.led_A061_CC1_reset.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_A061_CC1_reset.Location = new System.Drawing.Point(3, 61);
            this.led_A061_CC1_reset.Name = "led_A061_CC1_reset";
            this.led_A061_CC1_reset.Size = new System.Drawing.Size(175, 32);
            this.led_A061_CC1_reset.Text = "Reset";
            // 
            // button10
            // 
            this.button10.AllowMultipleStates = true;
            this.button10.BackColor = System.Drawing.Color.Gainsboro;
            this.button10.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_MI1SetCurvedSpeedMode")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.button10.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.button10.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button10.Location = new System.Drawing.Point(186, 99);
            this.button10.Name = "button10";
            this.button10.Size = new System.Drawing.Size(107, 32);
            stateObject4.Add("Text", "On");
            stateObject4.Add("BackColor", System.Drawing.Color.White);
            stateObject5.Add("Text", "Off");
            stateObject5.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.button10.States.Add(stateObject4);
            this.button10.States.Add(stateObject5);
            this.button10.Text = "On/Off";
            this.button10.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject6.Add("Text", "None");
            stateObject6.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.button10.UndefinedState = stateObject6;
            this.button10.Click += new System.EventHandler(this.button10_Click);
            // 
            // led3
            // 
            this.led3.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_MI1SetCurvedSpeedMode")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.led3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led3.Location = new System.Drawing.Point(3, 99);
            this.led3.Name = "led3";
            this.led3.Size = new System.Drawing.Size(175, 32);
            this.led3.Text = "Curved Speed Mode";
            // 
            // lab_info_M1_8
            // 
            this.lab_info_M1_8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_M1_8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_M1_8.Location = new System.Drawing.Point(17, 174);
            this.lab_info_M1_8.Multiline = true;
            this.lab_info_M1_8.Name = "lab_info_M1_8";
            this.lab_info_M1_8.Size = new System.Drawing.Size(163, 33);
            this.lab_info_M1_8.Title = "Set Speed [rpm]";
            // 
            // btn_A061_MI1_Enable
            // 
            this.btn_A061_MI1_Enable.AllowMultipleStates = true;
            this.btn_A061_MI1_Enable.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_MI1_Enable.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_MI1Enable")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_MI1_Enable.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_MI1_Enable.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_MI1_Enable.Location = new System.Drawing.Point(186, 23);
            this.btn_A061_MI1_Enable.Name = "btn_A061_MI1_Enable";
            this.btn_A061_MI1_Enable.Size = new System.Drawing.Size(107, 32);
            stateObject7.Add("Text", "On");
            stateObject7.Add("BackColor", System.Drawing.Color.White);
            stateObject8.Add("Text", "Off");
            stateObject8.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_MI1_Enable.States.Add(stateObject7);
            this.btn_A061_MI1_Enable.States.Add(stateObject8);
            this.btn_A061_MI1_Enable.Text = "On/Off";
            this.btn_A061_MI1_Enable.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject9.Add("Text", "None");
            stateObject9.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_MI1_Enable.UndefinedState = stateObject9;
            this.btn_A061_MI1_Enable.Click += new System.EventHandler(this.btn_A061_MI1_Enable_Click);
            // 
            // led_A061_MI1_enable
            // 
            this.led_A061_MI1_enable.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_MI1Enable")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_A061_MI1_enable.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.led_A061_MI1_enable.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_A061_MI1_enable.Location = new System.Drawing.Point(3, 23);
            this.led_A061_MI1_enable.Name = "led_A061_MI1_enable";
            this.led_A061_MI1_enable.Size = new System.Drawing.Size(175, 32);
            this.led_A061_MI1_enable.Text = "Power On";
            // 
            // num_A061_MI1_SetSpeed
            // 
            this.num_A061_MI1_SetSpeed.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("goA061_MI1SetSpeed")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.num_A061_MI1_SetSpeed.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.num_A061_MI1_SetSpeed.ForeColor = System.Drawing.SystemColors.ControlText;
            this.num_A061_MI1_SetSpeed.Location = new System.Drawing.Point(186, 174);
            this.num_A061_MI1_SetSpeed.Maximum = new decimal(new int[] {
                        120,
                        0,
                        0,
                        0});
            this.num_A061_MI1_SetSpeed.Minimum = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.num_A061_MI1_SetSpeed.Name = "num_A061_MI1_SetSpeed";
            this.num_A061_MI1_SetSpeed.Size = new System.Drawing.Size(105, 33);
            this.num_A061_MI1_SetSpeed.TextChanged += new System.EventHandler(this.num_A061_MI1_SetSpeed_TextChanged);
            // 
            // btn_A061_MI1_SetRun
            // 
            this.btn_A061_MI1_SetRun.AllowMultipleStates = true;
            this.btn_A061_MI1_SetRun.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_MI1_SetRun.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_MI1SetRun")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_MI1_SetRun.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_MI1_SetRun.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_MI1_SetRun.Location = new System.Drawing.Point(186, 216);
            this.btn_A061_MI1_SetRun.Name = "btn_A061_MI1_SetRun";
            this.btn_A061_MI1_SetRun.Size = new System.Drawing.Size(107, 61);
            stateObject10.Add("Text", "Start");
            stateObject10.Add("BackColor", System.Drawing.Color.White);
            stateObject11.Add("Text", "Stop");
            stateObject11.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_MI1_SetRun.States.Add(stateObject10);
            this.btn_A061_MI1_SetRun.States.Add(stateObject11);
            this.btn_A061_MI1_SetRun.Text = "Start/Stop";
            this.btn_A061_MI1_SetRun.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject12.Add("Text", "None");
            stateObject12.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_MI1_SetRun.UndefinedState = stateObject12;
            this.btn_A061_MI1_SetRun.Click += new System.EventHandler(this.btn_A061_MI1_SetRun_Click);
            // 
            // InlineMixerG1
            // 
            this.InlineMixerG1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.InlineMixerG1.AutoScroll = false;
            this.InlineMixerG1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.InlineMixerG1.Controls.Add(this.lab_info_M1_7);
            this.InlineMixerG1.Controls.Add(this.bar_MI1_SpeedM1);
            this.InlineMixerG1.Controls.Add(this.lab_info_M1_6);
            this.InlineMixerG1.Controls.Add(this.bar_MI1_TempM2);
            this.InlineMixerG1.Controls.Add(this.lab_info_M1_5);
            this.InlineMixerG1.Controls.Add(this.bar_MI1_TempM1);
            this.InlineMixerG1.Controls.Add(this.bar_MI1_torqueM2);
            this.InlineMixerG1.Controls.Add(this.led_MI1_IsReady);
            this.InlineMixerG1.Controls.Add(this.led_MI1_IsRun);
            this.InlineMixerG1.Controls.Add(this.bar_MI1_torqueM1);
            this.InlineMixerG1.Controls.Add(this.lab_info_M1_3);
            this.InlineMixerG1.Controls.Add(this.bar_MI1_temp);
            this.InlineMixerG1.Controls.Add(this.bar_MI1_pressure);
            this.InlineMixerG1.Controls.Add(this.lab_info_M1_2);
            this.InlineMixerG1.Controls.Add(this.lab_info_M1_1);
            this.InlineMixerG1.Controls.Add(this.lab_info_M1_4);
            this.InlineMixerG1.Dock = System.Windows.Forms.DockStyle.None;
            this.InlineMixerG1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.InlineMixerG1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.InlineMixerG1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.InlineMixerG1.Location = new System.Drawing.Point(3, 23);
            this.InlineMixerG1.Name = "InlineMixerG1";
            this.InlineMixerG1.Size = new System.Drawing.Size(313, 297);
            this.InlineMixerG1.Tag = null;
            this.InlineMixerG1.Title = "Current Staus";
            this.InlineMixerG1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Top;
            // 
            // lab_info_M1_7
            // 
            this.lab_info_M1_7.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_M1_7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_M1_7.Location = new System.Drawing.Point(13, 243);
            this.lab_info_M1_7.Multiline = true;
            this.lab_info_M1_7.Name = "lab_info_M1_7";
            this.lab_info_M1_7.Size = new System.Drawing.Size(177, 24);
            this.lab_info_M1_7.Title = "Speed[rpm]";
            // 
            // bar_MI1_SpeedM1
            // 
            this.bar_MI1_SpeedM1.BarColor = System.Drawing.Color.Gainsboro;
            this.bar_MI1_SpeedM1.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("giA061_MI1StatusSpeedM1")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.bar_MI1_SpeedM1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.bar_MI1_SpeedM1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bar_MI1_SpeedM1.Location = new System.Drawing.Point(196, 246);
            this.bar_MI1_SpeedM1.Maximum = new decimal(new int[] {
                        120,
                        0,
                        0,
                        0});
            this.bar_MI1_SpeedM1.Name = "bar_MI1_SpeedM1";
            this.bar_MI1_SpeedM1.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.bar_MI1_SpeedM1.Size = new System.Drawing.Size(109, 21);
            this.bar_MI1_SpeedM1.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.bar_MI1_SpeedM1.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // lab_info_M1_6
            // 
            this.lab_info_M1_6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_M1_6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_M1_6.Location = new System.Drawing.Point(13, 213);
            this.lab_info_M1_6.Multiline = true;
            this.lab_info_M1_6.Name = "lab_info_M1_6";
            this.lab_info_M1_6.Size = new System.Drawing.Size(177, 24);
            this.lab_info_M1_6.Title = "Motor2 Temperature[C]";
            // 
            // bar_MI1_TempM2
            // 
            this.bar_MI1_TempM2.BarColor = System.Drawing.Color.Maroon;
            this.bar_MI1_TempM2.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("giA061_MI1StatusTemperatureM2")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.bar_MI1_TempM2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.bar_MI1_TempM2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bar_MI1_TempM2.Location = new System.Drawing.Point(196, 216);
            this.bar_MI1_TempM2.Name = "bar_MI1_TempM2";
            this.bar_MI1_TempM2.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.bar_MI1_TempM2.Precision = 2;
            this.bar_MI1_TempM2.Size = new System.Drawing.Size(109, 21);
            this.bar_MI1_TempM2.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.bar_MI1_TempM2.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // lab_info_M1_5
            // 
            this.lab_info_M1_5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_M1_5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_M1_5.Location = new System.Drawing.Point(13, 183);
            this.lab_info_M1_5.Multiline = true;
            this.lab_info_M1_5.Name = "lab_info_M1_5";
            this.lab_info_M1_5.Size = new System.Drawing.Size(177, 24);
            this.lab_info_M1_5.Title = "Motor1 Temperature[C]";
            // 
            // bar_MI1_TempM1
            // 
            this.bar_MI1_TempM1.BarColor = System.Drawing.Color.Maroon;
            this.bar_MI1_TempM1.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("giA061_MI1StatusTemperatureM1")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.bar_MI1_TempM1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.bar_MI1_TempM1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bar_MI1_TempM1.Location = new System.Drawing.Point(196, 186);
            this.bar_MI1_TempM1.Name = "bar_MI1_TempM1";
            this.bar_MI1_TempM1.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.bar_MI1_TempM1.Precision = 2;
            this.bar_MI1_TempM1.Size = new System.Drawing.Size(109, 21);
            this.bar_MI1_TempM1.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.bar_MI1_TempM1.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // bar_MI1_torqueM2
            // 
            this.bar_MI1_torqueM2.BarColor = System.Drawing.Color.Gray;
            this.bar_MI1_torqueM2.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("giA061_MI1StatusTorqueM2")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.bar_MI1_torqueM2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.bar_MI1_torqueM2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bar_MI1_torqueM2.Location = new System.Drawing.Point(196, 96);
            this.bar_MI1_torqueM2.Maximum = new decimal(new int[] {
                        1888,
                        0,
                        0,
                        131072});
            this.bar_MI1_torqueM2.Name = "bar_MI1_torqueM2";
            this.bar_MI1_torqueM2.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.bar_MI1_torqueM2.Precision = 2;
            this.bar_MI1_torqueM2.Size = new System.Drawing.Size(109, 21);
            this.bar_MI1_torqueM2.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.bar_MI1_torqueM2.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // led_MI1_IsReady
            // 
            this.led_MI1_IsReady.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_MI1IsReady")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_MI1_IsReady.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led_MI1_IsReady.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_MI1_IsReady.Location = new System.Drawing.Point(13, 23);
            this.led_MI1_IsReady.Name = "led_MI1_IsReady";
            this.led_MI1_IsReady.Size = new System.Drawing.Size(140, 34);
            this.led_MI1_IsReady.Text = "Ready";
            // 
            // led_MI1_IsRun
            // 
            this.led_MI1_IsRun.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_MI1IsRun")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_MI1_IsRun.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led_MI1_IsRun.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_MI1_IsRun.Location = new System.Drawing.Point(153, 23);
            this.led_MI1_IsRun.Name = "led_MI1_IsRun";
            this.led_MI1_IsRun.Size = new System.Drawing.Size(152, 34);
            this.led_MI1_IsRun.Text = "Run";
            // 
            // bar_MI1_torqueM1
            // 
            this.bar_MI1_torqueM1.BarColor = System.Drawing.Color.Gray;
            this.bar_MI1_torqueM1.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("giA061_MI1StatusTorqueM1")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.bar_MI1_torqueM1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.bar_MI1_torqueM1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bar_MI1_torqueM1.Location = new System.Drawing.Point(196, 63);
            this.bar_MI1_torqueM1.Maximum = new decimal(new int[] {
                        1888,
                        0,
                        0,
                        131072});
            this.bar_MI1_torqueM1.Name = "bar_MI1_torqueM1";
            this.bar_MI1_torqueM1.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.bar_MI1_torqueM1.Precision = 2;
            this.bar_MI1_torqueM1.Size = new System.Drawing.Size(109, 21);
            this.bar_MI1_torqueM1.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.bar_MI1_torqueM1.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // lab_info_M1_3
            // 
            this.lab_info_M1_3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_M1_3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_M1_3.Location = new System.Drawing.Point(13, 153);
            this.lab_info_M1_3.Multiline = true;
            this.lab_info_M1_3.Name = "lab_info_M1_3";
            this.lab_info_M1_3.Size = new System.Drawing.Size(177, 24);
            this.lab_info_M1_3.Title = "Funnel Temperature[C]";
            // 
            // bar_MI1_temp
            // 
            this.bar_MI1_temp.BarColor = System.Drawing.Color.Maroon;
            this.bar_MI1_temp.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("giA061_MI1StatusTempFunnelOut")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.bar_MI1_temp.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.bar_MI1_temp.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bar_MI1_temp.Location = new System.Drawing.Point(196, 156);
            this.bar_MI1_temp.Maximum = new decimal(new int[] {
                        80,
                        0,
                        0,
                        0});
            this.bar_MI1_temp.Name = "bar_MI1_temp";
            this.bar_MI1_temp.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.bar_MI1_temp.Precision = 2;
            this.bar_MI1_temp.Size = new System.Drawing.Size(109, 21);
            this.bar_MI1_temp.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.bar_MI1_temp.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // bar_MI1_pressure
            // 
            this.bar_MI1_pressure.BarColor = System.Drawing.Color.SteelBlue;
            this.bar_MI1_pressure.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("giA061_MI1StatusPressureFunnel")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.bar_MI1_pressure.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.bar_MI1_pressure.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bar_MI1_pressure.Location = new System.Drawing.Point(196, 123);
            this.bar_MI1_pressure.Maximum = new decimal(new int[] {
                        11,
                        0,
                        0,
                        0});
            this.bar_MI1_pressure.Name = "bar_MI1_pressure";
            this.bar_MI1_pressure.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.bar_MI1_pressure.Precision = 2;
            this.bar_MI1_pressure.Size = new System.Drawing.Size(109, 21);
            this.bar_MI1_pressure.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.bar_MI1_pressure.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // lab_info_M1_2
            // 
            this.lab_info_M1_2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_M1_2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_M1_2.Location = new System.Drawing.Point(13, 93);
            this.lab_info_M1_2.Multiline = true;
            this.lab_info_M1_2.Name = "lab_info_M1_2";
            this.lab_info_M1_2.Size = new System.Drawing.Size(177, 24);
            this.lab_info_M1_2.Title = "TorqueM2[Nm]";
            // 
            // lab_info_M1_1
            // 
            this.lab_info_M1_1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_M1_1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_M1_1.Location = new System.Drawing.Point(13, 63);
            this.lab_info_M1_1.Multiline = true;
            this.lab_info_M1_1.Name = "lab_info_M1_1";
            this.lab_info_M1_1.Size = new System.Drawing.Size(177, 24);
            this.lab_info_M1_1.Title = "TorqueM1[Nm]";
            // 
            // lab_info_M1_4
            // 
            this.lab_info_M1_4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_M1_4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_M1_4.Location = new System.Drawing.Point(13, 123);
            this.lab_info_M1_4.Multiline = true;
            this.lab_info_M1_4.Name = "lab_info_M1_4";
            this.lab_info_M1_4.Size = new System.Drawing.Size(177, 24);
            this.lab_info_M1_4.Title = "Pressure[Bar]";
            // 
            // lab_A061_MI1_speed
            // 
            this.lab_A061_MI1_speed.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_A061_MI1_speed.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_A061_MI1_speed.Location = new System.Drawing.Point(128, 221);
            this.lab_A061_MI1_speed.Multiline = true;
            this.lab_A061_MI1_speed.Name = "lab_A061_MI1_speed";
            this.lab_A061_MI1_speed.Size = new System.Drawing.Size(108, 22);
            this.lab_A061_MI1_speed.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.lab_A061_MI1_speed.Title = "[rpm]";
            // 
            // Mixer
            // 
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.InlineMixerGroup1);
            this.Controls.Add(this.button8);
            this.Controls.Add(this.button7);
            this.Controls.Add(this.button6);
            this.Controls.Add(this.button5);
            this.Controls.Add(this.button4);
            this.Controls.Add(this.button3);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.button1);
            this.Text = "Digital Casting System";
            this.Controls.SetChildIndex(this.button1, 0);
            this.Controls.SetChildIndex(this.button2, 0);
            this.Controls.SetChildIndex(this.button3, 0);
            this.Controls.SetChildIndex(this.button4, 0);
            this.Controls.SetChildIndex(this.button5, 0);
            this.Controls.SetChildIndex(this.button6, 0);
            this.Controls.SetChildIndex(this.button7, 0);
            this.Controls.SetChildIndex(this.button8, 0);
            this.Controls.SetChildIndex(this.InlineMixerGroup1, 0);
            this.InlineMixerGroup1.ResumeLayout(false);
            this.InlineMixerG2.ResumeLayout(false);
            this.InlineMixerG1.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void button2_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Mixer));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button2_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button3_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(ConPump));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button3_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button4_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(DosPumpH));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button4_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button5_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(DosPumpL));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button5_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button6_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Sys));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button6_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button7_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Spare));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button7_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button8_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Spare2));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button8_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button1_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(MainScreen));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button1_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_MI1_Enable_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalInvert
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_MI1Enable"))).Invert();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_MI1_Enable_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_CC1_Reset_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalPulse
                ABB.Robotics.ScreenMaker.Base.IApplicationVariable time_0 = this.ScreenServices.ApplicationVariables["ResetTime"];
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_CC1Reset"))).Pulse(int.Parse(time_0.Value.ToString()));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_CC1_Reset_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button10_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalInvert
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_MI1SetCurvedSpeedMode"))).Invert();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button10_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_MI1_SetRun_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalInvert
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_MI1SetRun"))).Invert();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_MI1_SetRun_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void num_A061_MI1_SetSpeed_TextChanged(object sender, System.EventArgs e)
        {
            try
            {
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in num_A061_MI1_SetSpeed_TextChanged", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
    }
}
