//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace DCSControlPanel
{
    
    
    public class Spare2 : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.Button button1;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button2;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button3;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button4;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button5;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button6;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button7;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel9;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel10;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel11;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel6;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel7;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel8;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel5;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel3;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel4;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel1;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button8;
        
        public Spare2()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.button1 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button2 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button3 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button4 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button5 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button6 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button7 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button8 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.groupBox1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.tpsLabel9 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel10 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel11 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel6 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel7 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel8 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel5 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel3 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel4 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel2 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.groupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.Color.White;
            this.button1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button1.Location = new System.Drawing.Point(-1, 360);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(80, 30);
            this.button1.Text = "Main";
            this.button1.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // button2
            // 
            this.button2.BackColor = System.Drawing.Color.White;
            this.button2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button2.Location = new System.Drawing.Point(79, 360);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(80, 30);
            this.button2.Text = "Mixer";
            this.button2.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // button3
            // 
            this.button3.BackColor = System.Drawing.Color.White;
            this.button3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button3.Location = new System.Drawing.Point(159, 360);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(80, 30);
            this.button3.Text = "ConPump";
            this.button3.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button3.Click += new System.EventHandler(this.button3_Click);
            // 
            // button4
            // 
            this.button4.BackColor = System.Drawing.Color.White;
            this.button4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button4.Location = new System.Drawing.Point(239, 360);
            this.button4.Name = "button4";
            this.button4.Size = new System.Drawing.Size(80, 30);
            this.button4.Text = "DosPumpH";
            this.button4.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button4.Click += new System.EventHandler(this.button4_Click);
            // 
            // button5
            // 
            this.button5.BackColor = System.Drawing.Color.White;
            this.button5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button5.Location = new System.Drawing.Point(319, 360);
            this.button5.Name = "button5";
            this.button5.Size = new System.Drawing.Size(80, 30);
            this.button5.Text = "DosPumpL";
            this.button5.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button5.Click += new System.EventHandler(this.button5_Click);
            // 
            // button6
            // 
            this.button6.BackColor = System.Drawing.Color.White;
            this.button6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button6.Location = new System.Drawing.Point(399, 360);
            this.button6.Name = "button6";
            this.button6.Size = new System.Drawing.Size(80, 30);
            this.button6.Text = "Sys";
            this.button6.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button6.Click += new System.EventHandler(this.button6_Click);
            // 
            // button7
            // 
            this.button7.BackColor = System.Drawing.Color.White;
            this.button7.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button7.Location = new System.Drawing.Point(479, 360);
            this.button7.Name = "button7";
            this.button7.Size = new System.Drawing.Size(80, 30);
            this.button7.Text = "Robot";
            this.button7.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button7.Click += new System.EventHandler(this.button7_Click);
            // 
            // button8
            // 
            this.button8.BackColor = System.Drawing.Color.Silver;
            this.button8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button8.Location = new System.Drawing.Point(559, 360);
            this.button8.Name = "button8";
            this.button8.Size = new System.Drawing.Size(80, 30);
            this.button8.Text = "Info";
            this.button8.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button8.Click += new System.EventHandler(this.button8_Click);
            // 
            // groupBox1
            // 
            this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox1.AutoScroll = false;
            this.groupBox1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox1.Controls.Add(this.tpsLabel9);
            this.groupBox1.Controls.Add(this.tpsLabel10);
            this.groupBox1.Controls.Add(this.tpsLabel11);
            this.groupBox1.Controls.Add(this.tpsLabel6);
            this.groupBox1.Controls.Add(this.tpsLabel7);
            this.groupBox1.Controls.Add(this.tpsLabel8);
            this.groupBox1.Controls.Add(this.tpsLabel5);
            this.groupBox1.Controls.Add(this.tpsLabel3);
            this.groupBox1.Controls.Add(this.tpsLabel4);
            this.groupBox1.Controls.Add(this.tpsLabel2);
            this.groupBox1.Controls.Add(this.tpsLabel1);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox1.Location = new System.Drawing.Point(3, 34);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(633, 323);
            this.groupBox1.Tag = null;
            this.groupBox1.Title = "System infomation";
            this.groupBox1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // tpsLabel9
            // 
            this.tpsLabel9.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10;
            this.tpsLabel9.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel9.Location = new System.Drawing.Point(64, 278);
            this.tpsLabel9.Multiline = true;
            this.tpsLabel9.Name = "tpsLabel9";
            this.tpsLabel9.Size = new System.Drawing.Size(536, 24);
            this.tpsLabel9.Title = "Data: 2024.05.24. Wei-Ting Chen";
            // 
            // tpsLabel10
            // 
            this.tpsLabel10.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10;
            this.tpsLabel10.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel10.Location = new System.Drawing.Point(64, 254);
            this.tpsLabel10.Multiline = true;
            this.tpsLabel10.Name = "tpsLabel10";
            this.tpsLabel10.Size = new System.Drawing.Size(536, 28);
            this.tpsLabel10.Title = "Digital Casting System Controller 0.9.1";
            // 
            // tpsLabel11
            // 
            this.tpsLabel11.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel11.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel11.Location = new System.Drawing.Point(20, 229);
            this.tpsLabel11.Multiline = true;
            this.tpsLabel11.Name = "tpsLabel11";
            this.tpsLabel11.Size = new System.Drawing.Size(593, 28);
            this.tpsLabel11.Title = "Vesion";
            // 
            // tpsLabel6
            // 
            this.tpsLabel6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10;
            this.tpsLabel6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel6.Location = new System.Drawing.Point(64, 199);
            this.tpsLabel6.Multiline = true;
            this.tpsLabel6.Name = "tpsLabel6";
            this.tpsLabel6.Size = new System.Drawing.Size(536, 24);
            this.tpsLabel6.Title = "ViscoTec 3RD10-H; 1.15 ml/rev(Low)";
            // 
            // tpsLabel7
            // 
            this.tpsLabel7.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10;
            this.tpsLabel7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel7.Location = new System.Drawing.Point(64, 175);
            this.tpsLabel7.Multiline = true;
            this.tpsLabel7.Name = "tpsLabel7";
            this.tpsLabel7.Size = new System.Drawing.Size(536, 28);
            this.tpsLabel7.Title = "ViscoTec 2RD12-3D-H; 5.2 ml/rev (High)";
            // 
            // tpsLabel8
            // 
            this.tpsLabel8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel8.Location = new System.Drawing.Point(20, 150);
            this.tpsLabel8.Multiline = true;
            this.tpsLabel8.Name = "tpsLabel8";
            this.tpsLabel8.Size = new System.Drawing.Size(593, 28);
            this.tpsLabel8.Title = "Dosing Pump:";
            // 
            // tpsLabel5
            // 
            this.tpsLabel5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10;
            this.tpsLabel5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel5.Location = new System.Drawing.Point(64, 120);
            this.tpsLabel5.Multiline = true;
            this.tpsLabel5.Name = "tpsLabel5";
            this.tpsLabel5.Size = new System.Drawing.Size(536, 24);
            this.tpsLabel5.Title = "V:400; 50Hz; 1450rpm";
            // 
            // tpsLabel3
            // 
            this.tpsLabel3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10;
            this.tpsLabel3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel3.Location = new System.Drawing.Point(64, 96);
            this.tpsLabel3.Multiline = true;
            this.tpsLabel3.Name = "tpsLabel3";
            this.tpsLabel3.Size = new System.Drawing.Size(536, 28);
            this.tpsLabel3.Title = "PFT Swing L 1.5w; PFT R8-1.5; 75rpm";
            // 
            // tpsLabel4
            // 
            this.tpsLabel4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel4.Location = new System.Drawing.Point(20, 71);
            this.tpsLabel4.Multiline = true;
            this.tpsLabel4.Name = "tpsLabel4";
            this.tpsLabel4.Size = new System.Drawing.Size(593, 28);
            this.tpsLabel4.Title = "Concrete Pump:";
            // 
            // tpsLabel2
            // 
            this.tpsLabel2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10;
            this.tpsLabel2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel2.Location = new System.Drawing.Point(64, 46);
            this.tpsLabel2.Multiline = true;
            this.tpsLabel2.Name = "tpsLabel2";
            this.tpsLabel2.Size = new System.Drawing.Size(536, 28);
            this.tpsLabel2.Title = "Beckhoff AM8032-0E20-0000, Servomotor 2.95A, 2.37Nm, 6000U/min";
            // 
            // tpsLabel1
            // 
            this.tpsLabel1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel1.Location = new System.Drawing.Point(20, 21);
            this.tpsLabel1.Multiline = true;
            this.tpsLabel1.Name = "tpsLabel1";
            this.tpsLabel1.Size = new System.Drawing.Size(593, 28);
            this.tpsLabel1.Title = "Inline Mixer: ";
            // 
            // Spare2
            // 
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.button8);
            this.Controls.Add(this.button7);
            this.Controls.Add(this.button6);
            this.Controls.Add(this.button5);
            this.Controls.Add(this.button4);
            this.Controls.Add(this.button3);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.button1);
            this.Text = "Digital Casting System";
            this.Controls.SetChildIndex(this.button1, 0);
            this.Controls.SetChildIndex(this.button2, 0);
            this.Controls.SetChildIndex(this.button3, 0);
            this.Controls.SetChildIndex(this.button4, 0);
            this.Controls.SetChildIndex(this.button5, 0);
            this.Controls.SetChildIndex(this.button6, 0);
            this.Controls.SetChildIndex(this.button7, 0);
            this.Controls.SetChildIndex(this.button8, 0);
            this.Controls.SetChildIndex(this.groupBox1, 0);
            this.groupBox1.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void button2_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Mixer));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button2_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button3_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(ConPump));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button3_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button4_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(DosPumpH));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button4_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button5_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(DosPumpL));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button5_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button6_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Sys));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button6_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button7_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Spare));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button7_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button8_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Spare2));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button8_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button1_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(MainScreen));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button1_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
    }
}
