//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace DCSControlPanel
{
    
    
    public class DCSControlPanelBack : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.Button button1;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button2;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button3;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button4;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button5;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button6;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button7;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox InlineMixerGroup1;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor num_A061_MI1_SetSpeed;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox ControllerG1;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_MI1_IsReady;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_MI1_SetRun;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_A061_MI1_speed;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led1;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_CC1_Enable;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_A061_CC1_powerOn;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox ConcretePumpG1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_A061_CP1_flowrate;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led2;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led3;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor numEditor1;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_CC1_Reset;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_A061_CC1_reset;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_CP1_SetRun;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox ControllerG13;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_MI1_Enable;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_A061_MI1_enable;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox ControllerG12;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_A061_CC1_mode_manual;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_A061_CC1_mode_laptop;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_A061_CC1_mode_robot;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_go;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button8;
        
        public DCSControlPanelBack()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject1 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject2 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject3 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject4 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject5 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject6 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject7 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject8 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject9 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject10 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject11 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject12 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject13 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject14 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject15 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            this.button1 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button2 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button3 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button4 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button5 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button6 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button7 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button8 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.InlineMixerGroup1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.btn_A061_MI1_SetRun = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.lab_A061_MI1_speed = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.led1 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led_MI1_IsReady = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.num_A061_MI1_SetSpeed = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.ControllerG1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.btn_A061_go = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.ControllerG13 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.btn_A061_MI1_Enable = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.led_A061_MI1_enable = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.btn_A061_CC1_Enable = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.led_A061_CC1_powerOn = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.btn_A061_CC1_Reset = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.led_A061_CC1_reset = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.ControllerG12 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.led_A061_CC1_mode_manual = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led_A061_CC1_mode_laptop = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led_A061_CC1_mode_robot = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.ConcretePumpG1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.btn_A061_CP1_SetRun = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.lab_A061_CP1_flowrate = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.led2 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led3 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.numEditor1 = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.InlineMixerGroup1.SuspendLayout();
            this.ControllerG1.SuspendLayout();
            this.ControllerG13.SuspendLayout();
            this.ControllerG12.SuspendLayout();
            this.ConcretePumpG1.SuspendLayout();
            this.SuspendLayout();
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.Color.White;
            this.button1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button1.Location = new System.Drawing.Point(-1, 360);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(80, 30);
            this.button1.Text = "Main";
            this.button1.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // button2
            // 
            this.button2.BackColor = System.Drawing.Color.White;
            this.button2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button2.Location = new System.Drawing.Point(79, 360);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(80, 30);
            this.button2.Text = "Mixer";
            this.button2.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // button3
            // 
            this.button3.BackColor = System.Drawing.Color.White;
            this.button3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button3.Location = new System.Drawing.Point(159, 360);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(80, 30);
            this.button3.Text = "ConPump";
            this.button3.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button3.Click += new System.EventHandler(this.button3_Click);
            // 
            // button4
            // 
            this.button4.BackColor = System.Drawing.Color.White;
            this.button4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button4.Location = new System.Drawing.Point(239, 360);
            this.button4.Name = "button4";
            this.button4.Size = new System.Drawing.Size(80, 30);
            this.button4.Text = "DosPumpH";
            this.button4.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button4.Click += new System.EventHandler(this.button4_Click);
            // 
            // button5
            // 
            this.button5.BackColor = System.Drawing.Color.White;
            this.button5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button5.Location = new System.Drawing.Point(319, 360);
            this.button5.Name = "button5";
            this.button5.Size = new System.Drawing.Size(80, 30);
            this.button5.Text = "DosPumpL";
            this.button5.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button5.Click += new System.EventHandler(this.button5_Click);
            // 
            // button6
            // 
            this.button6.BackColor = System.Drawing.Color.White;
            this.button6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button6.Location = new System.Drawing.Point(399, 360);
            this.button6.Name = "button6";
            this.button6.Size = new System.Drawing.Size(80, 30);
            this.button6.Text = "Sys";
            this.button6.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button6.Click += new System.EventHandler(this.button6_Click);
            // 
            // button7
            // 
            this.button7.BackColor = System.Drawing.Color.White;
            this.button7.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button7.Location = new System.Drawing.Point(479, 360);
            this.button7.Name = "button7";
            this.button7.Size = new System.Drawing.Size(80, 30);
            this.button7.Text = "Spare";
            this.button7.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button7.Click += new System.EventHandler(this.button7_Click);
            // 
            // button8
            // 
            this.button8.BackColor = System.Drawing.Color.White;
            this.button8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button8.Location = new System.Drawing.Point(559, 360);
            this.button8.Name = "button8";
            this.button8.Size = new System.Drawing.Size(80, 30);
            this.button8.Text = "Spare";
            this.button8.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button8.Click += new System.EventHandler(this.button8_Click);
            // 
            // InlineMixerGroup1
            // 
            this.InlineMixerGroup1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.InlineMixerGroup1.AutoScroll = false;
            this.InlineMixerGroup1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.InlineMixerGroup1.Controls.Add(this.btn_A061_MI1_SetRun);
            this.InlineMixerGroup1.Controls.Add(this.lab_A061_MI1_speed);
            this.InlineMixerGroup1.Controls.Add(this.led1);
            this.InlineMixerGroup1.Controls.Add(this.led_MI1_IsReady);
            this.InlineMixerGroup1.Controls.Add(this.num_A061_MI1_SetSpeed);
            this.InlineMixerGroup1.Dock = System.Windows.Forms.DockStyle.None;
            this.InlineMixerGroup1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.InlineMixerGroup1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.InlineMixerGroup1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.InlineMixerGroup1.Location = new System.Drawing.Point(2, 23);
            this.InlineMixerGroup1.Name = "InlineMixerGroup1";
            this.InlineMixerGroup1.Size = new System.Drawing.Size(335, 93);
            this.InlineMixerGroup1.Tag = null;
            this.InlineMixerGroup1.Title = "Inline Mixer";
            this.InlineMixerGroup1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // btn_A061_MI1_SetRun
            // 
            this.btn_A061_MI1_SetRun.AllowMultipleStates = true;
            this.btn_A061_MI1_SetRun.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_MI1_SetRun.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_MI1SetRun")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_MI1_SetRun.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_MI1_SetRun.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_MI1_SetRun.Location = new System.Drawing.Point(220, 22);
            this.btn_A061_MI1_SetRun.Name = "btn_A061_MI1_SetRun";
            this.btn_A061_MI1_SetRun.Size = new System.Drawing.Size(112, 63);
            stateObject1.Add("Text", "Start");
            stateObject1.Add("BackColor", System.Drawing.Color.White);
            stateObject2.Add("Text", "Stop");
            stateObject2.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_MI1_SetRun.States.Add(stateObject1);
            this.btn_A061_MI1_SetRun.States.Add(stateObject2);
            this.btn_A061_MI1_SetRun.Text = "Start/Stop";
            this.btn_A061_MI1_SetRun.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject3.Add("Text", "None");
            stateObject3.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_MI1_SetRun.UndefinedState = stateObject3;
            this.btn_A061_MI1_SetRun.Click += new System.EventHandler(this.btn_A061_MI1_SetRun_Click);
            // 
            // lab_A061_MI1_speed
            // 
            this.lab_A061_MI1_speed.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_A061_MI1_speed.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_A061_MI1_speed.Location = new System.Drawing.Point(107, 22);
            this.lab_A061_MI1_speed.Multiline = true;
            this.lab_A061_MI1_speed.Name = "lab_A061_MI1_speed";
            this.lab_A061_MI1_speed.Size = new System.Drawing.Size(107, 26);
            this.lab_A061_MI1_speed.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.lab_A061_MI1_speed.Title = "[rpm]";
            // 
            // led1
            // 
            this.led1.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_MI1IsReady")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.led1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led1.Location = new System.Drawing.Point(8, 54);
            this.led1.Name = "led1";
            this.led1.Size = new System.Drawing.Size(93, 35);
            this.led1.Text = "Run";
            // 
            // led_MI1_IsReady
            // 
            this.led_MI1_IsReady.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_MI1IsReady")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_MI1_IsReady.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.led_MI1_IsReady.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_MI1_IsReady.Location = new System.Drawing.Point(8, 16);
            this.led_MI1_IsReady.Name = "led_MI1_IsReady";
            this.led_MI1_IsReady.Size = new System.Drawing.Size(93, 38);
            this.led_MI1_IsReady.Text = "Ready";
            // 
            // num_A061_MI1_SetSpeed
            // 
            this.num_A061_MI1_SetSpeed.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("goA061_MI1SetSpeed")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.num_A061_MI1_SetSpeed.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.num_A061_MI1_SetSpeed.ForeColor = System.Drawing.SystemColors.ControlText;
            this.num_A061_MI1_SetSpeed.Location = new System.Drawing.Point(107, 54);
            this.num_A061_MI1_SetSpeed.Maximum = new decimal(new int[] {
                        120,
                        0,
                        0,
                        0});
            this.num_A061_MI1_SetSpeed.Minimum = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.num_A061_MI1_SetSpeed.Name = "num_A061_MI1_SetSpeed";
            this.num_A061_MI1_SetSpeed.Size = new System.Drawing.Size(107, 31);
            // 
            // ControllerG1
            // 
            this.ControllerG1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.ControllerG1.AutoScroll = false;
            this.ControllerG1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.ControllerG1.Controls.Add(this.btn_A061_go);
            this.ControllerG1.Controls.Add(this.ControllerG13);
            this.ControllerG1.Controls.Add(this.ControllerG12);
            this.ControllerG1.Dock = System.Windows.Forms.DockStyle.None;
            this.ControllerG1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.ControllerG1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.ControllerG1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.ControllerG1.Location = new System.Drawing.Point(343, 23);
            this.ControllerG1.Name = "ControllerG1";
            this.ControllerG1.Size = new System.Drawing.Size(296, 331);
            this.ControllerG1.Tag = null;
            this.ControllerG1.Title = "Controller";
            this.ControllerG1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // btn_A061_go
            // 
            this.btn_A061_go.BackColor = System.Drawing.Color.White;
            this.btn_A061_go.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_go.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_go.Location = new System.Drawing.Point(125, 279);
            this.btn_A061_go.Name = "btn_A061_go";
            this.btn_A061_go.Size = new System.Drawing.Size(149, 35);
            this.btn_A061_go.Text = "--INFO>";
            this.btn_A061_go.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.btn_A061_go.Click += new System.EventHandler(this.btn_goInfo);
            // 
            // ControllerG13
            // 
            this.ControllerG13.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.ControllerG13.AutoScroll = false;
            this.ControllerG13.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.ControllerG13.Controls.Add(this.btn_A061_MI1_Enable);
            this.ControllerG13.Controls.Add(this.led_A061_MI1_enable);
            this.ControllerG13.Controls.Add(this.btn_A061_CC1_Enable);
            this.ControllerG13.Controls.Add(this.led_A061_CC1_powerOn);
            this.ControllerG13.Controls.Add(this.btn_A061_CC1_Reset);
            this.ControllerG13.Controls.Add(this.led_A061_CC1_reset);
            this.ControllerG13.Dock = System.Windows.Forms.DockStyle.None;
            this.ControllerG13.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.ControllerG13.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.ControllerG13.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.OnlyTopLine;
            this.ControllerG13.Location = new System.Drawing.Point(3, 78);
            this.ControllerG13.Name = "ControllerG13";
            this.ControllerG13.Size = new System.Drawing.Size(290, 145);
            this.ControllerG13.Tag = null;
            this.ControllerG13.Title = "Power";
            this.ControllerG13.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // btn_A061_MI1_Enable
            // 
            this.btn_A061_MI1_Enable.AllowMultipleStates = true;
            this.btn_A061_MI1_Enable.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_MI1_Enable.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_MI1Enable")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_MI1_Enable.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_MI1_Enable.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_MI1_Enable.Location = new System.Drawing.Point(167, 94);
            this.btn_A061_MI1_Enable.Name = "btn_A061_MI1_Enable";
            this.btn_A061_MI1_Enable.Size = new System.Drawing.Size(104, 32);
            stateObject4.Add("Text", "On");
            stateObject4.Add("BackColor", System.Drawing.Color.White);
            stateObject5.Add("Text", "Off");
            stateObject5.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_MI1_Enable.States.Add(stateObject4);
            this.btn_A061_MI1_Enable.States.Add(stateObject5);
            this.btn_A061_MI1_Enable.Text = "On/Off";
            this.btn_A061_MI1_Enable.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject6.Add("Text", "None");
            stateObject6.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_MI1_Enable.UndefinedState = stateObject6;
            // 
            // led_A061_MI1_enable
            // 
            this.led_A061_MI1_enable.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_CC1Reset")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_A061_MI1_enable.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.led_A061_MI1_enable.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_A061_MI1_enable.Location = new System.Drawing.Point(13, 94);
            this.led_A061_MI1_enable.Name = "led_A061_MI1_enable";
            this.led_A061_MI1_enable.Size = new System.Drawing.Size(148, 32);
            this.led_A061_MI1_enable.Text = "Inline Mixer";
            // 
            // btn_A061_CC1_Enable
            // 
            this.btn_A061_CC1_Enable.AllowMultipleStates = true;
            this.btn_A061_CC1_Enable.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_CC1_Enable.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_CC1Enable")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_CC1_Enable.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_CC1_Enable.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_CC1_Enable.Location = new System.Drawing.Point(167, 17);
            this.btn_A061_CC1_Enable.Name = "btn_A061_CC1_Enable";
            this.btn_A061_CC1_Enable.Size = new System.Drawing.Size(104, 32);
            stateObject7.Add("Text", "On");
            stateObject7.Add("BackColor", System.Drawing.Color.White);
            stateObject8.Add("Text", "Off");
            stateObject8.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CC1_Enable.States.Add(stateObject7);
            this.btn_A061_CC1_Enable.States.Add(stateObject8);
            this.btn_A061_CC1_Enable.Text = "On/Off";
            this.btn_A061_CC1_Enable.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject9.Add("Text", "None");
            stateObject9.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CC1_Enable.UndefinedState = stateObject9;
            this.btn_A061_CC1_Enable.Click += new System.EventHandler(this.btn_A061_CC1_Enable_Click);
            // 
            // led_A061_CC1_powerOn
            // 
            this.led_A061_CC1_powerOn.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_CC1_power_on")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_A061_CC1_powerOn.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.led_A061_CC1_powerOn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_A061_CC1_powerOn.Location = new System.Drawing.Point(13, 17);
            this.led_A061_CC1_powerOn.Name = "led_A061_CC1_powerOn";
            this.led_A061_CC1_powerOn.Size = new System.Drawing.Size(148, 32);
            this.led_A061_CC1_powerOn.Text = "Power";
            this.led_A061_CC1_powerOn.ValueChanged += new System.EventHandler(this.led_A061_CC1_powerOn_ValueChanged);
            // 
            // btn_A061_CC1_Reset
            // 
            this.btn_A061_CC1_Reset.AllowMultipleStates = true;
            this.btn_A061_CC1_Reset.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_CC1_Reset.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_CC1Reset")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_CC1_Reset.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_CC1_Reset.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_CC1_Reset.Location = new System.Drawing.Point(167, 56);
            this.btn_A061_CC1_Reset.Name = "btn_A061_CC1_Reset";
            this.btn_A061_CC1_Reset.Size = new System.Drawing.Size(104, 32);
            stateObject10.Add("Text", "On");
            stateObject10.Add("BackColor", System.Drawing.Color.White);
            stateObject11.Add("Text", "Off");
            stateObject11.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CC1_Reset.States.Add(stateObject10);
            this.btn_A061_CC1_Reset.States.Add(stateObject11);
            this.btn_A061_CC1_Reset.Text = "On/Off";
            this.btn_A061_CC1_Reset.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject12.Add("Text", "None");
            stateObject12.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CC1_Reset.UndefinedState = stateObject12;
            this.btn_A061_CC1_Reset.Click += new System.EventHandler(this.btn_A061_CC1_Reset_Click);
            // 
            // led_A061_CC1_reset
            // 
            this.led_A061_CC1_reset.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_CC1Reset")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_A061_CC1_reset.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.led_A061_CC1_reset.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_A061_CC1_reset.Location = new System.Drawing.Point(13, 56);
            this.led_A061_CC1_reset.Name = "led_A061_CC1_reset";
            this.led_A061_CC1_reset.Size = new System.Drawing.Size(148, 32);
            this.led_A061_CC1_reset.Text = "Reset";
            this.led_A061_CC1_reset.ValueChanged += new System.EventHandler(this.led_A061_CC1_reset_ValueChanged);
            // 
            // ControllerG12
            // 
            this.ControllerG12.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.ControllerG12.AutoScroll = false;
            this.ControllerG12.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.ControllerG12.Controls.Add(this.led_A061_CC1_mode_manual);
            this.ControllerG12.Controls.Add(this.led_A061_CC1_mode_laptop);
            this.ControllerG12.Controls.Add(this.led_A061_CC1_mode_robot);
            this.ControllerG12.Dock = System.Windows.Forms.DockStyle.None;
            this.ControllerG12.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.ControllerG12.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.ControllerG12.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.OnlyTopLine;
            this.ControllerG12.Location = new System.Drawing.Point(3, 22);
            this.ControllerG12.Name = "ControllerG12";
            this.ControllerG12.Size = new System.Drawing.Size(290, 51);
            this.ControllerG12.Tag = null;
            this.ControllerG12.Title = "Operation mode";
            this.ControllerG12.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // led_A061_CC1_mode_manual
            // 
            this.led_A061_CC1_mode_manual.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_CC1_mode_manual")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_A061_CC1_mode_manual.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.led_A061_CC1_mode_manual.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_A061_CC1_mode_manual.Location = new System.Drawing.Point(188, 18);
            this.led_A061_CC1_mode_manual.Name = "led_A061_CC1_mode_manual";
            this.led_A061_CC1_mode_manual.Size = new System.Drawing.Size(101, 32);
            this.led_A061_CC1_mode_manual.Text = "Manual";
            // 
            // led_A061_CC1_mode_laptop
            // 
            this.led_A061_CC1_mode_laptop.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_CC1_mode_laptop")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_A061_CC1_mode_laptop.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.led_A061_CC1_mode_laptop.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_A061_CC1_mode_laptop.Location = new System.Drawing.Point(86, 18);
            this.led_A061_CC1_mode_laptop.Name = "led_A061_CC1_mode_laptop";
            this.led_A061_CC1_mode_laptop.Size = new System.Drawing.Size(101, 32);
            this.led_A061_CC1_mode_laptop.Text = "Laptop";
            // 
            // led_A061_CC1_mode_robot
            // 
            this.led_A061_CC1_mode_robot.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_CC1_mode_robot")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_A061_CC1_mode_robot.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.led_A061_CC1_mode_robot.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_A061_CC1_mode_robot.Location = new System.Drawing.Point(3, 18);
            this.led_A061_CC1_mode_robot.Name = "led_A061_CC1_mode_robot";
            this.led_A061_CC1_mode_robot.Size = new System.Drawing.Size(82, 32);
            this.led_A061_CC1_mode_robot.Text = "Robot";
            // 
            // ConcretePumpG1
            // 
            this.ConcretePumpG1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.ConcretePumpG1.AutoScroll = false;
            this.ConcretePumpG1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.ConcretePumpG1.Controls.Add(this.btn_A061_CP1_SetRun);
            this.ConcretePumpG1.Controls.Add(this.lab_A061_CP1_flowrate);
            this.ConcretePumpG1.Controls.Add(this.led2);
            this.ConcretePumpG1.Controls.Add(this.led3);
            this.ConcretePumpG1.Controls.Add(this.numEditor1);
            this.ConcretePumpG1.Dock = System.Windows.Forms.DockStyle.None;
            this.ConcretePumpG1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.ConcretePumpG1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.ConcretePumpG1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.ConcretePumpG1.Location = new System.Drawing.Point(2, 118);
            this.ConcretePumpG1.Name = "ConcretePumpG1";
            this.ConcretePumpG1.Size = new System.Drawing.Size(335, 93);
            this.ConcretePumpG1.Tag = null;
            this.ConcretePumpG1.Title = "Concrete Pump";
            this.ConcretePumpG1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // btn_A061_CP1_SetRun
            // 
            this.btn_A061_CP1_SetRun.AllowMultipleStates = true;
            this.btn_A061_CP1_SetRun.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_CP1_SetRun.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_CP1_SetRun.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_CP1_SetRun.Location = new System.Drawing.Point(220, 22);
            this.btn_A061_CP1_SetRun.Name = "btn_A061_CP1_SetRun";
            this.btn_A061_CP1_SetRun.Size = new System.Drawing.Size(112, 63);
            stateObject13.Add("Text", "Start");
            stateObject13.Add("BackColor", System.Drawing.Color.White);
            stateObject14.Add("Text", "Stop");
            stateObject14.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CP1_SetRun.States.Add(stateObject13);
            this.btn_A061_CP1_SetRun.States.Add(stateObject14);
            this.btn_A061_CP1_SetRun.Text = "Start/Stop";
            this.btn_A061_CP1_SetRun.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject15.Add("Text", "None");
            stateObject15.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CP1_SetRun.UndefinedState = stateObject15;
            // 
            // lab_A061_CP1_flowrate
            // 
            this.lab_A061_CP1_flowrate.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_A061_CP1_flowrate.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_A061_CP1_flowrate.Location = new System.Drawing.Point(107, 22);
            this.lab_A061_CP1_flowrate.Multiline = true;
            this.lab_A061_CP1_flowrate.Name = "lab_A061_CP1_flowrate";
            this.lab_A061_CP1_flowrate.Size = new System.Drawing.Size(107, 26);
            this.lab_A061_CP1_flowrate.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.lab_A061_CP1_flowrate.Title = "[l/min]";
            // 
            // led2
            // 
            this.led2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.led2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led2.Location = new System.Drawing.Point(8, 54);
            this.led2.Name = "led2";
            this.led2.Size = new System.Drawing.Size(93, 35);
            this.led2.Text = "Run";
            // 
            // led3
            // 
            this.led3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.led3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led3.Location = new System.Drawing.Point(8, 16);
            this.led3.Name = "led3";
            this.led3.Size = new System.Drawing.Size(93, 38);
            this.led3.Text = "Ready";
            // 
            // numEditor1
            // 
            this.numEditor1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.numEditor1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.numEditor1.Location = new System.Drawing.Point(107, 54);
            this.numEditor1.Maximum = new decimal(new int[] {
                        24,
                        0,
                        0,
                        0});
            this.numEditor1.Minimum = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.numEditor1.Name = "numEditor1";
            this.numEditor1.Size = new System.Drawing.Size(107, 31);
            // 
            // DCSControlPanelBack
            // 
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.ConcretePumpG1);
            this.Controls.Add(this.InlineMixerGroup1);
            this.Controls.Add(this.button8);
            this.Controls.Add(this.button7);
            this.Controls.Add(this.button6);
            this.Controls.Add(this.button5);
            this.Controls.Add(this.button4);
            this.Controls.Add(this.button3);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.ControllerG1);
            this.Text = "Digital Casting System";
            this.Controls.SetChildIndex(this.ControllerG1, 0);
            this.Controls.SetChildIndex(this.button1, 0);
            this.Controls.SetChildIndex(this.button2, 0);
            this.Controls.SetChildIndex(this.button3, 0);
            this.Controls.SetChildIndex(this.button4, 0);
            this.Controls.SetChildIndex(this.button5, 0);
            this.Controls.SetChildIndex(this.button6, 0);
            this.Controls.SetChildIndex(this.button7, 0);
            this.Controls.SetChildIndex(this.button8, 0);
            this.Controls.SetChildIndex(this.InlineMixerGroup1, 0);
            this.Controls.SetChildIndex(this.ConcretePumpG1, 0);
            this.InlineMixerGroup1.ResumeLayout(false);
            this.ControllerG1.ResumeLayout(false);
            this.ControllerG13.ResumeLayout(false);
            this.ControllerG12.ResumeLayout(false);
            this.ConcretePumpG1.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void button2_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Mixer));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button2_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button3_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(ConPump));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button3_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button4_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(DosPumpH));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button4_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button5_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(DosPumpL));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button5_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button6_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Sys));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button6_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button7_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Spare));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button7_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button8_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Spare2));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button8_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_MI1_SetRun_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalInvert
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_MI1SetRun"))).Invert();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_MI1_SetRun_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_CC1_Enable_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalInvert
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_CC1Enable"))).Invert();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_CC1_Enable_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_CC1_Reset_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalPulse
                ABB.Robotics.ScreenMaker.Base.IApplicationVariable time_0 = this.ScreenServices.ApplicationVariables["ResetTime"];
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_CC1Reset"))).Pulse(int.Parse(time_0.Value.ToString()));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_CC1_Reset_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_goMain(object sender, System.EventArgs e)
        {
        }
        
        private void btn_goInfo(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(MainInfo));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_goInfo", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
    }
}
