//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace DCSControlPanel
{
    
    
    public class DCSControlPanel1 : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.Button button1;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button2;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button3;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button4;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button5;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button6;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button7;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led1;
        
        private ABB.Robotics.Tps.Windows.Forms.RadioButton radioButton1;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led2;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel1;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor numEditor1;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox3;
        
        private ABB.Robotics.Tps.Windows.Forms.RadioButton radioButton2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel2;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor numEditor2;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led3;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led4;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox4;
        
        private ABB.Robotics.Tps.Windows.Forms.RadioButton radioButton3;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel3;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor numEditor3;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led5;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led6;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox5;
        
        private ABB.Robotics.Tps.Windows.Forms.RadioButton radioButton4;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel4;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor numEditor4;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led7;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led8;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel12;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel10;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor numEditor7;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel11;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel8;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor numEditor6;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel9;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel7;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor numEditor5;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel6;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led10;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel5;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led9;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph barGraph1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel13;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor numEditor8;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel14;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel15;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor numEditor9;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel16;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel17;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor numEditor10;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel18;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button8;
        
        public DCSControlPanel1()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.button1 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button2 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button3 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button4 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button5 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button6 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button7 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button8 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.led1 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.radioButton1 = new ABB.Robotics.Tps.Windows.Forms.RadioButton();
            this.led2 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.groupBox2 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.tpsLabel1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.numEditor1 = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.groupBox3 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.radioButton2 = new ABB.Robotics.Tps.Windows.Forms.RadioButton();
            this.tpsLabel2 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.numEditor2 = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.led3 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led4 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.groupBox4 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.radioButton3 = new ABB.Robotics.Tps.Windows.Forms.RadioButton();
            this.tpsLabel3 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.numEditor3 = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.led5 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led6 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.groupBox5 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.radioButton4 = new ABB.Robotics.Tps.Windows.Forms.RadioButton();
            this.tpsLabel4 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.numEditor4 = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.led7 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led8 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.tpsLabel12 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.groupBox1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.barGraph1 = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.tpsLabel13 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.numEditor8 = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.tpsLabel14 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel15 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.numEditor9 = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.tpsLabel16 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel17 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.numEditor10 = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.tpsLabel18 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel10 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.numEditor7 = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.tpsLabel11 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel8 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.numEditor6 = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.tpsLabel9 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel7 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.numEditor5 = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.tpsLabel6 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.led10 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.tpsLabel5 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.led9 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.groupBox2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.Color.White;
            this.button1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button1.Location = new System.Drawing.Point(-1, 360);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(80, 30);
            this.button1.Text = "Main";
            this.button1.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // button2
            // 
            this.button2.BackColor = System.Drawing.Color.White;
            this.button2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button2.Location = new System.Drawing.Point(79, 360);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(80, 30);
            this.button2.Text = "Mixer";
            this.button2.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // button3
            // 
            this.button3.BackColor = System.Drawing.Color.White;
            this.button3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button3.Location = new System.Drawing.Point(159, 360);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(80, 30);
            this.button3.Text = "ConPump";
            this.button3.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            // 
            // button4
            // 
            this.button4.BackColor = System.Drawing.Color.White;
            this.button4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button4.Location = new System.Drawing.Point(239, 360);
            this.button4.Name = "button4";
            this.button4.Size = new System.Drawing.Size(80, 30);
            this.button4.Text = "DosPumpH";
            this.button4.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            // 
            // button5
            // 
            this.button5.BackColor = System.Drawing.Color.White;
            this.button5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button5.Location = new System.Drawing.Point(319, 360);
            this.button5.Name = "button5";
            this.button5.Size = new System.Drawing.Size(80, 30);
            this.button5.Text = "DosPumpL";
            this.button5.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            // 
            // button6
            // 
            this.button6.BackColor = System.Drawing.Color.White;
            this.button6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button6.Location = new System.Drawing.Point(399, 360);
            this.button6.Name = "button6";
            this.button6.Size = new System.Drawing.Size(80, 30);
            this.button6.Text = "Sys";
            this.button6.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            // 
            // button7
            // 
            this.button7.BackColor = System.Drawing.Color.White;
            this.button7.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button7.Location = new System.Drawing.Point(479, 360);
            this.button7.Name = "button7";
            this.button7.Size = new System.Drawing.Size(80, 30);
            this.button7.Text = "Spare";
            this.button7.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            // 
            // button8
            // 
            this.button8.BackColor = System.Drawing.Color.White;
            this.button8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button8.Location = new System.Drawing.Point(559, 360);
            this.button8.Name = "button8";
            this.button8.Size = new System.Drawing.Size(80, 30);
            this.button8.Text = "Spare";
            this.button8.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            // 
            // led1
            // 
            this.led1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led1.Location = new System.Drawing.Point(3, 25);
            this.led1.Name = "led1";
            this.led1.Size = new System.Drawing.Size(35, 35);
            this.led1.Text = "";
            // 
            // radioButton1
            // 
            this.radioButton1.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.radioButton1.Checked = true;
            this.radioButton1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font11b;
            this.radioButton1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.radioButton1.Location = new System.Drawing.Point(226, 12);
            this.radioButton1.Name = "radioButton1";
            this.radioButton1.Size = new System.Drawing.Size(112, 62);
            this.radioButton1.Text = "ON/OFF";
            // 
            // led2
            // 
            this.led2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led2.Location = new System.Drawing.Point(44, 25);
            this.led2.Name = "led2";
            this.led2.Size = new System.Drawing.Size(35, 35);
            this.led2.Text = "";
            // 
            // groupBox2
            // 
            this.groupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox2.AutoScroll = false;
            this.groupBox2.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox2.Controls.Add(this.radioButton1);
            this.groupBox2.Controls.Add(this.tpsLabel1);
            this.groupBox2.Controls.Add(this.numEditor1);
            this.groupBox2.Controls.Add(this.led1);
            this.groupBox2.Controls.Add(this.led2);
            this.groupBox2.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox2.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox2.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox2.Location = new System.Drawing.Point(0, 31);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(342, 77);
            this.groupBox2.Tag = null;
            this.groupBox2.Title = "Mixer";
            this.groupBox2.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // tpsLabel1
            // 
            this.tpsLabel1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel1.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.tpsLabel1.Location = new System.Drawing.Point(172, 30);
            this.tpsLabel1.Multiline = true;
            this.tpsLabel1.Name = "tpsLabel1";
            this.tpsLabel1.Size = new System.Drawing.Size(48, 27);
            this.tpsLabel1.Title = "rpm";
            // 
            // numEditor1
            // 
            this.numEditor1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font11b;
            this.numEditor1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.numEditor1.Location = new System.Drawing.Point(95, 30);
            this.numEditor1.Maximum = new decimal(new int[] {
                        120,
                        0,
                        0,
                        0});
            this.numEditor1.Minimum = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.numEditor1.Name = "numEditor1";
            this.numEditor1.Size = new System.Drawing.Size(70, 25);
            // 
            // groupBox3
            // 
            this.groupBox3.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox3.AutoScroll = false;
            this.groupBox3.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox3.Controls.Add(this.radioButton2);
            this.groupBox3.Controls.Add(this.tpsLabel2);
            this.groupBox3.Controls.Add(this.numEditor2);
            this.groupBox3.Controls.Add(this.led3);
            this.groupBox3.Controls.Add(this.led4);
            this.groupBox3.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.groupBox3.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox3.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox3.Location = new System.Drawing.Point(0, 111);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(342, 77);
            this.groupBox3.Tag = null;
            this.groupBox3.Title = "C Pump";
            this.groupBox3.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // radioButton2
            // 
            this.radioButton2.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.radioButton2.Checked = true;
            this.radioButton2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font11b;
            this.radioButton2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.radioButton2.Location = new System.Drawing.Point(226, 12);
            this.radioButton2.Name = "radioButton2";
            this.radioButton2.Size = new System.Drawing.Size(112, 62);
            this.radioButton2.Text = "ON/OFF";
            // 
            // tpsLabel2
            // 
            this.tpsLabel2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel2.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.tpsLabel2.Location = new System.Drawing.Point(172, 30);
            this.tpsLabel2.Multiline = true;
            this.tpsLabel2.Name = "tpsLabel2";
            this.tpsLabel2.Size = new System.Drawing.Size(48, 27);
            this.tpsLabel2.Title = "l/min";
            // 
            // numEditor2
            // 
            this.numEditor2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font11b;
            this.numEditor2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.numEditor2.Location = new System.Drawing.Point(95, 30);
            this.numEditor2.Maximum = new decimal(new int[] {
                        24,
                        0,
                        0,
                        0});
            this.numEditor2.Minimum = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.numEditor2.Name = "numEditor2";
            this.numEditor2.Size = new System.Drawing.Size(70, 25);
            // 
            // led3
            // 
            this.led3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led3.Location = new System.Drawing.Point(3, 25);
            this.led3.Name = "led3";
            this.led3.Size = new System.Drawing.Size(35, 35);
            this.led3.Text = "";
            // 
            // led4
            // 
            this.led4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led4.Location = new System.Drawing.Point(44, 25);
            this.led4.Name = "led4";
            this.led4.Size = new System.Drawing.Size(35, 35);
            this.led4.Text = "";
            // 
            // groupBox4
            // 
            this.groupBox4.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox4.AutoScroll = false;
            this.groupBox4.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox4.Controls.Add(this.radioButton3);
            this.groupBox4.Controls.Add(this.tpsLabel3);
            this.groupBox4.Controls.Add(this.numEditor3);
            this.groupBox4.Controls.Add(this.led5);
            this.groupBox4.Controls.Add(this.led6);
            this.groupBox4.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.groupBox4.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox4.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox4.Location = new System.Drawing.Point(0, 191);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(342, 77);
            this.groupBox4.Tag = null;
            this.groupBox4.Title = "D Pump H";
            this.groupBox4.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // radioButton3
            // 
            this.radioButton3.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.radioButton3.Checked = true;
            this.radioButton3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font11b;
            this.radioButton3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.radioButton3.Location = new System.Drawing.Point(226, 12);
            this.radioButton3.Name = "radioButton3";
            this.radioButton3.Size = new System.Drawing.Size(112, 62);
            this.radioButton3.Text = "ON/OFF";
            // 
            // tpsLabel3
            // 
            this.tpsLabel3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel3.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.tpsLabel3.Location = new System.Drawing.Point(172, 30);
            this.tpsLabel3.Multiline = true;
            this.tpsLabel3.Name = "tpsLabel3";
            this.tpsLabel3.Size = new System.Drawing.Size(67, 27);
            this.tpsLabel3.Title = "ml/min";
            // 
            // numEditor3
            // 
            this.numEditor3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font11b;
            this.numEditor3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.numEditor3.Location = new System.Drawing.Point(95, 30);
            this.numEditor3.Maximum = new decimal(new int[] {
                        400,
                        0,
                        0,
                        0});
            this.numEditor3.Minimum = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.numEditor3.Name = "numEditor3";
            this.numEditor3.Size = new System.Drawing.Size(70, 25);
            // 
            // led5
            // 
            this.led5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led5.Location = new System.Drawing.Point(3, 25);
            this.led5.Name = "led5";
            this.led5.Size = new System.Drawing.Size(35, 35);
            this.led5.Text = "";
            // 
            // led6
            // 
            this.led6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led6.Location = new System.Drawing.Point(44, 25);
            this.led6.Name = "led6";
            this.led6.Size = new System.Drawing.Size(35, 35);
            this.led6.Text = "";
            // 
            // groupBox5
            // 
            this.groupBox5.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox5.AutoScroll = false;
            this.groupBox5.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox5.Controls.Add(this.radioButton4);
            this.groupBox5.Controls.Add(this.tpsLabel4);
            this.groupBox5.Controls.Add(this.numEditor4);
            this.groupBox5.Controls.Add(this.led7);
            this.groupBox5.Controls.Add(this.led8);
            this.groupBox5.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox5.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox5.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox5.Location = new System.Drawing.Point(0, 271);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(342, 77);
            this.groupBox5.Tag = null;
            this.groupBox5.Title = "D Pump L";
            this.groupBox5.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // radioButton4
            // 
            this.radioButton4.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.radioButton4.Checked = true;
            this.radioButton4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font11b;
            this.radioButton4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.radioButton4.Location = new System.Drawing.Point(226, 12);
            this.radioButton4.Name = "radioButton4";
            this.radioButton4.Size = new System.Drawing.Size(112, 62);
            this.radioButton4.Text = "ON/OFF";
            // 
            // tpsLabel4
            // 
            this.tpsLabel4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel4.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.tpsLabel4.Location = new System.Drawing.Point(172, 30);
            this.tpsLabel4.Multiline = true;
            this.tpsLabel4.Name = "tpsLabel4";
            this.tpsLabel4.Size = new System.Drawing.Size(67, 27);
            this.tpsLabel4.Title = "ml/min";
            // 
            // numEditor4
            // 
            this.numEditor4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font11b;
            this.numEditor4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.numEditor4.Location = new System.Drawing.Point(95, 30);
            this.numEditor4.Maximum = new decimal(new int[] {
                        138,
                        0,
                        0,
                        0});
            this.numEditor4.Minimum = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.numEditor4.Name = "numEditor4";
            this.numEditor4.Size = new System.Drawing.Size(70, 25);
            // 
            // led7
            // 
            this.led7.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led7.Location = new System.Drawing.Point(3, 25);
            this.led7.Name = "led7";
            this.led7.Size = new System.Drawing.Size(35, 35);
            this.led7.Text = "";
            // 
            // led8
            // 
            this.led8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led8.Location = new System.Drawing.Point(44, 25);
            this.led8.Name = "led8";
            this.led8.Size = new System.Drawing.Size(35, 35);
            this.led8.Text = "";
            // 
            // tpsLabel12
            // 
            this.tpsLabel12.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel12.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel12.Location = new System.Drawing.Point(14, 22);
            this.tpsLabel12.Multiline = true;
            this.tpsLabel12.Name = "tpsLabel12";
            this.tpsLabel12.Size = new System.Drawing.Size(94, 35);
            this.tpsLabel12.Title = "CC Power";
            // 
            // groupBox1
            // 
            this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox1.AutoScroll = false;
            this.groupBox1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox1.Controls.Add(this.barGraph1);
            this.groupBox1.Controls.Add(this.tpsLabel13);
            this.groupBox1.Controls.Add(this.numEditor8);
            this.groupBox1.Controls.Add(this.tpsLabel14);
            this.groupBox1.Controls.Add(this.tpsLabel15);
            this.groupBox1.Controls.Add(this.numEditor9);
            this.groupBox1.Controls.Add(this.tpsLabel16);
            this.groupBox1.Controls.Add(this.tpsLabel17);
            this.groupBox1.Controls.Add(this.numEditor10);
            this.groupBox1.Controls.Add(this.tpsLabel18);
            this.groupBox1.Controls.Add(this.tpsLabel10);
            this.groupBox1.Controls.Add(this.numEditor7);
            this.groupBox1.Controls.Add(this.tpsLabel11);
            this.groupBox1.Controls.Add(this.tpsLabel8);
            this.groupBox1.Controls.Add(this.numEditor6);
            this.groupBox1.Controls.Add(this.tpsLabel9);
            this.groupBox1.Controls.Add(this.tpsLabel7);
            this.groupBox1.Controls.Add(this.numEditor5);
            this.groupBox1.Controls.Add(this.tpsLabel6);
            this.groupBox1.Controls.Add(this.led10);
            this.groupBox1.Controls.Add(this.tpsLabel5);
            this.groupBox1.Controls.Add(this.led9);
            this.groupBox1.Controls.Add(this.tpsLabel12);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox1.Location = new System.Drawing.Point(348, 31);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(291, 317);
            this.groupBox1.Tag = null;
            this.groupBox1.Title = "Info";
            this.groupBox1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // barGraph1
            // 
            this.barGraph1.BarColor = System.Drawing.Color.DarkRed;
            this.barGraph1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.barGraph1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.barGraph1.Location = new System.Drawing.Point(122, 115);
            this.barGraph1.Name = "barGraph1";
            this.barGraph1.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.barGraph1.Size = new System.Drawing.Size(104, 16);
            this.barGraph1.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // tpsLabel13
            // 
            this.tpsLabel13.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.tpsLabel13.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.tpsLabel13.Location = new System.Drawing.Point(184, 278);
            this.tpsLabel13.Multiline = true;
            this.tpsLabel13.Name = "tpsLabel13";
            this.tpsLabel13.Size = new System.Drawing.Size(53, 25);
            this.tpsLabel13.Title = "bar";
            // 
            // numEditor8
            // 
            this.numEditor8.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.numEditor8.Enabled = false;
            this.numEditor8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.numEditor8.ForeColor = System.Drawing.SystemColors.Highlight;
            this.numEditor8.Location = new System.Drawing.Point(116, 281);
            this.numEditor8.Name = "numEditor8";
            this.numEditor8.Size = new System.Drawing.Size(74, 22);
            // 
            // tpsLabel14
            // 
            this.tpsLabel14.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel14.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel14.Location = new System.Drawing.Point(16, 278);
            this.tpsLabel14.Multiline = true;
            this.tpsLabel14.Name = "tpsLabel14";
            this.tpsLabel14.Size = new System.Drawing.Size(115, 25);
            this.tpsLabel14.Title = "C Pump Presu.";
            // 
            // tpsLabel15
            // 
            this.tpsLabel15.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.tpsLabel15.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.tpsLabel15.Location = new System.Drawing.Point(184, 252);
            this.tpsLabel15.Multiline = true;
            this.tpsLabel15.Name = "tpsLabel15";
            this.tpsLabel15.Size = new System.Drawing.Size(53, 25);
            this.tpsLabel15.Title = "C";
            // 
            // numEditor9
            // 
            this.numEditor9.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.numEditor9.Enabled = false;
            this.numEditor9.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.numEditor9.ForeColor = System.Drawing.SystemColors.Highlight;
            this.numEditor9.Location = new System.Drawing.Point(116, 255);
            this.numEditor9.Name = "numEditor9";
            this.numEditor9.Size = new System.Drawing.Size(74, 22);
            // 
            // tpsLabel16
            // 
            this.tpsLabel16.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel16.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel16.Location = new System.Drawing.Point(16, 252);
            this.tpsLabel16.Multiline = true;
            this.tpsLabel16.Name = "tpsLabel16";
            this.tpsLabel16.Size = new System.Drawing.Size(115, 25);
            this.tpsLabel16.Title = "C Pump Tem.";
            // 
            // tpsLabel17
            // 
            this.tpsLabel17.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.tpsLabel17.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.tpsLabel17.Location = new System.Drawing.Point(184, 226);
            this.tpsLabel17.Multiline = true;
            this.tpsLabel17.Name = "tpsLabel17";
            this.tpsLabel17.Size = new System.Drawing.Size(53, 25);
            this.tpsLabel17.Title = "Nm";
            // 
            // numEditor10
            // 
            this.numEditor10.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.numEditor10.Enabled = false;
            this.numEditor10.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.numEditor10.ForeColor = System.Drawing.SystemColors.Highlight;
            this.numEditor10.Location = new System.Drawing.Point(116, 229);
            this.numEditor10.Name = "numEditor10";
            this.numEditor10.Size = new System.Drawing.Size(74, 22);
            // 
            // tpsLabel18
            // 
            this.tpsLabel18.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel18.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel18.Location = new System.Drawing.Point(16, 226);
            this.tpsLabel18.Multiline = true;
            this.tpsLabel18.Name = "tpsLabel18";
            this.tpsLabel18.Size = new System.Drawing.Size(115, 25);
            this.tpsLabel18.Title = "Concrete Tem.";
            // 
            // tpsLabel10
            // 
            this.tpsLabel10.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.tpsLabel10.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.tpsLabel10.Location = new System.Drawing.Point(184, 186);
            this.tpsLabel10.Multiline = true;
            this.tpsLabel10.Name = "tpsLabel10";
            this.tpsLabel10.Size = new System.Drawing.Size(53, 25);
            this.tpsLabel10.Title = "bar";
            // 
            // numEditor7
            // 
            this.numEditor7.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.numEditor7.Enabled = false;
            this.numEditor7.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.numEditor7.ForeColor = System.Drawing.SystemColors.Highlight;
            this.numEditor7.Location = new System.Drawing.Point(116, 189);
            this.numEditor7.Name = "numEditor7";
            this.numEditor7.Size = new System.Drawing.Size(74, 22);
            // 
            // tpsLabel11
            // 
            this.tpsLabel11.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel11.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel11.Location = new System.Drawing.Point(16, 186);
            this.tpsLabel11.Multiline = true;
            this.tpsLabel11.Name = "tpsLabel11";
            this.tpsLabel11.Size = new System.Drawing.Size(94, 25);
            this.tpsLabel11.Title = "Mixer Presu.";
            // 
            // tpsLabel8
            // 
            this.tpsLabel8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.tpsLabel8.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.tpsLabel8.Location = new System.Drawing.Point(184, 160);
            this.tpsLabel8.Multiline = true;
            this.tpsLabel8.Name = "tpsLabel8";
            this.tpsLabel8.Size = new System.Drawing.Size(53, 25);
            this.tpsLabel8.Title = "C";
            // 
            // numEditor6
            // 
            this.numEditor6.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.numEditor6.Enabled = false;
            this.numEditor6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.numEditor6.ForeColor = System.Drawing.SystemColors.Highlight;
            this.numEditor6.Location = new System.Drawing.Point(116, 163);
            this.numEditor6.Name = "numEditor6";
            this.numEditor6.Size = new System.Drawing.Size(74, 22);
            // 
            // tpsLabel9
            // 
            this.tpsLabel9.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel9.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel9.Location = new System.Drawing.Point(16, 160);
            this.tpsLabel9.Multiline = true;
            this.tpsLabel9.Name = "tpsLabel9";
            this.tpsLabel9.Size = new System.Drawing.Size(94, 25);
            this.tpsLabel9.Title = "Mixer Tem.";
            // 
            // tpsLabel7
            // 
            this.tpsLabel7.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.tpsLabel7.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.tpsLabel7.Location = new System.Drawing.Point(184, 134);
            this.tpsLabel7.Multiline = true;
            this.tpsLabel7.Name = "tpsLabel7";
            this.tpsLabel7.Size = new System.Drawing.Size(53, 25);
            this.tpsLabel7.Title = "Nm";
            // 
            // numEditor5
            // 
            this.numEditor5.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.numEditor5.Enabled = false;
            this.numEditor5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.numEditor5.ForeColor = System.Drawing.SystemColors.Highlight;
            this.numEditor5.Location = new System.Drawing.Point(116, 137);
            this.numEditor5.Name = "numEditor5";
            this.numEditor5.Size = new System.Drawing.Size(74, 22);
            // 
            // tpsLabel6
            // 
            this.tpsLabel6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel6.Location = new System.Drawing.Point(16, 134);
            this.tpsLabel6.Multiline = true;
            this.tpsLabel6.Name = "tpsLabel6";
            this.tpsLabel6.Size = new System.Drawing.Size(94, 25);
            this.tpsLabel6.Title = "Mixer Torq.";
            // 
            // led10
            // 
            this.led10.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led10.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led10.Location = new System.Drawing.Point(96, 52);
            this.led10.Name = "led10";
            this.led10.Size = new System.Drawing.Size(35, 35);
            this.led10.Text = "";
            // 
            // tpsLabel5
            // 
            this.tpsLabel5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel5.Location = new System.Drawing.Point(14, 52);
            this.tpsLabel5.Multiline = true;
            this.tpsLabel5.Name = "tpsLabel5";
            this.tpsLabel5.Size = new System.Drawing.Size(94, 35);
            this.tpsLabel5.Title = "Connection";
            // 
            // led9
            // 
            this.led9.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led9.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led9.Location = new System.Drawing.Point(96, 22);
            this.led9.Name = "led9";
            this.led9.Size = new System.Drawing.Size(35, 35);
            this.led9.Text = "";
            // 
            // DCSControlPanel1
            // 
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.groupBox5);
            this.Controls.Add(this.groupBox4);
            this.Controls.Add(this.groupBox3);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.button8);
            this.Controls.Add(this.button7);
            this.Controls.Add(this.button6);
            this.Controls.Add(this.button5);
            this.Controls.Add(this.button4);
            this.Controls.Add(this.button3);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.groupBox1);
            this.Text = "Digital Casting System";
            this.Controls.SetChildIndex(this.groupBox1, 0);
            this.Controls.SetChildIndex(this.button1, 0);
            this.Controls.SetChildIndex(this.button2, 0);
            this.Controls.SetChildIndex(this.button3, 0);
            this.Controls.SetChildIndex(this.button4, 0);
            this.Controls.SetChildIndex(this.button5, 0);
            this.Controls.SetChildIndex(this.button6, 0);
            this.Controls.SetChildIndex(this.button7, 0);
            this.Controls.SetChildIndex(this.button8, 0);
            this.Controls.SetChildIndex(this.groupBox2, 0);
            this.Controls.SetChildIndex(this.groupBox3, 0);
            this.Controls.SetChildIndex(this.groupBox4, 0);
            this.Controls.SetChildIndex(this.groupBox5, 0);
            this.groupBox2.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.groupBox4.ResumeLayout(false);
            this.groupBox5.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void button2_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Mixer));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button2_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button1_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(MainScreen));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button1_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
    }
}
