//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace DCSControlPanel
{
    
    
    public class DosPumpL : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.Button button1;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button2;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button3;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button4;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button5;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button6;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button7;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox DosingPump2G1;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox InlineMixerG1;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_SP1_IsReady;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_SP1_IsRun;
        
        private ABB.Robotics.Tps.Windows.Forms.TabControl tab_CP1_1;
        
        private ABB.Robotics.Tps.Windows.Forms.TabPage tabPage1;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_SP1_SetRun;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor num_A061_SP1_SetSpeed;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_A061_SP1_PowerOn;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_M1_8;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_SP1_PowerOn;
        
        private ABB.Robotics.Tps.Windows.Forms.TabPage tabPage2;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor numEditor3;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel3;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_A061_SP1_FLushOn;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_SP1_FlushOn;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor num_A061_SP1_DosingFactor;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel2;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor num_A061_SP1_SetCheckflow;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel1;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_A061_SP1_CheckOn;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_SP1_CheckOn;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_SP1_Error;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph bar_SP1_Curr_Flowrate;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph bar_SP1_Motor_Speed;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel5;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel4;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_CP1_3;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_CP1_2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_info_CP1_1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel bar_AP1_Max_Flowrate;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button8;
        
        public DosPumpL()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject1 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject2 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject3 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject4 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject5 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject6 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject7 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject8 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject9 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject10 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject11 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject12 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            this.button1 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button2 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button3 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button4 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button5 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button6 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button7 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button8 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.DosingPump2G1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.InlineMixerG1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.bar_AP1_Max_Flowrate = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.led_SP1_Error = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.bar_SP1_Curr_Flowrate = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.bar_SP1_Motor_Speed = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.tpsLabel5 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel4 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.lab_info_CP1_3 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.lab_info_CP1_2 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.lab_info_CP1_1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.led_SP1_IsReady = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led_SP1_IsRun = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.tab_CP1_1 = new ABB.Robotics.Tps.Windows.Forms.TabControl();
            this.tabPage1 = new ABB.Robotics.Tps.Windows.Forms.TabPage();
            this.btn_A061_SP1_SetRun = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.num_A061_SP1_SetSpeed = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.led_A061_SP1_PowerOn = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.lab_info_M1_8 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.btn_A061_SP1_PowerOn = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.tabPage2 = new ABB.Robotics.Tps.Windows.Forms.TabPage();
            this.numEditor3 = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.tpsLabel3 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.led_A061_SP1_FLushOn = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.btn_A061_SP1_FlushOn = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.num_A061_SP1_DosingFactor = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.tpsLabel2 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.num_A061_SP1_SetCheckflow = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.tpsLabel1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.led_A061_SP1_CheckOn = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.btn_A061_SP1_CheckOn = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.DosingPump2G1.SuspendLayout();
            this.InlineMixerG1.SuspendLayout();
            this.tab_CP1_1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.SuspendLayout();
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.Color.White;
            this.button1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button1.Location = new System.Drawing.Point(-1, 360);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(80, 30);
            this.button1.Text = "Main";
            this.button1.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // button2
            // 
            this.button2.BackColor = System.Drawing.Color.White;
            this.button2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button2.Location = new System.Drawing.Point(79, 360);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(80, 30);
            this.button2.Text = "Mixer";
            this.button2.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // button3
            // 
            this.button3.BackColor = System.Drawing.Color.White;
            this.button3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button3.Location = new System.Drawing.Point(159, 360);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(80, 30);
            this.button3.Text = "ConPump";
            this.button3.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button3.Click += new System.EventHandler(this.button3_Click);
            // 
            // button4
            // 
            this.button4.BackColor = System.Drawing.Color.White;
            this.button4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button4.Location = new System.Drawing.Point(239, 360);
            this.button4.Name = "button4";
            this.button4.Size = new System.Drawing.Size(80, 30);
            this.button4.Text = "DosPumpH";
            this.button4.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button4.Click += new System.EventHandler(this.button4_Click);
            // 
            // button5
            // 
            this.button5.BackColor = System.Drawing.Color.Silver;
            this.button5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button5.Location = new System.Drawing.Point(319, 360);
            this.button5.Name = "button5";
            this.button5.Size = new System.Drawing.Size(80, 30);
            this.button5.Text = "DosPumpL";
            this.button5.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button5.Click += new System.EventHandler(this.button5_Click);
            // 
            // button6
            // 
            this.button6.BackColor = System.Drawing.Color.White;
            this.button6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button6.Location = new System.Drawing.Point(399, 360);
            this.button6.Name = "button6";
            this.button6.Size = new System.Drawing.Size(80, 30);
            this.button6.Text = "Sys";
            this.button6.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button6.Click += new System.EventHandler(this.button6_Click);
            // 
            // button7
            // 
            this.button7.BackColor = System.Drawing.Color.White;
            this.button7.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button7.Location = new System.Drawing.Point(479, 360);
            this.button7.Name = "button7";
            this.button7.Size = new System.Drawing.Size(80, 30);
            this.button7.Text = "Robot";
            this.button7.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button7.Click += new System.EventHandler(this.button7_Click);
            // 
            // button8
            // 
            this.button8.BackColor = System.Drawing.Color.White;
            this.button8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button8.Location = new System.Drawing.Point(559, 360);
            this.button8.Name = "button8";
            this.button8.Size = new System.Drawing.Size(80, 30);
            this.button8.Text = "Info";
            this.button8.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button8.Click += new System.EventHandler(this.button8_Click);
            // 
            // DosingPump2G1
            // 
            this.DosingPump2G1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.DosingPump2G1.AutoScroll = false;
            this.DosingPump2G1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.DosingPump2G1.Controls.Add(this.InlineMixerG1);
            this.DosingPump2G1.Controls.Add(this.tab_CP1_1);
            this.DosingPump2G1.Dock = System.Windows.Forms.DockStyle.None;
            this.DosingPump2G1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.DosingPump2G1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.DosingPump2G1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.OnlyTopLine;
            this.DosingPump2G1.Location = new System.Drawing.Point(3, 31);
            this.DosingPump2G1.Name = "DosingPump2G1";
            this.DosingPump2G1.Size = new System.Drawing.Size(633, 323);
            this.DosingPump2G1.Tag = null;
            this.DosingPump2G1.Title = "Dosing Pump 2 (Low flowrate)";
            this.DosingPump2G1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // InlineMixerG1
            // 
            this.InlineMixerG1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.InlineMixerG1.AutoScroll = false;
            this.InlineMixerG1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.InlineMixerG1.Controls.Add(this.bar_AP1_Max_Flowrate);
            this.InlineMixerG1.Controls.Add(this.led_SP1_Error);
            this.InlineMixerG1.Controls.Add(this.bar_SP1_Curr_Flowrate);
            this.InlineMixerG1.Controls.Add(this.bar_SP1_Motor_Speed);
            this.InlineMixerG1.Controls.Add(this.tpsLabel5);
            this.InlineMixerG1.Controls.Add(this.tpsLabel4);
            this.InlineMixerG1.Controls.Add(this.lab_info_CP1_3);
            this.InlineMixerG1.Controls.Add(this.lab_info_CP1_2);
            this.InlineMixerG1.Controls.Add(this.lab_info_CP1_1);
            this.InlineMixerG1.Controls.Add(this.led_SP1_IsReady);
            this.InlineMixerG1.Controls.Add(this.led_SP1_IsRun);
            this.InlineMixerG1.Dock = System.Windows.Forms.DockStyle.None;
            this.InlineMixerG1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.InlineMixerG1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.InlineMixerG1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.InlineMixerG1.Location = new System.Drawing.Point(0, 23);
            this.InlineMixerG1.Name = "InlineMixerG1";
            this.InlineMixerG1.Size = new System.Drawing.Size(313, 297);
            this.InlineMixerG1.Tag = null;
            this.InlineMixerG1.Title = "Current Staus";
            this.InlineMixerG1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Top;
            // 
            // bar_AP1_Max_Flowrate
            // 
            this.bar_AP1_Max_Flowrate.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.bar_AP1_Max_Flowrate.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bar_AP1_Max_Flowrate.Location = new System.Drawing.Point(193, 169);
            this.bar_AP1_Max_Flowrate.Multiline = true;
            this.bar_AP1_Max_Flowrate.Name = "bar_AP1_Max_Flowrate";
            this.bar_AP1_Max_Flowrate.Size = new System.Drawing.Size(109, 24);
            this.bar_AP1_Max_Flowrate.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.bar_AP1_Max_Flowrate.Title = "130.00";
            // 
            // led_SP1_Error
            // 
            this.led_SP1_Error.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_SP1NoError")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_SP1_Error.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led_SP1_Error.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_SP1_Error.Location = new System.Drawing.Point(13, 63);
            this.led_SP1_Error.Name = "led_SP1_Error";
            this.led_SP1_Error.OffValue = 1;
            this.led_SP1_Error.OnValue = 0;
            this.led_SP1_Error.Size = new System.Drawing.Size(140, 34);
            this.led_SP1_Error.Text = "Error";
            // 
            // bar_SP1_Curr_Flowrate
            // 
            this.bar_SP1_Curr_Flowrate.BarColor = System.Drawing.Color.Maroon;
            this.bar_SP1_Curr_Flowrate.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("goA061_SP1SetFlowrate")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.bar_SP1_Curr_Flowrate.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.bar_SP1_Curr_Flowrate.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bar_SP1_Curr_Flowrate.Location = new System.Drawing.Point(193, 142);
            this.bar_SP1_Curr_Flowrate.Maximum = new decimal(new int[] {
                        130,
                        0,
                        0,
                        0});
            this.bar_SP1_Curr_Flowrate.Name = "bar_SP1_Curr_Flowrate";
            this.bar_SP1_Curr_Flowrate.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.bar_SP1_Curr_Flowrate.Precision = 2;
            this.bar_SP1_Curr_Flowrate.Size = new System.Drawing.Size(109, 21);
            this.bar_SP1_Curr_Flowrate.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.bar_SP1_Curr_Flowrate.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // bar_SP1_Motor_Speed
            // 
            this.bar_SP1_Motor_Speed.BarColor = System.Drawing.Color.Gray;
            this.bar_SP1_Motor_Speed.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.bar_SP1_Motor_Speed.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bar_SP1_Motor_Speed.Location = new System.Drawing.Point(193, 114);
            this.bar_SP1_Motor_Speed.Maximum = new decimal(new int[] {
                        18,
                        0,
                        0,
                        0});
            this.bar_SP1_Motor_Speed.Name = "bar_SP1_Motor_Speed";
            this.bar_SP1_Motor_Speed.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.bar_SP1_Motor_Speed.Precision = 2;
            this.bar_SP1_Motor_Speed.Size = new System.Drawing.Size(109, 21);
            this.bar_SP1_Motor_Speed.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.bar_SP1_Motor_Speed.ValuePlacement = ABB.Robotics.Tps.Windows.Forms.BarValuePlacement.Center;
            // 
            // tpsLabel5
            // 
            this.tpsLabel5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel5.Location = new System.Drawing.Point(10, 242);
            this.tpsLabel5.Multiline = true;
            this.tpsLabel5.Name = "tpsLabel5";
            this.tpsLabel5.Size = new System.Drawing.Size(177, 24);
            this.tpsLabel5.Title = "Material Density[g/cm3]";
            // 
            // tpsLabel4
            // 
            this.tpsLabel4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel4.Location = new System.Drawing.Point(10, 212);
            this.tpsLabel4.Multiline = true;
            this.tpsLabel4.Name = "tpsLabel4";
            this.tpsLabel4.Size = new System.Drawing.Size(177, 24);
            this.tpsLabel4.Title = "Material Mass[g]";
            // 
            // lab_info_CP1_3
            // 
            this.lab_info_CP1_3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_CP1_3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_CP1_3.Location = new System.Drawing.Point(10, 141);
            this.lab_info_CP1_3.Multiline = true;
            this.lab_info_CP1_3.Name = "lab_info_CP1_3";
            this.lab_info_CP1_3.Size = new System.Drawing.Size(186, 21);
            this.lab_info_CP1_3.Title = "Current Flowrate[ml/min]";
            // 
            // lab_info_CP1_2
            // 
            this.lab_info_CP1_2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_CP1_2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_CP1_2.Location = new System.Drawing.Point(10, 168);
            this.lab_info_CP1_2.Multiline = true;
            this.lab_info_CP1_2.Name = "lab_info_CP1_2";
            this.lab_info_CP1_2.Size = new System.Drawing.Size(177, 24);
            this.lab_info_CP1_2.Title = "Max. Flowrate[ml/min]";
            // 
            // lab_info_CP1_1
            // 
            this.lab_info_CP1_1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_CP1_1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_CP1_1.Location = new System.Drawing.Point(13, 114);
            this.lab_info_CP1_1.Multiline = true;
            this.lab_info_CP1_1.Name = "lab_info_CP1_1";
            this.lab_info_CP1_1.Size = new System.Drawing.Size(177, 21);
            this.lab_info_CP1_1.Title = "Motor Speed[rpm]";
            // 
            // led_SP1_IsReady
            // 
            this.led_SP1_IsReady.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_SP1NoError")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_SP1_IsReady.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led_SP1_IsReady.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_SP1_IsReady.Location = new System.Drawing.Point(13, 23);
            this.led_SP1_IsReady.Name = "led_SP1_IsReady";
            this.led_SP1_IsReady.Size = new System.Drawing.Size(140, 34);
            this.led_SP1_IsReady.Text = "Ready";
            // 
            // led_SP1_IsRun
            // 
            this.led_SP1_IsRun.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_SP1IsRun")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_SP1_IsRun.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led_SP1_IsRun.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_SP1_IsRun.Location = new System.Drawing.Point(153, 23);
            this.led_SP1_IsRun.Name = "led_SP1_IsRun";
            this.led_SP1_IsRun.Size = new System.Drawing.Size(152, 34);
            this.led_SP1_IsRun.Text = "Run";
            // 
            // tab_CP1_1
            // 
            this.tab_CP1_1.AutoScroll = false;
            this.tab_CP1_1.BackColor = System.Drawing.Color.White;
            this.tab_CP1_1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tab_CP1_1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tab_CP1_1.Location = new System.Drawing.Point(322, 23);
            this.tab_CP1_1.Name = "tab_CP1_1";
            this.tab_CP1_1.SelectedIndex = 0;
            this.tab_CP1_1.Size = new System.Drawing.Size(308, 297);
            this.tab_CP1_1.TabPages.Add(this.tabPage1);
            this.tab_CP1_1.TabPages.Add(this.tabPage2);
            // 
            // tabPage1
            // 
            this.tabPage1.Controls.Add(this.btn_A061_SP1_SetRun);
            this.tabPage1.Controls.Add(this.num_A061_SP1_SetSpeed);
            this.tabPage1.Controls.Add(this.led_A061_SP1_PowerOn);
            this.tabPage1.Controls.Add(this.lab_info_M1_8);
            this.tabPage1.Controls.Add(this.btn_A061_SP1_PowerOn);
            this.tabPage1.Dock = System.Windows.Forms.DockStyle.None;
            this.tabPage1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tabPage1.Location = new System.Drawing.Point(0, 40);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Size = new System.Drawing.Size(308, 257);
            this.tabPage1.Text = "Operation";
            // 
            // btn_A061_SP1_SetRun
            // 
            this.btn_A061_SP1_SetRun.AllowMultipleStates = true;
            this.btn_A061_SP1_SetRun.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_SP1_SetRun.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_SP1SetRun")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_SP1_SetRun.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_SP1_SetRun.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_SP1_SetRun.Location = new System.Drawing.Point(185, 176);
            this.btn_A061_SP1_SetRun.Name = "btn_A061_SP1_SetRun";
            this.btn_A061_SP1_SetRun.Size = new System.Drawing.Size(107, 61);
            stateObject1.Add("Text", "Start");
            stateObject1.Add("BackColor", System.Drawing.Color.White);
            stateObject2.Add("Text", "Stop");
            stateObject2.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_SP1_SetRun.States.Add(stateObject1);
            this.btn_A061_SP1_SetRun.States.Add(stateObject2);
            this.btn_A061_SP1_SetRun.Text = "Start/Stop";
            this.btn_A061_SP1_SetRun.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject3.Add("Text", "None");
            stateObject3.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_SP1_SetRun.UndefinedState = stateObject3;
            this.btn_A061_SP1_SetRun.Click += new System.EventHandler(this.btn_A061_SP1_SetRun_Click);
            // 
            // num_A061_SP1_SetSpeed
            // 
            this.num_A061_SP1_SetSpeed.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("goA061_SP1SetFlowrate")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.num_A061_SP1_SetSpeed.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.num_A061_SP1_SetSpeed.ForeColor = System.Drawing.SystemColors.ControlText;
            this.num_A061_SP1_SetSpeed.Location = new System.Drawing.Point(187, 124);
            this.num_A061_SP1_SetSpeed.Maximum = new decimal(new int[] {
                        137,
                        0,
                        0,
                        0});
            this.num_A061_SP1_SetSpeed.Minimum = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.num_A061_SP1_SetSpeed.Name = "num_A061_SP1_SetSpeed";
            this.num_A061_SP1_SetSpeed.Size = new System.Drawing.Size(105, 33);
            // 
            // led_A061_SP1_PowerOn
            // 
            this.led_A061_SP1_PowerOn.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_SP1PowerOn")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_A061_SP1_PowerOn.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.led_A061_SP1_PowerOn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_A061_SP1_PowerOn.Location = new System.Drawing.Point(14, 13);
            this.led_A061_SP1_PowerOn.Name = "led_A061_SP1_PowerOn";
            this.led_A061_SP1_PowerOn.Size = new System.Drawing.Size(165, 32);
            this.led_A061_SP1_PowerOn.Text = "Power On";
            // 
            // lab_info_M1_8
            // 
            this.lab_info_M1_8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_info_M1_8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_info_M1_8.Location = new System.Drawing.Point(20, 123);
            this.lab_info_M1_8.Multiline = true;
            this.lab_info_M1_8.Name = "lab_info_M1_8";
            this.lab_info_M1_8.Size = new System.Drawing.Size(163, 33);
            this.lab_info_M1_8.Title = "Flowrate [ml/min]";
            // 
            // btn_A061_SP1_PowerOn
            // 
            this.btn_A061_SP1_PowerOn.AllowMultipleStates = true;
            this.btn_A061_SP1_PowerOn.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_SP1_PowerOn.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_SP1PowerOn")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_SP1_PowerOn.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_SP1_PowerOn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_SP1_PowerOn.Location = new System.Drawing.Point(183, 13);
            this.btn_A061_SP1_PowerOn.Name = "btn_A061_SP1_PowerOn";
            this.btn_A061_SP1_PowerOn.Size = new System.Drawing.Size(107, 32);
            stateObject4.Add("Text", "On");
            stateObject4.Add("BackColor", System.Drawing.Color.White);
            stateObject5.Add("Text", "Off");
            stateObject5.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_SP1_PowerOn.States.Add(stateObject4);
            this.btn_A061_SP1_PowerOn.States.Add(stateObject5);
            this.btn_A061_SP1_PowerOn.Text = "On/Off";
            this.btn_A061_SP1_PowerOn.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject6.Add("Text", "None");
            stateObject6.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_SP1_PowerOn.UndefinedState = stateObject6;
            this.btn_A061_SP1_PowerOn.Click += new System.EventHandler(this.btn_A061_SP1_forward_Click);
            // 
            // tabPage2
            // 
            this.tabPage2.Controls.Add(this.numEditor3);
            this.tabPage2.Controls.Add(this.tpsLabel3);
            this.tabPage2.Controls.Add(this.led_A061_SP1_FLushOn);
            this.tabPage2.Controls.Add(this.btn_A061_SP1_FlushOn);
            this.tabPage2.Controls.Add(this.num_A061_SP1_DosingFactor);
            this.tabPage2.Controls.Add(this.tpsLabel2);
            this.tabPage2.Controls.Add(this.num_A061_SP1_SetCheckflow);
            this.tabPage2.Controls.Add(this.tpsLabel1);
            this.tabPage2.Controls.Add(this.led_A061_SP1_CheckOn);
            this.tabPage2.Controls.Add(this.btn_A061_SP1_CheckOn);
            this.tabPage2.Dock = System.Windows.Forms.DockStyle.None;
            this.tabPage2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tabPage2.Location = new System.Drawing.Point(0, 40);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Size = new System.Drawing.Size(308, 257);
            this.tabPage2.Text = "Calibration";
            // 
            // numEditor3
            // 
            this.numEditor3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.numEditor3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.numEditor3.Location = new System.Drawing.Point(185, 103);
            this.numEditor3.Maximum = new decimal(new int[] {
                        120,
                        0,
                        0,
                        0});
            this.numEditor3.Minimum = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.numEditor3.Name = "numEditor3";
            this.numEditor3.Size = new System.Drawing.Size(105, 33);
            this.numEditor3.Value = new decimal(new int[] {
                        60,
                        0,
                        0,
                        0});
            // 
            // tpsLabel3
            // 
            this.tpsLabel3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel3.Location = new System.Drawing.Point(14, 102);
            this.tpsLabel3.Multiline = true;
            this.tpsLabel3.Name = "tpsLabel3";
            this.tpsLabel3.Size = new System.Drawing.Size(163, 33);
            this.tpsLabel3.Title = "Calib. Time[s]";
            // 
            // led_A061_SP1_FLushOn
            // 
            this.led_A061_SP1_FLushOn.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_SP1FlushOn")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_A061_SP1_FLushOn.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.led_A061_SP1_FLushOn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_A061_SP1_FLushOn.Location = new System.Drawing.Point(14, 195);
            this.led_A061_SP1_FLushOn.Name = "led_A061_SP1_FLushOn";
            this.led_A061_SP1_FLushOn.Size = new System.Drawing.Size(163, 32);
            this.led_A061_SP1_FLushOn.Text = "Flush On";
            // 
            // btn_A061_SP1_FlushOn
            // 
            this.btn_A061_SP1_FlushOn.AllowMultipleStates = true;
            this.btn_A061_SP1_FlushOn.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_SP1_FlushOn.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_SP1FlushOn")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_SP1_FlushOn.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_SP1_FlushOn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_SP1_FlushOn.Location = new System.Drawing.Point(183, 195);
            this.btn_A061_SP1_FlushOn.Name = "btn_A061_SP1_FlushOn";
            this.btn_A061_SP1_FlushOn.Size = new System.Drawing.Size(107, 32);
            stateObject7.Add("Text", "On");
            stateObject7.Add("BackColor", System.Drawing.Color.White);
            stateObject8.Add("Text", "Off");
            stateObject8.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_SP1_FlushOn.States.Add(stateObject7);
            this.btn_A061_SP1_FlushOn.States.Add(stateObject8);
            this.btn_A061_SP1_FlushOn.Text = "On/Off";
            this.btn_A061_SP1_FlushOn.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject9.Add("Text", "None");
            stateObject9.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_SP1_FlushOn.UndefinedState = stateObject9;
            this.btn_A061_SP1_FlushOn.Click += new System.EventHandler(this.btn_A061_SP1_FlushOn_Click);
            // 
            // num_A061_SP1_DosingFactor
            // 
            this.num_A061_SP1_DosingFactor.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("goA061_SP1SetDosingFactor")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.num_A061_SP1_DosingFactor.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.num_A061_SP1_DosingFactor.ForeColor = System.Drawing.SystemColors.ControlText;
            this.num_A061_SP1_DosingFactor.Location = new System.Drawing.Point(185, 63);
            this.num_A061_SP1_DosingFactor.Maximum = new decimal(new int[] {
                        10,
                        0,
                        0,
                        0});
            this.num_A061_SP1_DosingFactor.Minimum = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.num_A061_SP1_DosingFactor.Name = "num_A061_SP1_DosingFactor";
            this.num_A061_SP1_DosingFactor.Size = new System.Drawing.Size(105, 33);
            // 
            // tpsLabel2
            // 
            this.tpsLabel2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel2.Location = new System.Drawing.Point(14, 62);
            this.tpsLabel2.Multiline = true;
            this.tpsLabel2.Name = "tpsLabel2";
            this.tpsLabel2.Size = new System.Drawing.Size(163, 33);
            this.tpsLabel2.Title = "Dosing Factor";
            // 
            // num_A061_SP1_SetCheckflow
            // 
            this.num_A061_SP1_SetCheckflow.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("goA061_SP1SetCheckFlow")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.num_A061_SP1_SetCheckflow.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.num_A061_SP1_SetCheckflow.ForeColor = System.Drawing.SystemColors.ControlText;
            this.num_A061_SP1_SetCheckflow.Location = new System.Drawing.Point(185, 24);
            this.num_A061_SP1_SetCheckflow.Maximum = new decimal(new int[] {
                        120,
                        0,
                        0,
                        0});
            this.num_A061_SP1_SetCheckflow.Minimum = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.num_A061_SP1_SetCheckflow.Name = "num_A061_SP1_SetCheckflow";
            this.num_A061_SP1_SetCheckflow.Size = new System.Drawing.Size(105, 33);
            // 
            // tpsLabel1
            // 
            this.tpsLabel1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel1.Location = new System.Drawing.Point(14, 23);
            this.tpsLabel1.Multiline = true;
            this.tpsLabel1.Name = "tpsLabel1";
            this.tpsLabel1.Size = new System.Drawing.Size(163, 33);
            this.tpsLabel1.Title = "Flowrate [ml/min]";
            // 
            // led_A061_SP1_CheckOn
            // 
            this.led_A061_SP1_CheckOn.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_SP1CheckOn")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_A061_SP1_CheckOn.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.led_A061_SP1_CheckOn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_A061_SP1_CheckOn.Location = new System.Drawing.Point(14, 157);
            this.led_A061_SP1_CheckOn.Name = "led_A061_SP1_CheckOn";
            this.led_A061_SP1_CheckOn.Size = new System.Drawing.Size(163, 32);
            this.led_A061_SP1_CheckOn.Text = "Check On";
            // 
            // btn_A061_SP1_CheckOn
            // 
            this.btn_A061_SP1_CheckOn.AllowMultipleStates = true;
            this.btn_A061_SP1_CheckOn.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_SP1_CheckOn.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_SP1CheckOn")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_SP1_CheckOn.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_SP1_CheckOn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_SP1_CheckOn.Location = new System.Drawing.Point(183, 157);
            this.btn_A061_SP1_CheckOn.Name = "btn_A061_SP1_CheckOn";
            this.btn_A061_SP1_CheckOn.Size = new System.Drawing.Size(107, 32);
            stateObject10.Add("Text", "On");
            stateObject10.Add("BackColor", System.Drawing.Color.White);
            stateObject11.Add("Text", "Off");
            stateObject11.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_SP1_CheckOn.States.Add(stateObject10);
            this.btn_A061_SP1_CheckOn.States.Add(stateObject11);
            this.btn_A061_SP1_CheckOn.Text = "On/Off";
            this.btn_A061_SP1_CheckOn.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject12.Add("Text", "None");
            stateObject12.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_SP1_CheckOn.UndefinedState = stateObject12;
            this.btn_A061_SP1_CheckOn.Click += new System.EventHandler(this.btn_A061_SP1_CheckOn_Click);
            // 
            // DosPumpL
            // 
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.DosingPump2G1);
            this.Controls.Add(this.button8);
            this.Controls.Add(this.button7);
            this.Controls.Add(this.button6);
            this.Controls.Add(this.button5);
            this.Controls.Add(this.button4);
            this.Controls.Add(this.button3);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.button1);
            this.Text = "Digital Casting System";
            this.Controls.SetChildIndex(this.button1, 0);
            this.Controls.SetChildIndex(this.button2, 0);
            this.Controls.SetChildIndex(this.button3, 0);
            this.Controls.SetChildIndex(this.button4, 0);
            this.Controls.SetChildIndex(this.button5, 0);
            this.Controls.SetChildIndex(this.button6, 0);
            this.Controls.SetChildIndex(this.button7, 0);
            this.Controls.SetChildIndex(this.button8, 0);
            this.Controls.SetChildIndex(this.DosingPump2G1, 0);
            this.DosingPump2G1.ResumeLayout(false);
            this.InlineMixerG1.ResumeLayout(false);
            this.tab_CP1_1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage2.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void button2_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Mixer));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button2_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button3_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(ConPump));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button3_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button4_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(DosPumpH));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button4_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button5_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(DosPumpL));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button5_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button6_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Sys));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button6_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button7_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Spare));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button7_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button8_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Spare2));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button8_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button1_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(MainScreen));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button1_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_SP1_forward_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalInvert
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_SP1PowerOn"))).Invert();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_SP1_forward_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_SP1_SetRun_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalInvert
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_SP1SetRun"))).Invert();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_SP1_SetRun_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_SP1_CheckOn_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalInvert
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_SP1CheckOn"))).Invert();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_SP1_CheckOn_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_SP1_FlushOn_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalInvert
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_SP1FlushOn"))).Invert();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_SP1_FlushOn_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
    }
}
