//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace DCSControlPanel
{
    
    
    public class MainScreen : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.Button button1;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button2;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button3;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button4;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button5;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button6;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button7;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox InlineMixerGroup1;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox ControllerG1;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_MI1_IsReady;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_MI1_SetRun;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_A061_MI1_speed;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_MI1_IsRun;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_CC1_Enable;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_A061_CC1_powerOn;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox ConcretePumpG1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel lab_A061_CP1_flowrate;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_CP1_IsRun;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_CP1_IsReady;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor num_A061_CP1_SetFlowrate;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_CC1_Reset;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_A061_CC1_reset;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_CP1_SetRun;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox ControllerG13;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_MI1_Enable;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_A061_MI1_enable;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox ControllerG12;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_A061_CC1_mode_manual;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_A061_CC1_mode_laptop;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_A061_CC1_mode_robot;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_goInfo;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_AP1_SetRun;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel1;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_AP1_IsRun;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor num_A061_AP1_SetSpeed;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_AP1_IsReady;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox2;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_SP1_SetRun;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel2;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_SP1_IsRun;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led_SP1_IsReady;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor num_A061_SP1_SetSpeed;
        
        private ABB.Robotics.Tps.Windows.Forms.Button btn_A061_CC1_record;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led8;
        
        private ABB.Robotics.Tps.Windows.Forms.NumEditor num_A061_MI1_SetSpeed;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button8;
        
        public MainScreen()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject1 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject2 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject3 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject4 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject5 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject6 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject7 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject8 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject9 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject10 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject11 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject12 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject13 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject14 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject15 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject16 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject17 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject18 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject19 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject20 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject21 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject22 = new ABB.Robotics.Tps.Windows.Forms.StateObject(0);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject23 = new ABB.Robotics.Tps.Windows.Forms.StateObject(1);
            ABB.Robotics.Tps.Windows.Forms.StateObject stateObject24 = new ABB.Robotics.Tps.Windows.Forms.StateObject(null);
            this.button1 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button2 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button3 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button4 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button5 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button6 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button7 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button8 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.InlineMixerGroup1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.num_A061_MI1_SetSpeed = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.btn_A061_MI1_SetRun = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.lab_A061_MI1_speed = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.led_MI1_IsRun = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led_MI1_IsReady = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.ControllerG1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.led8 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.btn_A061_CC1_record = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.ControllerG13 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.btn_A061_MI1_Enable = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.led_A061_MI1_enable = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.btn_A061_CC1_Enable = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.btn_A061_CC1_Reset = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.led_A061_CC1_powerOn = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led_A061_CC1_reset = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.ControllerG12 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.led_A061_CC1_mode_manual = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led_A061_CC1_mode_laptop = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led_A061_CC1_mode_robot = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.btn_A061_goInfo = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.ConcretePumpG1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.btn_A061_CP1_SetRun = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.lab_A061_CP1_flowrate = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.led_CP1_IsRun = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led_CP1_IsReady = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.num_A061_CP1_SetFlowrate = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.groupBox1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.btn_A061_AP1_SetRun = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.tpsLabel1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.led_AP1_IsRun = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.num_A061_AP1_SetSpeed = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.led_AP1_IsReady = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.groupBox2 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.btn_A061_SP1_SetRun = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.tpsLabel2 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.led_SP1_IsRun = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led_SP1_IsReady = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.num_A061_SP1_SetSpeed = new ABB.Robotics.Tps.Windows.Forms.NumEditor();
            this.InlineMixerGroup1.SuspendLayout();
            this.ControllerG1.SuspendLayout();
            this.ControllerG13.SuspendLayout();
            this.ControllerG12.SuspendLayout();
            this.ConcretePumpG1.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.SuspendLayout();
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.Color.Silver;
            this.button1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button1.Location = new System.Drawing.Point(-1, 360);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(80, 30);
            this.button1.Text = "Main";
            this.button1.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // button2
            // 
            this.button2.BackColor = System.Drawing.Color.White;
            this.button2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button2.Location = new System.Drawing.Point(79, 360);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(80, 30);
            this.button2.Text = "Mixer";
            this.button2.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // button3
            // 
            this.button3.BackColor = System.Drawing.Color.White;
            this.button3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button3.Location = new System.Drawing.Point(159, 360);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(80, 30);
            this.button3.Text = "ConPump";
            this.button3.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button3.Click += new System.EventHandler(this.button3_Click);
            // 
            // button4
            // 
            this.button4.BackColor = System.Drawing.Color.White;
            this.button4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button4.Location = new System.Drawing.Point(239, 360);
            this.button4.Name = "button4";
            this.button4.Size = new System.Drawing.Size(80, 30);
            this.button4.Text = "DosPumpH";
            this.button4.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button4.Click += new System.EventHandler(this.button4_Click);
            // 
            // button5
            // 
            this.button5.BackColor = System.Drawing.Color.White;
            this.button5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button5.Location = new System.Drawing.Point(319, 360);
            this.button5.Name = "button5";
            this.button5.Size = new System.Drawing.Size(80, 30);
            this.button5.Text = "DosPumpL";
            this.button5.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button5.Click += new System.EventHandler(this.button5_Click);
            // 
            // button6
            // 
            this.button6.BackColor = System.Drawing.Color.White;
            this.button6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button6.Location = new System.Drawing.Point(399, 360);
            this.button6.Name = "button6";
            this.button6.Size = new System.Drawing.Size(80, 30);
            this.button6.Text = "Sys";
            this.button6.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button6.Click += new System.EventHandler(this.button6_Click);
            // 
            // button7
            // 
            this.button7.BackColor = System.Drawing.Color.White;
            this.button7.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button7.Location = new System.Drawing.Point(479, 360);
            this.button7.Name = "button7";
            this.button7.Size = new System.Drawing.Size(80, 30);
            this.button7.Text = "Robot";
            this.button7.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button7.Click += new System.EventHandler(this.button7_Click);
            // 
            // button8
            // 
            this.button8.BackColor = System.Drawing.Color.White;
            this.button8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.button8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button8.Location = new System.Drawing.Point(559, 360);
            this.button8.Name = "button8";
            this.button8.Size = new System.Drawing.Size(80, 30);
            this.button8.Text = "Info";
            this.button8.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button8.Click += new System.EventHandler(this.button8_Click);
            // 
            // InlineMixerGroup1
            // 
            this.InlineMixerGroup1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.InlineMixerGroup1.AutoScroll = false;
            this.InlineMixerGroup1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.InlineMixerGroup1.Controls.Add(this.num_A061_MI1_SetSpeed);
            this.InlineMixerGroup1.Controls.Add(this.btn_A061_MI1_SetRun);
            this.InlineMixerGroup1.Controls.Add(this.lab_A061_MI1_speed);
            this.InlineMixerGroup1.Controls.Add(this.led_MI1_IsRun);
            this.InlineMixerGroup1.Controls.Add(this.led_MI1_IsReady);
            this.InlineMixerGroup1.Dock = System.Windows.Forms.DockStyle.None;
            this.InlineMixerGroup1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.InlineMixerGroup1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.InlineMixerGroup1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.OnlyTopLine;
            this.InlineMixerGroup1.Location = new System.Drawing.Point(3, 31);
            this.InlineMixerGroup1.Name = "InlineMixerGroup1";
            this.InlineMixerGroup1.Size = new System.Drawing.Size(310, 85);
            this.InlineMixerGroup1.Tag = null;
            this.InlineMixerGroup1.Title = "Inline Mixer";
            this.InlineMixerGroup1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // num_A061_MI1_SetSpeed
            // 
            this.num_A061_MI1_SetSpeed.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("goA061_MI1SetSpeed")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.num_A061_MI1_SetSpeed.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.num_A061_MI1_SetSpeed.ForeColor = System.Drawing.SystemColors.ControlText;
            this.num_A061_MI1_SetSpeed.Location = new System.Drawing.Point(91, 49);
            this.num_A061_MI1_SetSpeed.Maximum = new decimal(new int[] {
                        120,
                        0,
                        0,
                        0});
            this.num_A061_MI1_SetSpeed.Minimum = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.num_A061_MI1_SetSpeed.Name = "num_A061_MI1_SetSpeed";
            this.num_A061_MI1_SetSpeed.Size = new System.Drawing.Size(108, 33);
            // 
            // btn_A061_MI1_SetRun
            // 
            this.btn_A061_MI1_SetRun.AllowMultipleStates = true;
            this.btn_A061_MI1_SetRun.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_MI1_SetRun.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_MI1SetRun")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_MI1_SetRun.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_MI1_SetRun.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_MI1_SetRun.Location = new System.Drawing.Point(205, 22);
            this.btn_A061_MI1_SetRun.Name = "btn_A061_MI1_SetRun";
            this.btn_A061_MI1_SetRun.Size = new System.Drawing.Size(101, 61);
            stateObject1.Add("Text", "Start");
            stateObject1.Add("BackColor", System.Drawing.Color.White);
            stateObject2.Add("Text", "Stop");
            stateObject2.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_MI1_SetRun.States.Add(stateObject1);
            this.btn_A061_MI1_SetRun.States.Add(stateObject2);
            this.btn_A061_MI1_SetRun.Text = "Start/Stop";
            this.btn_A061_MI1_SetRun.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject3.Add("Text", "None");
            stateObject3.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_MI1_SetRun.UndefinedState = stateObject3;
            this.btn_A061_MI1_SetRun.Click += new System.EventHandler(this.btn_A061_MI1_SetRun_Click);
            // 
            // lab_A061_MI1_speed
            // 
            this.lab_A061_MI1_speed.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_A061_MI1_speed.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_A061_MI1_speed.Location = new System.Drawing.Point(91, 22);
            this.lab_A061_MI1_speed.Multiline = true;
            this.lab_A061_MI1_speed.Name = "lab_A061_MI1_speed";
            this.lab_A061_MI1_speed.Size = new System.Drawing.Size(108, 22);
            this.lab_A061_MI1_speed.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.lab_A061_MI1_speed.Title = "[rpm]";
            // 
            // led_MI1_IsRun
            // 
            this.led_MI1_IsRun.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_MI1IsRun")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_MI1_IsRun.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led_MI1_IsRun.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_MI1_IsRun.Location = new System.Drawing.Point(3, 50);
            this.led_MI1_IsRun.Name = "led_MI1_IsRun";
            this.led_MI1_IsRun.Size = new System.Drawing.Size(87, 34);
            this.led_MI1_IsRun.Text = "Run";
            // 
            // led_MI1_IsReady
            // 
            this.led_MI1_IsReady.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_MI1IsReady")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_MI1_IsReady.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led_MI1_IsReady.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_MI1_IsReady.Location = new System.Drawing.Point(3, 22);
            this.led_MI1_IsReady.Name = "led_MI1_IsReady";
            this.led_MI1_IsReady.Size = new System.Drawing.Size(87, 32);
            this.led_MI1_IsReady.Text = "Ready";
            // 
            // ControllerG1
            // 
            this.ControllerG1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.ControllerG1.AutoScroll = false;
            this.ControllerG1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.ControllerG1.Controls.Add(this.led8);
            this.ControllerG1.Controls.Add(this.btn_A061_CC1_record);
            this.ControllerG1.Controls.Add(this.ControllerG13);
            this.ControllerG1.Controls.Add(this.ControllerG12);
            this.ControllerG1.Controls.Add(this.btn_A061_goInfo);
            this.ControllerG1.Dock = System.Windows.Forms.DockStyle.None;
            this.ControllerG1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.ControllerG1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.ControllerG1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.OnlyTopLine;
            this.ControllerG1.Location = new System.Drawing.Point(3, 215);
            this.ControllerG1.Name = "ControllerG1";
            this.ControllerG1.Size = new System.Drawing.Size(629, 139);
            this.ControllerG1.Tag = null;
            this.ControllerG1.Title = "Controller";
            this.ControllerG1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // led8
            // 
            this.led8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led8.Location = new System.Drawing.Point(322, 68);
            this.led8.Name = "led8";
            this.led8.Size = new System.Drawing.Size(33, 33);
            this.led8.Text = "";
            // 
            // btn_A061_CC1_record
            // 
            this.btn_A061_CC1_record.AllowMultipleStates = true;
            this.btn_A061_CC1_record.BackColor = System.Drawing.Color.White;
            this.btn_A061_CC1_record.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_CC1_record.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_CC1_record.Location = new System.Drawing.Point(369, 69);
            this.btn_A061_CC1_record.Name = "btn_A061_CC1_record";
            this.btn_A061_CC1_record.Size = new System.Drawing.Size(241, 32);
            stateObject4.Add("Text", "Record data");
            stateObject4.Add("BackColor", System.Drawing.Color.White);
            stateObject5.Add("Text", "Recording data");
            stateObject5.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CC1_record.States.Add(stateObject4);
            this.btn_A061_CC1_record.States.Add(stateObject5);
            this.btn_A061_CC1_record.Text = "Record/Recording";
            this.btn_A061_CC1_record.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject6.Add("Text", "Record/Recording");
            stateObject6.Add("BackColor", System.Drawing.Color.White);
            this.btn_A061_CC1_record.UndefinedState = stateObject6;
            // 
            // ControllerG13
            // 
            this.ControllerG13.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.ControllerG13.AutoScroll = false;
            this.ControllerG13.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.ControllerG13.Controls.Add(this.btn_A061_MI1_Enable);
            this.ControllerG13.Controls.Add(this.led_A061_MI1_enable);
            this.ControllerG13.Controls.Add(this.btn_A061_CC1_Enable);
            this.ControllerG13.Controls.Add(this.btn_A061_CC1_Reset);
            this.ControllerG13.Controls.Add(this.led_A061_CC1_powerOn);
            this.ControllerG13.Controls.Add(this.led_A061_CC1_reset);
            this.ControllerG13.Dock = System.Windows.Forms.DockStyle.None;
            this.ControllerG13.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.ControllerG13.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.ControllerG13.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.OnlyTopLine;
            this.ControllerG13.Location = new System.Drawing.Point(3, 19);
            this.ControllerG13.Name = "ControllerG13";
            this.ControllerG13.Size = new System.Drawing.Size(279, 126);
            this.ControllerG13.Tag = null;
            this.ControllerG13.Title = "Power";
            this.ControllerG13.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // btn_A061_MI1_Enable
            // 
            this.btn_A061_MI1_Enable.AllowMultipleStates = true;
            this.btn_A061_MI1_Enable.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_MI1_Enable.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_MI1Enable")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_MI1_Enable.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_MI1_Enable.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_MI1_Enable.Location = new System.Drawing.Point(164, 88);
            this.btn_A061_MI1_Enable.Name = "btn_A061_MI1_Enable";
            this.btn_A061_MI1_Enable.Size = new System.Drawing.Size(107, 32);
            stateObject7.Add("Text", "On");
            stateObject7.Add("BackColor", System.Drawing.Color.White);
            stateObject8.Add("Text", "Off");
            stateObject8.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_MI1_Enable.States.Add(stateObject7);
            this.btn_A061_MI1_Enable.States.Add(stateObject8);
            this.btn_A061_MI1_Enable.Text = "On/Off";
            this.btn_A061_MI1_Enable.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject9.Add("Text", "None");
            stateObject9.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_MI1_Enable.UndefinedState = stateObject9;
            this.btn_A061_MI1_Enable.Click += new System.EventHandler(this.btn_A061_MI1_Enable_Click);
            // 
            // led_A061_MI1_enable
            // 
            this.led_A061_MI1_enable.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_MI1Enable")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_A061_MI1_enable.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.led_A061_MI1_enable.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_A061_MI1_enable.Location = new System.Drawing.Point(3, 88);
            this.led_A061_MI1_enable.Name = "led_A061_MI1_enable";
            this.led_A061_MI1_enable.Size = new System.Drawing.Size(151, 32);
            this.led_A061_MI1_enable.Text = "Inline Mixer";
            // 
            // btn_A061_CC1_Enable
            // 
            this.btn_A061_CC1_Enable.AllowMultipleStates = true;
            this.btn_A061_CC1_Enable.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_CC1_Enable.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_CC1Enable")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_CC1_Enable.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_CC1_Enable.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_CC1_Enable.Location = new System.Drawing.Point(164, 12);
            this.btn_A061_CC1_Enable.Name = "btn_A061_CC1_Enable";
            this.btn_A061_CC1_Enable.Size = new System.Drawing.Size(107, 32);
            stateObject10.Add("Text", "On");
            stateObject10.Add("BackColor", System.Drawing.Color.White);
            stateObject11.Add("Text", "Off");
            stateObject11.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CC1_Enable.States.Add(stateObject10);
            this.btn_A061_CC1_Enable.States.Add(stateObject11);
            this.btn_A061_CC1_Enable.Text = "On/Off";
            this.btn_A061_CC1_Enable.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject12.Add("Text", "None");
            stateObject12.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CC1_Enable.UndefinedState = stateObject12;
            this.btn_A061_CC1_Enable.Click += new System.EventHandler(this.btn_A061_CC1_Enable_Click);
            // 
            // btn_A061_CC1_Reset
            // 
            this.btn_A061_CC1_Reset.AllowMultipleStates = true;
            this.btn_A061_CC1_Reset.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_CC1_Reset.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_CC1Reset")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_CC1_Reset.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_CC1_Reset.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_CC1_Reset.Location = new System.Drawing.Point(164, 50);
            this.btn_A061_CC1_Reset.Name = "btn_A061_CC1_Reset";
            this.btn_A061_CC1_Reset.Size = new System.Drawing.Size(107, 32);
            stateObject13.Add("Text", "On");
            stateObject13.Add("BackColor", System.Drawing.Color.White);
            stateObject14.Add("Text", "Off");
            stateObject14.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CC1_Reset.States.Add(stateObject13);
            this.btn_A061_CC1_Reset.States.Add(stateObject14);
            this.btn_A061_CC1_Reset.Text = "On/Off";
            this.btn_A061_CC1_Reset.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject15.Add("Text", "None");
            stateObject15.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CC1_Reset.UndefinedState = stateObject15;
            this.btn_A061_CC1_Reset.Click += new System.EventHandler(this.btn_A061_CC1_Reset_Click);
            // 
            // led_A061_CC1_powerOn
            // 
            this.led_A061_CC1_powerOn.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_CC1_power_on")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_A061_CC1_powerOn.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.led_A061_CC1_powerOn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_A061_CC1_powerOn.Location = new System.Drawing.Point(3, 12);
            this.led_A061_CC1_powerOn.Name = "led_A061_CC1_powerOn";
            this.led_A061_CC1_powerOn.Size = new System.Drawing.Size(123, 32);
            this.led_A061_CC1_powerOn.Text = "Power";
            // 
            // led_A061_CC1_reset
            // 
            this.led_A061_CC1_reset.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_CC1Reset")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_A061_CC1_reset.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.led_A061_CC1_reset.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_A061_CC1_reset.Location = new System.Drawing.Point(3, 50);
            this.led_A061_CC1_reset.Name = "led_A061_CC1_reset";
            this.led_A061_CC1_reset.Size = new System.Drawing.Size(123, 32);
            this.led_A061_CC1_reset.Text = "Reset";
            // 
            // ControllerG12
            // 
            this.ControllerG12.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.ControllerG12.AutoScroll = false;
            this.ControllerG12.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.ControllerG12.Controls.Add(this.led_A061_CC1_mode_manual);
            this.ControllerG12.Controls.Add(this.led_A061_CC1_mode_laptop);
            this.ControllerG12.Controls.Add(this.led_A061_CC1_mode_robot);
            this.ControllerG12.Dock = System.Windows.Forms.DockStyle.None;
            this.ControllerG12.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.ControllerG12.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.ControllerG12.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.OnlyTopLine;
            this.ControllerG12.Location = new System.Drawing.Point(319, 19);
            this.ControllerG12.Name = "ControllerG12";
            this.ControllerG12.Size = new System.Drawing.Size(317, 51);
            this.ControllerG12.Tag = null;
            this.ControllerG12.Title = "Operation mode";
            this.ControllerG12.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // led_A061_CC1_mode_manual
            // 
            this.led_A061_CC1_mode_manual.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_CC1_mode_manual")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_A061_CC1_mode_manual.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.led_A061_CC1_mode_manual.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_A061_CC1_mode_manual.Location = new System.Drawing.Point(188, 18);
            this.led_A061_CC1_mode_manual.Name = "led_A061_CC1_mode_manual";
            this.led_A061_CC1_mode_manual.Size = new System.Drawing.Size(101, 32);
            this.led_A061_CC1_mode_manual.Text = "Manual";
            // 
            // led_A061_CC1_mode_laptop
            // 
            this.led_A061_CC1_mode_laptop.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_CC1_mode_laptop")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_A061_CC1_mode_laptop.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.led_A061_CC1_mode_laptop.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_A061_CC1_mode_laptop.Location = new System.Drawing.Point(91, 18);
            this.led_A061_CC1_mode_laptop.Name = "led_A061_CC1_mode_laptop";
            this.led_A061_CC1_mode_laptop.Size = new System.Drawing.Size(96, 32);
            this.led_A061_CC1_mode_laptop.Text = "Laptop";
            // 
            // led_A061_CC1_mode_robot
            // 
            this.led_A061_CC1_mode_robot.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_CC1_mode_robot")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_A061_CC1_mode_robot.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9b;
            this.led_A061_CC1_mode_robot.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_A061_CC1_mode_robot.Location = new System.Drawing.Point(3, 18);
            this.led_A061_CC1_mode_robot.Name = "led_A061_CC1_mode_robot";
            this.led_A061_CC1_mode_robot.Size = new System.Drawing.Size(82, 32);
            this.led_A061_CC1_mode_robot.Text = "Robot";
            // 
            // btn_A061_goInfo
            // 
            this.btn_A061_goInfo.BackColor = System.Drawing.Color.White;
            this.btn_A061_goInfo.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_goInfo.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_goInfo.Location = new System.Drawing.Point(476, 104);
            this.btn_A061_goInfo.Name = "btn_A061_goInfo";
            this.btn_A061_goInfo.Size = new System.Drawing.Size(134, 35);
            this.btn_A061_goInfo.Text = "--INFO>";
            this.btn_A061_goInfo.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.btn_A061_goInfo.Click += new System.EventHandler(this.btn_goInfo);
            // 
            // ConcretePumpG1
            // 
            this.ConcretePumpG1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.ConcretePumpG1.AutoScroll = false;
            this.ConcretePumpG1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.ConcretePumpG1.Controls.Add(this.btn_A061_CP1_SetRun);
            this.ConcretePumpG1.Controls.Add(this.lab_A061_CP1_flowrate);
            this.ConcretePumpG1.Controls.Add(this.led_CP1_IsRun);
            this.ConcretePumpG1.Controls.Add(this.led_CP1_IsReady);
            this.ConcretePumpG1.Controls.Add(this.num_A061_CP1_SetFlowrate);
            this.ConcretePumpG1.Dock = System.Windows.Forms.DockStyle.None;
            this.ConcretePumpG1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.ConcretePumpG1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.ConcretePumpG1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.OnlyTopLine;
            this.ConcretePumpG1.Location = new System.Drawing.Point(315, 31);
            this.ConcretePumpG1.Name = "ConcretePumpG1";
            this.ConcretePumpG1.Size = new System.Drawing.Size(317, 85);
            this.ConcretePumpG1.Tag = null;
            this.ConcretePumpG1.Title = "Concrete Pump";
            this.ConcretePumpG1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // btn_A061_CP1_SetRun
            // 
            this.btn_A061_CP1_SetRun.AllowMultipleStates = true;
            this.btn_A061_CP1_SetRun.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_CP1_SetRun.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_CP1ForwardOn")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_CP1_SetRun.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_CP1_SetRun.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_CP1_SetRun.Location = new System.Drawing.Point(216, 22);
            this.btn_A061_CP1_SetRun.Name = "btn_A061_CP1_SetRun";
            this.btn_A061_CP1_SetRun.Size = new System.Drawing.Size(101, 61);
            stateObject16.Add("Text", "Start");
            stateObject16.Add("BackColor", System.Drawing.Color.White);
            stateObject17.Add("Text", "Stop");
            stateObject17.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CP1_SetRun.States.Add(stateObject16);
            this.btn_A061_CP1_SetRun.States.Add(stateObject17);
            this.btn_A061_CP1_SetRun.Text = "Start/Stop";
            this.btn_A061_CP1_SetRun.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject18.Add("Text", "None");
            stateObject18.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_CP1_SetRun.UndefinedState = stateObject18;
            this.btn_A061_CP1_SetRun.Click += new System.EventHandler(this.btn_A061_CP1_SetRun_Click);
            // 
            // lab_A061_CP1_flowrate
            // 
            this.lab_A061_CP1_flowrate.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.lab_A061_CP1_flowrate.ForeColor = System.Drawing.SystemColors.ControlText;
            this.lab_A061_CP1_flowrate.Location = new System.Drawing.Point(101, 22);
            this.lab_A061_CP1_flowrate.Multiline = true;
            this.lab_A061_CP1_flowrate.Name = "lab_A061_CP1_flowrate";
            this.lab_A061_CP1_flowrate.Size = new System.Drawing.Size(105, 22);
            this.lab_A061_CP1_flowrate.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.lab_A061_CP1_flowrate.Title = "[l/min]";
            // 
            // led_CP1_IsRun
            // 
            this.led_CP1_IsRun.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_CP1IsRun")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_CP1_IsRun.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led_CP1_IsRun.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_CP1_IsRun.Location = new System.Drawing.Point(4, 50);
            this.led_CP1_IsRun.Name = "led_CP1_IsRun";
            this.led_CP1_IsRun.Size = new System.Drawing.Size(91, 33);
            this.led_CP1_IsRun.Text = "Run";
            // 
            // led_CP1_IsReady
            // 
            this.led_CP1_IsReady.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_CP1IsReady")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_CP1_IsReady.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led_CP1_IsReady.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_CP1_IsReady.Location = new System.Drawing.Point(4, 22);
            this.led_CP1_IsReady.Name = "led_CP1_IsReady";
            this.led_CP1_IsReady.Size = new System.Drawing.Size(91, 34);
            this.led_CP1_IsReady.Text = "Ready";
            // 
            // num_A061_CP1_SetFlowrate
            // 
            this.num_A061_CP1_SetFlowrate.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("goA061_CP1SetFlowrate")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.num_A061_CP1_SetFlowrate.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.num_A061_CP1_SetFlowrate.ForeColor = System.Drawing.SystemColors.ControlText;
            this.num_A061_CP1_SetFlowrate.Location = new System.Drawing.Point(101, 50);
            this.num_A061_CP1_SetFlowrate.Maximum = new decimal(new int[] {
                        24,
                        0,
                        0,
                        0});
            this.num_A061_CP1_SetFlowrate.Minimum = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.num_A061_CP1_SetFlowrate.Name = "num_A061_CP1_SetFlowrate";
            this.num_A061_CP1_SetFlowrate.Size = new System.Drawing.Size(108, 33);
            // 
            // groupBox1
            // 
            this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox1.AutoScroll = false;
            this.groupBox1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox1.Controls.Add(this.btn_A061_AP1_SetRun);
            this.groupBox1.Controls.Add(this.tpsLabel1);
            this.groupBox1.Controls.Add(this.led_AP1_IsRun);
            this.groupBox1.Controls.Add(this.num_A061_AP1_SetSpeed);
            this.groupBox1.Controls.Add(this.led_AP1_IsReady);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.OnlyTopLine;
            this.groupBox1.Location = new System.Drawing.Point(3, 122);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(310, 87);
            this.groupBox1.Tag = null;
            this.groupBox1.Title = "Dosing Pump 1";
            this.groupBox1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // btn_A061_AP1_SetRun
            // 
            this.btn_A061_AP1_SetRun.AllowMultipleStates = true;
            this.btn_A061_AP1_SetRun.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_AP1_SetRun.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_AP1SetRun")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_AP1_SetRun.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_AP1_SetRun.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_AP1_SetRun.Location = new System.Drawing.Point(204, 22);
            this.btn_A061_AP1_SetRun.Name = "btn_A061_AP1_SetRun";
            this.btn_A061_AP1_SetRun.Size = new System.Drawing.Size(101, 61);
            stateObject19.Add("Text", "Start");
            stateObject19.Add("BackColor", System.Drawing.Color.White);
            stateObject20.Add("Text", "Stop");
            stateObject20.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_AP1_SetRun.States.Add(stateObject19);
            this.btn_A061_AP1_SetRun.States.Add(stateObject20);
            this.btn_A061_AP1_SetRun.Text = "Start/Stop";
            this.btn_A061_AP1_SetRun.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject21.Add("Text", "None");
            stateObject21.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_AP1_SetRun.UndefinedState = stateObject21;
            this.btn_A061_AP1_SetRun.Click += new System.EventHandler(this.btn_A061_AP1_SetRun_Click);
            // 
            // tpsLabel1
            // 
            this.tpsLabel1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel1.Location = new System.Drawing.Point(91, 22);
            this.tpsLabel1.Multiline = true;
            this.tpsLabel1.Name = "tpsLabel1";
            this.tpsLabel1.Size = new System.Drawing.Size(108, 22);
            this.tpsLabel1.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.tpsLabel1.Title = "[ml/min]";
            // 
            // led_AP1_IsRun
            // 
            this.led_AP1_IsRun.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_AP1IsRun")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_AP1_IsRun.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led_AP1_IsRun.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_AP1_IsRun.Location = new System.Drawing.Point(3, 50);
            this.led_AP1_IsRun.Name = "led_AP1_IsRun";
            this.led_AP1_IsRun.Size = new System.Drawing.Size(86, 34);
            this.led_AP1_IsRun.Text = "Run";
            // 
            // num_A061_AP1_SetSpeed
            // 
            this.num_A061_AP1_SetSpeed.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("goA061_AP1SetFlowrate")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.num_A061_AP1_SetSpeed.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.num_A061_AP1_SetSpeed.ForeColor = System.Drawing.SystemColors.ControlText;
            this.num_A061_AP1_SetSpeed.Location = new System.Drawing.Point(91, 50);
            this.num_A061_AP1_SetSpeed.Maximum = new decimal(new int[] {
                        637,
                        0,
                        0,
                        0});
            this.num_A061_AP1_SetSpeed.Minimum = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.num_A061_AP1_SetSpeed.Name = "num_A061_AP1_SetSpeed";
            this.num_A061_AP1_SetSpeed.Size = new System.Drawing.Size(108, 33);
            // 
            // led_AP1_IsReady
            // 
            this.led_AP1_IsReady.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_AP1NoError")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_AP1_IsReady.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led_AP1_IsReady.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_AP1_IsReady.Location = new System.Drawing.Point(3, 22);
            this.led_AP1_IsReady.Name = "led_AP1_IsReady";
            this.led_AP1_IsReady.Size = new System.Drawing.Size(86, 32);
            this.led_AP1_IsReady.Text = "Ready";
            // 
            // groupBox2
            // 
            this.groupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox2.AutoScroll = false;
            this.groupBox2.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox2.Controls.Add(this.btn_A061_SP1_SetRun);
            this.groupBox2.Controls.Add(this.tpsLabel2);
            this.groupBox2.Controls.Add(this.led_SP1_IsRun);
            this.groupBox2.Controls.Add(this.led_SP1_IsReady);
            this.groupBox2.Controls.Add(this.num_A061_SP1_SetSpeed);
            this.groupBox2.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox2.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox2.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.OnlyTopLine;
            this.groupBox2.Location = new System.Drawing.Point(319, 122);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(313, 87);
            this.groupBox2.Tag = null;
            this.groupBox2.Title = "Dosing Pump 2";
            this.groupBox2.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // btn_A061_SP1_SetRun
            // 
            this.btn_A061_SP1_SetRun.AllowMultipleStates = true;
            this.btn_A061_SP1_SetRun.BackColor = System.Drawing.Color.Gainsboro;
            this.btn_A061_SP1_SetRun.DataBindings.Add(new System.Windows.Forms.Binding("SelectedStateValue", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("doA061_SP1SetRun")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.btn_A061_SP1_SetRun.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.btn_A061_SP1_SetRun.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btn_A061_SP1_SetRun.Location = new System.Drawing.Point(212, 22);
            this.btn_A061_SP1_SetRun.Name = "btn_A061_SP1_SetRun";
            this.btn_A061_SP1_SetRun.Size = new System.Drawing.Size(101, 61);
            stateObject22.Add("Text", "Start");
            stateObject22.Add("BackColor", System.Drawing.Color.White);
            stateObject23.Add("Text", "Stop");
            stateObject23.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_SP1_SetRun.States.Add(stateObject22);
            this.btn_A061_SP1_SetRun.States.Add(stateObject23);
            this.btn_A061_SP1_SetRun.Text = "Start/Stop";
            this.btn_A061_SP1_SetRun.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            stateObject24.Add("Text", "None");
            stateObject24.Add("BackColor", System.Drawing.Color.Gainsboro);
            this.btn_A061_SP1_SetRun.UndefinedState = stateObject24;
            this.btn_A061_SP1_SetRun.Click += new System.EventHandler(this.btn_A061_SP1_SetRun_Click);
            // 
            // tpsLabel2
            // 
            this.tpsLabel2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.tpsLabel2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel2.Location = new System.Drawing.Point(101, 22);
            this.tpsLabel2.Multiline = true;
            this.tpsLabel2.Name = "tpsLabel2";
            this.tpsLabel2.Size = new System.Drawing.Size(105, 22);
            this.tpsLabel2.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.tpsLabel2.Title = "[ml/min]";
            // 
            // led_SP1_IsRun
            // 
            this.led_SP1_IsRun.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_SP1IsRun")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_SP1_IsRun.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led_SP1_IsRun.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_SP1_IsRun.Location = new System.Drawing.Point(4, 50);
            this.led_SP1_IsRun.Name = "led_SP1_IsRun";
            this.led_SP1_IsRun.Size = new System.Drawing.Size(91, 33);
            this.led_SP1_IsRun.Text = "Run";
            // 
            // led_SP1_IsReady
            // 
            this.led_SP1_IsReady.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("diA061_SP1NoError")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led_SP1_IsReady.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8b;
            this.led_SP1_IsReady.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led_SP1_IsReady.Location = new System.Drawing.Point(4, 22);
            this.led_SP1_IsReady.Name = "led_SP1_IsReady";
            this.led_SP1_IsReady.Size = new System.Drawing.Size(91, 34);
            this.led_SP1_IsReady.Text = "Ready";
            // 
            // num_A061_SP1_SetSpeed
            // 
            this.num_A061_SP1_SetSpeed.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("goA061_SP1SetFlowrate")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.num_A061_SP1_SetSpeed.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.num_A061_SP1_SetSpeed.ForeColor = System.Drawing.SystemColors.ControlText;
            this.num_A061_SP1_SetSpeed.Location = new System.Drawing.Point(98, 50);
            this.num_A061_SP1_SetSpeed.Maximum = new decimal(new int[] {
                        138,
                        0,
                        0,
                        0});
            this.num_A061_SP1_SetSpeed.Minimum = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            this.num_A061_SP1_SetSpeed.Name = "num_A061_SP1_SetSpeed";
            this.num_A061_SP1_SetSpeed.Size = new System.Drawing.Size(108, 33);
            // 
            // MainScreen
            // 
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.InlineMixerGroup1);
            this.Controls.Add(this.ConcretePumpG1);
            this.Controls.Add(this.button8);
            this.Controls.Add(this.button7);
            this.Controls.Add(this.button6);
            this.Controls.Add(this.button5);
            this.Controls.Add(this.button4);
            this.Controls.Add(this.button3);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.ControllerG1);
            this.Text = "Digital Casting System";
            this.Controls.SetChildIndex(this.ControllerG1, 0);
            this.Controls.SetChildIndex(this.button1, 0);
            this.Controls.SetChildIndex(this.button2, 0);
            this.Controls.SetChildIndex(this.button3, 0);
            this.Controls.SetChildIndex(this.button4, 0);
            this.Controls.SetChildIndex(this.button5, 0);
            this.Controls.SetChildIndex(this.button6, 0);
            this.Controls.SetChildIndex(this.button7, 0);
            this.Controls.SetChildIndex(this.button8, 0);
            this.Controls.SetChildIndex(this.ConcretePumpG1, 0);
            this.Controls.SetChildIndex(this.InlineMixerGroup1, 0);
            this.Controls.SetChildIndex(this.groupBox1, 0);
            this.Controls.SetChildIndex(this.groupBox2, 0);
            this.InlineMixerGroup1.ResumeLayout(false);
            this.ControllerG1.ResumeLayout(false);
            this.ControllerG13.ResumeLayout(false);
            this.ControllerG12.ResumeLayout(false);
            this.ConcretePumpG1.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void button2_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Mixer));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button2_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button3_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(ConPump));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button3_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button4_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(DosPumpH));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button4_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button5_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(DosPumpL));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button5_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button6_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Sys));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button6_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button7_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Spare));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button7_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button8_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(Spare2));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button8_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_MI1_SetRun_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalInvert
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_MI1SetRun"))).Invert();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_MI1_SetRun_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_CC1_Enable_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalInvert
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_CC1Enable"))).Invert();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_CC1_Enable_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_CC1_Reset_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalPulse
                ABB.Robotics.ScreenMaker.Base.IApplicationVariable time_0 = this.ScreenServices.ApplicationVariables["ResetTime"];
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_CC1Reset"))).Pulse(int.Parse(time_0.Value.ToString()));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_CC1_Reset_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_goInfo(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(MainInfo));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_goInfo", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button1_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ScreenOpen
                this.ShowScreen(typeof(MainScreen));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button1_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_MI1_Enable_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalInvert
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_MI1Enable"))).Invert();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_MI1_Enable_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_CP1_SetRun_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalInvert
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_CP1ForwardOn"))).Invert();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_CP1_SetRun_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_AP1_SetRun_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalInvert
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_AP1SetRun"))).Invert();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_AP1_SetRun_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void btn_A061_SP1_SetRun_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalInvert
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/doA061_SP1SetRun"))).Invert();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in btn_A061_SP1_SetRun_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        #region Protected Methods
        protected override void OnInstall(ABB.Robotics.ScreenMaker.Base.IScreenServices services)
        {
            if ((services.ApplicationVariables.Count == 0))
            {
                // 
                // ResetTime
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable ResetTime = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("ResetTime", "3000", typeof(ABB.Robotics.Controllers.RapidDomain.Num));
                // 
                // MI1Speed
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable MI1Speed = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("MI1Speed", "0", typeof(ABB.Robotics.Controllers.RapidDomain.Num));
                // 
                // temperature
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable temperature = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("temperature", "0", typeof(ABB.Robotics.Controllers.RapidDomain.Num));
                // 
                // Mi1TorqueM1
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable Mi1TorqueM1 = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("Mi1TorqueM1", "0", typeof(ABB.Robotics.Controllers.RapidDomain.Num));
                // 
                // Store variables
                // 
                services.ApplicationVariables.Add("ResetTime", ResetTime);
                services.ApplicationVariables.Add("MI1Speed", MI1Speed);
                services.ApplicationVariables.Add("temperature", temperature);
                services.ApplicationVariables.Add("Mi1TorqueM1", Mi1TorqueM1);
            }
            base.OnInstall(services);
        }
        #endregion
    }
}
